"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {AlertTriangle,BadgePercent,BellRing,Building2,CheckCheck,Clock3,Command,Loader2,RefreshCw,Search,ShieldAlert,TicketCheck,UserRound,UsersRound,Wallet} from "lucide-react";

type Result={id:number;reference:string;title:string;subtitle:string;status:string;created_at:string;kind:"customer_order"|"captain_order"|"captain"|"promo"|"company"};
type Note={key:string;type:string;severity:"danger"|"warning"|"info";title:string;detail:string;href:string;createdAt:string;read:boolean};
const kindMeta={customer_order:{label:"طلب زبون",icon:TicketCheck},captain_order:{label:"طلب كابتن",icon:TicketCheck},captain:{label:"كابتن",icon:UserRound},promo:{label:"خصم",icon:BadgePercent},company:{label:"شركة",icon:Building2}} as const;
const dt=(v:string)=>{try{return new Intl.DateTimeFormat("ar-IQ",{timeZone:"Asia/Baghdad",dateStyle:"short",timeStyle:"short"}).format(new Date(v))}catch{return "—"}};

export default function CommandCenter(){
 const [token,setToken]=useState("");const [name,setName]=useState("الإدارة");const [q,setQ]=useState("");const [results,setResults]=useState<Result[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [loading,setLoading]=useState(true);const [searching,setSearching]=useState(false);const [error,setError]=useState("");const input=useRef<HTMLInputElement|null>(null);
 useEffect(()=>{const t=sessionStorage.getItem("mainAdminToken")||"";if(!t){location.replace("/admin");return}setToken(t);void load(t,"")},[]);
 useEffect(()=>{const on=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();input.current?.focus()}};window.addEventListener("keydown",on);return()=>window.removeEventListener("keydown",on)},[]);
 async function api(path:string,opt:RequestInit={},t=token){return fetch(path,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`}})}
 async function load(t=token,query=q){setError("");if(!query)setLoading(true);else setSearching(true);try{const params=query.trim().length>=2?`?q=${encodeURIComponent(query.trim())}`:"";const r=await api(`/api/admin/command${params}`,{},t);const x=await r.json();if(r.status===401||r.status===403){location.replace("/admin");return}if(!r.ok)throw new Error(x.message||"تعذر تحميل مركز القيادة");setName(x.session?.name||"الإدارة");setResults(x.results||[]);setNotes(x.notifications||[])}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false);setSearching(false)}}
 function submit(e:FormEvent){e.preventDefault();void load(token,q)}
 async function mark(key:string){await api("/api/admin/command",{method:"PATCH",body:JSON.stringify({key})});setNotes(v=>v.map(n=>n.key===key?{...n,read:true}:n))}
 async function markAll(){await api("/api/admin/command",{method:"PATCH",body:JSON.stringify({all:true})});setNotes(v=>v.map(n=>({...n,read:true})))}
 const unread=notes.filter(n=>!n.read).length;
 const counts=useMemo(()=>({danger:notes.filter(n=>!n.read&&n.severity==="danger").length,warning:notes.filter(n=>!n.read&&n.severity==="warning").length,info:notes.filter(n=>!n.read&&n.severity==="info").length}),[notes]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#071f2b]"><Loader2 className="size-8 animate-spin text-[#d6ad68]"/></main>;
 return <main dir="rtl" className="min-h-screen bg-[#eef2f4] text-[#17384a]">
  <header className="border-b border-white/10 bg-[#071f2b] text-white"><div className="mx-auto max-w-[1500px] px-4 py-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end"><div className="flex-1"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-[#d6ad68] text-[#12394d]"><Command className="size-6"/></span><div><p className="text-[9px] tracking-[.2em] text-[#d6ad68]">GLOBAL COMMAND CENTER</p><h1 className="mt-1 text-2xl font-bold">مركز القيادة والبحث</h1><p className="mt-1 text-xs text-white/45">{name} · كل بيانات التشغيل من نقطة واحدة</p></div></div></div><form onSubmit={submit} className="flex w-full gap-2 lg:max-w-2xl"><div className="relative flex-1"><Search className="absolute right-4 top-1/2 size-4 -translate-y-1/2 text-white/35"/><input ref={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث برقم طلب، هاتف، شركة، كابتن، بروموكود..." className="h-14 w-full rounded-2xl border border-white/10 bg-white/7 pr-11 pl-4 text-sm text-white outline-none placeholder:text-white/30 focus:border-[#d6ad68]/60"/></div><button disabled={searching||q.trim().length<2} className="grid h-14 min-w-14 place-items-center rounded-2xl bg-[#d6ad68] text-[#12394d] disabled:opacity-40">{searching?<Loader2 className="size-5 animate-spin"/>:<Search className="size-5"/>}</button></form></div><div className="mt-3 text-[10px] text-white/30">اختصار البحث: Ctrl / ⌘ + K</div></div></header>
  <div className="mx-auto grid max-w-[1500px] gap-6 p-4 lg:grid-cols-[1fr_420px] lg:p-8">
   <section className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">نتائج البحث</h2><p className="mt-1 text-xs text-slate-400">البحث يشمل الطلبات والكباتن والشركات والخصومات</p></div>{q&&<button onClick={()=>load()} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs shadow-sm"><RefreshCw className="size-4"/>تحديث</button>}</div>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {!q.trim()&&<div className="rounded-[28px] border border-dashed border-slate-300 bg-white p-12 text-center"><Search className="mx-auto size-10 text-slate-300"/><h3 className="mt-4 font-bold">ابحث بأي معلومة تعرفها</h3><p className="mx-auto mt-2 max-w-md text-xs leading-6 text-slate-400">مثلاً رقم المسافر، اسم الشركة، اسم الكابتن، رقم الطلب أو كود الخصم. النظام يجمعلك كل النتائج المرتبطة.</p></div>}
    {q.trim()&&results.length===0&&!searching&&<div className="rounded-[28px] bg-white p-12 text-center text-sm text-slate-400">ماكو نتائج مطابقة</div>}
    <div className="grid gap-3 xl:grid-cols-2">{results.map((r,i)=>{const m=kindMeta[r.kind];const Icon=m.icon;return <article key={`${r.kind}-${r.id}-${i}`} className="rounded-[22px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#edf4f6] text-[#286b82]"><Icon className="size-5"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] text-slate-500">{m.label}</span><span className="truncate font-mono text-[10px] text-slate-400">{r.reference}</span></div><h3 className="mt-2 truncate font-bold">{r.title}</h3><p className="mt-1 truncate text-xs text-slate-400">{r.subtitle||"—"}</p><div className="mt-3 flex items-center justify-between border-t pt-3 text-[10px] text-slate-400"><span>{r.status}</span><span>{dt(r.created_at)}</span></div></div></div></article>})}</div>
   </section>
   <aside className="space-y-4"><div className="rounded-[28px] bg-[#0b3042] p-5 text-white shadow-xl"><div className="flex items-center justify-between"><div><p className="text-[9px] tracking-[.16em] text-[#d6ad68]">OPERATIONS INBOX</p><h2 className="mt-1 text-xl font-bold">مركز التنبيهات</h2></div><span className="grid size-12 place-items-center rounded-2xl bg-white/10"><BellRing className="size-5"/></span></div><div className="mt-5 grid grid-cols-3 gap-2"><Stat label="حرج" value={counts.danger} icon={<ShieldAlert/>}/><Stat label="مهم" value={counts.warning} icon={<AlertTriangle/>}/><Stat label="تنبيه" value={counts.info} icon={<Clock3/>}/></div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-white/50">غير مقروء: {unread}</span><button onClick={markAll} disabled={!unread} className="flex items-center gap-1 rounded-lg bg-white/10 px-3 py-2 disabled:opacity-30"><CheckCheck className="size-4"/>تعليم الكل كمقروء</button></div></div>
    <div className="space-y-2">{notes.map(n=><article key={n.key} className={`rounded-[20px] border bg-white p-4 shadow-sm transition ${n.read?"opacity-55":""} ${n.severity==="danger"?"border-red-200":n.severity==="warning"?"border-amber-200":"border-slate-200"}`}><div className="flex items-start gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${n.read?"bg-slate-300":n.severity==="danger"?"bg-red-500":n.severity==="warning"?"bg-amber-500":"bg-blue-500"}`}/><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">{n.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{n.detail}</p><div className="mt-3 flex items-center justify-between gap-2"><a href={n.href} className="text-[10px] font-bold text-[#25677e]">فتح القسم</a>{!n.read&&<button onClick={()=>mark(n.key)} className="rounded-lg bg-slate-100 px-2 py-1 text-[9px] text-slate-500">تمت القراءة</button>}</div></div></div></article>)}{!notes.length&&<div className="rounded-[22px] bg-white p-8 text-center text-xs text-slate-400">ماكو تنبيهات حالياً</div>}</div>
   </aside>
  </div>
 </main>
}
function Stat({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="rounded-xl bg-white/8 p-3 text-center"><div className="mx-auto grid size-7 place-items-center text-[#d6ad68]">{icon}</div><div className="mt-1 text-lg font-bold">{value}</div><div className="text-[9px] text-white/45">{label}</div></div>}
