"use client";
import { useEffect,useState } from "react";

type Company={id:number;name:string;price_iqd:number|string;billing_type:string;active:boolean;notes:string};
const paymentLabels:Record<string,string>={cash:"نقدي",electronic:"إلكتروني",credit:"آجل / حساب شركة",prepaid:"مدفوع مسبقاً",voucher:"قسيمة",complimentary:"مجاني"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#07111f",color:"#f8fafc",border:"1px solid #334155",borderRadius:11,padding:"12px 13px",fontSize:16};
const card:React.CSSProperties={background:"#0d1829",border:"1px solid #1f2d42",borderRadius:18,padding:17};
const btn:React.CSSProperties={border:"1px solid #c8a66a",background:"#c8a66a",color:"#07111f",borderRadius:10,padding:"11px 14px",fontWeight:900,cursor:"pointer"};
export default function PricingSettings(){
 const [settings,setSettings]=useState<any>({default_price_iqd:40000,default_payment_type:"cash",allow_manual_override:true,require_override_reason:true});
 const [companies,setCompanies]=useState<Company[]>([]);const [msg,setMsg]=useState("");
 const [company,setCompany]=useState({name:"",priceIqd:"40000",billingType:"credit",active:true,notes:""});
 async function load(){const [a,b]=await Promise.all([fetch("/api/ops/pricing",{cache:"no-store"}),fetch("/api/ops/admin?action=companies",{cache:"no-store"})]);if(a.ok)setSettings((await a.json()).settings||settings);if(b.ok)setCompanies((await b.json()).companies||[])}
 useEffect(()=>{load()},[]);
 async function saveSettings(){setMsg("");const r=await fetch("/api/ops/pricing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({defaultPriceIqd:Number(settings.default_price_iqd||0),defaultPaymentType:settings.default_payment_type,allowManualOverride:settings.allow_manual_override,requireOverrideReason:settings.require_override_reason})});const d=await r.json();setMsg(r.ok?"تم حفظ إعدادات السعر العام":d.message||"تعذر الحفظ");if(r.ok)load()}
 async function saveCompany(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/ops/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"saveCompany",...company,priceIqd:Number(company.priceIqd||0)})});const d=await r.json();setMsg(r.ok?"تم حفظ سعر الشركة":d.message||"تعذر حفظ الشركة");if(r.ok){setCompany({name:"",priceIqd:String(settings.default_price_iqd||40000),billingType:"credit",active:true,notes:""});load()}}
 async function edit(c:Company){setCompany({name:c.name,priceIqd:String(c.price_iqd),billingType:c.billing_type,active:c.active,notes:c.notes||""});window.scrollTo({top:0,behavior:"smooth"})}
 return <main dir="rtl" style={{minHeight:"100vh",background:"#07111f",color:"#f8fafc",padding:16,fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap",marginBottom:18}}><div><div style={{color:"#c8a66a",fontWeight:900}}>PRICING CONTROL</div><h1 style={{margin:"6px 0"}}>إعدادات أسعار المسافرين</h1><div style={{color:"#94a3b8"}}>المصدر المركزي للسعر الذي يظهر تلقائياً بواجهة الموظف.</div></div><div style={{display:"flex",gap:8}}><a href="/ops/admin" style={{...btn,background:"#111d30",color:"#e2e8f0",borderColor:"#334155",textDecoration:"none"}}>لوحة الإدارة</a><a href="/ops/admin/companies" style={{...btn,background:"#111d30",color:"#e2e8f0",borderColor:"#334155",textDecoration:"none"}}>التسويات</a></div></header>
  {msg&&<div style={{...card,marginBottom:14,borderColor:"#8a6f3e"}}>{msg}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14,marginBottom:16}}>
   <div style={card}><h2 style={{marginTop:0}}>السعر العام</h2><label>سعر المسافر العادي<input style={{...input,marginTop:7}} inputMode="numeric" value={settings.default_price_iqd||""} onChange={e=>setSettings({...settings,default_price_iqd:e.target.value.replace(/\D/g,"")})}/></label><label style={{display:"block",marginTop:12}}>طريقة الحساب الافتراضية<select style={{...input,marginTop:7}} value={settings.default_payment_type||"cash"} onChange={e=>setSettings({...settings,default_payment_type:e.target.value})}>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{display:"flex",gap:9,marginTop:14}}><input type="checkbox" checked={Boolean(settings.allow_manual_override)} onChange={e=>setSettings({...settings,allow_manual_override:e.target.checked})}/>السماح للموظف بتعديل السعر يدوياً</label><label style={{display:"flex",gap:9,marginTop:10}}><input type="checkbox" checked={Boolean(settings.require_override_reason)} onChange={e=>setSettings({...settings,require_override_reason:e.target.checked})}/>طلب سبب عند تغيير السعر يدوياً</label><button style={{...btn,width:"100%",marginTop:15}} onClick={saveSettings}>حفظ إعدادات السعر العام</button></div>
   <form style={card} onSubmit={saveCompany}><h2 style={{marginTop:0}}>سعر خاص لشركة</h2><label>اسم الشركة<input required style={{...input,marginTop:7}} value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/></label><label style={{display:"block",marginTop:12}}>سعر الشخص<input style={{...input,marginTop:7}} inputMode="numeric" value={company.priceIqd} onChange={e=>setCompany({...company,priceIqd:e.target.value.replace(/\D/g,"")})}/></label><label style={{display:"block",marginTop:12}}>نوع الحساب<select style={{...input,marginTop:7}} value={company.billingType} onChange={e=>setCompany({...company,billingType:e.target.value})}>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{display:"block",marginTop:12}}>ملاحظات<input style={{...input,marginTop:7}} value={company.notes} onChange={e=>setCompany({...company,notes:e.target.value})}/></label><label style={{display:"flex",gap:9,marginTop:12}}><input type="checkbox" checked={company.active} onChange={e=>setCompany({...company,active:e.target.checked})}/>الشركة فعالة</label><button style={{...btn,width:"100%",marginTop:15}}>حفظ سعر الشركة</button></form>
  </section>
  <section style={card}><h2 style={{marginTop:0}}>قائمة الأسعار الخاصة</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720}}><thead><tr>{["الشركة","سعر الشخص","طريقة الحساب","الحالة","ملاحظات",""].map(x=><th key={x} style={{textAlign:"right",padding:10,borderBottom:"1px solid #334155",color:"#94a3b8"}}>{x}</th>)}</tr></thead><tbody>{companies.map(c=><tr key={c.id}><td style={{padding:10,borderBottom:"1px solid #1f2d42",fontWeight:900}}>{c.name}</td><td style={{padding:10,borderBottom:"1px solid #1f2d42"}}>{Number(c.price_iqd||0).toLocaleString("en-US")} د.ع</td><td style={{padding:10,borderBottom:"1px solid #1f2d42"}}>{paymentLabels[c.billing_type]||c.billing_type}</td><td style={{padding:10,borderBottom:"1px solid #1f2d42"}}>{c.active?"فعال":"موقوف"}</td><td style={{padding:10,borderBottom:"1px solid #1f2d42"}}>{c.notes||"—"}</td><td style={{padding:10,borderBottom:"1px solid #1f2d42"}}><button onClick={()=>edit(c)} style={{...btn,padding:"7px 10px"}}>تعديل</button></td></tr>)}</tbody></table></div></section>
 </div></main>
}
