"use client";
import { useEffect,useMemo,useState } from "react";

type Company={id:number;name:string;price_iqd:number|string;billing_type:string;active:boolean;notes:string};
type Rule={id:number;rule_type:string;key_value:string;label:string;price_iqd:number|string;payment_type:string;active:boolean;priority:number;valid_from?:string;valid_to?:string};
const paymentLabels:Record<string,string>={cash:"نقدي",electronic:"إلكتروني",credit:"آجل / حساب شركة",prepaid:"مدفوع مسبقاً",voucher:"قسيمة",complimentary:"مجاني"};
const ruleLabels:Record<string,string>={lounge:"حسب الصالة",shift:"حسب الشفت",category:"حسب فئة المسافر",promotion:"عرض مؤقت",airline:"حسب شركة الطيران",special:"شخص / كود خاص"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#07111f",color:"#f8fafc",border:"1px solid #334155",borderRadius:11,padding:"12px 13px",fontSize:16};
const card:React.CSSProperties={background:"#0d1829",border:"1px solid #1f2d42",borderRadius:18,padding:17};
const btn:React.CSSProperties={border:"1px solid #c8a66a",background:"#c8a66a",color:"#07111f",borderRadius:10,padding:"11px 14px",fontWeight:900,cursor:"pointer"};
export default function PricingSettings(){
 const [settings,setSettings]=useState<any>({default_price_iqd:40000,default_payment_type:"cash",allow_manual_override:true,require_override_reason:true,override_min_iqd:0,override_max_iqd:1000000,override_roles:["owner","manager","supervisor"],discount_reasons:["شركة","VIP","عرض","موافقة مدير","تصحيح خطأ"],abnormal_low_iqd:20000,abnormal_high_iqd:100000,child_free_under:0});
 const [companies,setCompanies]=useState<Company[]>([]);const [rules,setRules]=useState<Rule[]>([]);const [audit,setAudit]=useState<any[]>([]);const [msg,setMsg]=useState("");
 const [company,setCompany]=useState({id:0,name:"",priceIqd:"40000",billingType:"credit",active:true,notes:""});
 const [rule,setRule]=useState({id:0,ruleType:"lounge",keyValue:"",label:"",priceIqd:"40000",paymentType:"cash",priority:"100",validFrom:"",validTo:"",active:true});
 async function load(){const [a,b,c,d]=await Promise.all([fetch("/api/ops/pricing",{cache:"no-store"}),fetch("/api/ops/admin?action=companies",{cache:"no-store"}),fetch("/api/ops/pricing?action=rules",{cache:"no-store"}),fetch("/api/ops/pricing?action=audit",{cache:"no-store"})]);if(a.ok)setSettings((await a.json()).settings||settings);if(b.ok)setCompanies((await b.json()).companies||[]);if(c.ok)setRules((await c.json()).rules||[]);if(d.ok)setAudit((await d.json()).audit||[])}
 useEffect(()=>{load()},[]);
 async function saveSettings(){setMsg("");const r=await fetch("/api/ops/pricing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({defaultPriceIqd:Number(settings.default_price_iqd||0),defaultPaymentType:settings.default_payment_type,allowManualOverride:settings.allow_manual_override,requireOverrideReason:settings.require_override_reason,overrideMinIqd:Number(settings.override_min_iqd||0),overrideMaxIqd:Number(settings.override_max_iqd||0),overrideRoles:settings.override_roles||[],discountReasons:settings.discount_reasons||[],abnormalLowIqd:Number(settings.abnormal_low_iqd||0),abnormalHighIqd:Number(settings.abnormal_high_iqd||0),childFreeUnder:Number(settings.child_free_under||0)})});const d=await r.json();setMsg(r.ok?"تم حفظ إعدادات التسعير":d.message||"تعذر الحفظ");if(r.ok)load()}
 async function saveCompany(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/ops/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"saveCompany",...company,id:company.id||undefined,priceIqd:Number(company.priceIqd||0)})});const d=await r.json();setMsg(r.ok?"تم حفظ سعر الشركة":d.message||"تعذر حفظ الشركة");if(r.ok){setCompany({id:0,name:"",priceIqd:String(settings.default_price_iqd||40000),billingType:"credit",active:true,notes:""});load()}}
 async function saveRule(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/ops/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"saveRule",id:rule.id||undefined,ruleType:rule.ruleType,keyValue:rule.keyValue,label:rule.label,priceIqd:Number(rule.priceIqd||0),paymentType:rule.paymentType,priority:Number(rule.priority||100),validFrom:rule.validFrom||null,validTo:rule.validTo||null,active:rule.active})});const d=await r.json();setMsg(r.ok?"تم حفظ قاعدة السعر":d.message||"تعذر حفظ القاعدة");if(r.ok){setRule({id:0,ruleType:"lounge",keyValue:"",label:"",priceIqd:String(settings.default_price_iqd||40000),paymentType:"cash",priority:"100",validFrom:"",validTo:"",active:true});load()}}
 async function removeRule(id:number){if(!confirm("حذف قاعدة السعر؟"))return;await fetch("/api/ops/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"deleteRule",id})});load()}
 async function reset(){if(!confirm("ترجع كل قواعد الأسعار المتقدمة للإعداد الافتراضي 40,000؟"))return;const r=await fetch("/api/ops/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reset"})});setMsg(r.ok?"تم إرجاع إعدادات الأسعار الافتراضية":"تعذر الإرجاع");load()}
 function editCompany(c:Company){setCompany({id:c.id,name:c.name,priceIqd:String(c.price_iqd),billingType:c.billing_type,active:c.active,notes:c.notes||""});window.scrollTo({top:0,behavior:"smooth"})}
 function editRule(r:Rule){setRule({id:r.id,ruleType:r.rule_type,keyValue:r.key_value,label:r.label||"",priceIqd:String(r.price_iqd),paymentType:r.payment_type,priority:String(r.priority||100),validFrom:r.valid_from?String(r.valid_from).slice(0,16):"",validTo:r.valid_to?String(r.valid_to).slice(0,16):"",active:r.active});window.scrollTo({top:0,behavior:"smooth"})}
 const preview=useMemo(()=>[{name:"مسافر عادي",price:Number(settings.default_price_iqd||0),type:settings.default_payment_type},{name:companies[0]?.name||"شركة نموذجية",price:Number(companies[0]?.price_iqd||settings.default_price_iqd||0),type:companies[0]?.billing_type||settings.default_payment_type}], [settings,companies]);
 return <main dir="rtl" style={{minHeight:"100vh",background:"#07111f",color:"#f8fafc",padding:16,fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1240,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap",marginBottom:18}}><div><div style={{color:"#c8a66a",fontWeight:900}}>PRICING CONTROL CENTER</div><h1 style={{margin:"6px 0"}}>إعدادات أسعار المسافرين</h1><div style={{color:"#94a3b8"}}>تحكم مركزي بالسعر العام، الشركات، الصالات، الشفتات، الفئات، شركات الطيران والعروض.</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={reset} style={{...btn,background:"#401b1b",color:"#fecaca",borderColor:"#7f1d1d"}}>إرجاع الافتراضي</button><a href="/ops/admin" style={{...btn,background:"#111d30",color:"#e2e8f0",borderColor:"#334155",textDecoration:"none"}}>لوحة الإدارة</a></div></header>
  {msg&&<div style={{...card,marginBottom:14,borderColor:"#8a6f3e"}}>{msg}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14,marginBottom:16}}>
   <div style={card}><h2 style={{marginTop:0}}>الإعداد العام والحماية</h2><Field label="سعر المسافر العام"><input style={input} inputMode="numeric" value={settings.default_price_iqd||""} onChange={e=>setSettings({...settings,default_price_iqd:e.target.value.replace(/\D/g,"")})}/></Field><Field label="طريقة الحساب الافتراضية"><select style={input} value={settings.default_payment_type||"cash"} onChange={e=>setSettings({...settings,default_payment_type:e.target.value})}>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Field label="أقل سعر تعديل"><input style={input} inputMode="numeric" value={settings.override_min_iqd||0} onChange={e=>setSettings({...settings,override_min_iqd:e.target.value.replace(/\D/g,"")})}/></Field><Field label="أعلى سعر تعديل"><input style={input} inputMode="numeric" value={settings.override_max_iqd||0} onChange={e=>setSettings({...settings,override_max_iqd:e.target.value.replace(/\D/g,"")})}/></Field></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Field label="تنبيه أقل من"><input style={input} inputMode="numeric" value={settings.abnormal_low_iqd||0} onChange={e=>setSettings({...settings,abnormal_low_iqd:e.target.value.replace(/\D/g,"")})}/></Field><Field label="تنبيه أعلى من"><input style={input} inputMode="numeric" value={settings.abnormal_high_iqd||0} onChange={e=>setSettings({...settings,abnormal_high_iqd:e.target.value.replace(/\D/g,"")})}/></Field></div><Field label="مجاني لمن عمره أقل من"><input style={input} inputMode="numeric" value={settings.child_free_under||0} onChange={e=>setSettings({...settings,child_free_under:e.target.value.replace(/\D/g,"")})}/></Field><label style={{display:"flex",gap:9,marginTop:10}}><input type="checkbox" checked={Boolean(settings.allow_manual_override)} onChange={e=>setSettings({...settings,allow_manual_override:e.target.checked})}/>السماح بتعديل السعر يدوياً</label><label style={{display:"flex",gap:9,marginTop:10}}><input type="checkbox" checked={Boolean(settings.require_override_reason)} onChange={e=>setSettings({...settings,require_override_reason:e.target.checked})}/>سبب إلزامي عند تغيير السعر</label><Field label="الأدوار المسموح لها بالتعديل (مفصولة بفاصلة)"><input style={input} value={(settings.override_roles||[]).join(",")} onChange={e=>setSettings({...settings,override_roles:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></Field><Field label="أسباب الخصم الجاهزة"><input style={input} value={(settings.discount_reasons||[]).join(",")} onChange={e=>setSettings({...settings,discount_reasons:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></Field><button style={{...btn,width:"100%"}} onClick={saveSettings}>حفظ الإعداد العام</button></div>
   <form style={card} onSubmit={saveCompany}><h2 style={{marginTop:0}}>سعر خاص لشركة</h2><Field label="اسم الشركة"><input required style={input} value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/></Field><Field label="سعر الشخص"><input style={input} inputMode="numeric" value={company.priceIqd} onChange={e=>setCompany({...company,priceIqd:e.target.value.replace(/\D/g,"")})}/></Field><Field label="نوع الحساب"><select style={input} value={company.billingType} onChange={e=>setCompany({...company,billingType:e.target.value})}>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="ملاحظات"><input style={input} value={company.notes} onChange={e=>setCompany({...company,notes:e.target.value})}/></Field><label style={{display:"flex",gap:9,marginTop:12}}><input type="checkbox" checked={company.active} onChange={e=>setCompany({...company,active:e.target.checked})}/>الشركة فعالة</label><button style={{...btn,width:"100%",marginTop:15}}>حفظ سعر الشركة</button></form>
   <form style={card} onSubmit={saveRule}><h2 style={{marginTop:0}}>قاعدة سعر متقدمة</h2><Field label="نوع القاعدة"><select style={input} value={rule.ruleType} onChange={e=>setRule({...rule,ruleType:e.target.value})}>{Object.entries(ruleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="القيمة (مثلاً عراق لاونج / الليلي / IA / VIP-001)"><input required style={input} value={rule.keyValue} onChange={e=>setRule({...rule,keyValue:e.target.value})}/></Field><Field label="اسم توضيحي"><input style={input} value={rule.label} onChange={e=>setRule({...rule,label:e.target.value})}/></Field><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Field label="السعر"><input style={input} inputMode="numeric" value={rule.priceIqd} onChange={e=>setRule({...rule,priceIqd:e.target.value.replace(/\D/g,"")})}/></Field><Field label="الأولوية"><input style={input} inputMode="numeric" value={rule.priority} onChange={e=>setRule({...rule,priority:e.target.value.replace(/\D/g,"")})}/></Field></div><Field label="طريقة الحساب"><select style={input} value={rule.paymentType} onChange={e=>setRule({...rule,paymentType:e.target.value})}>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Field label="يبدأ"><input type="datetime-local" style={input} value={rule.validFrom} onChange={e=>setRule({...rule,validFrom:e.target.value})}/></Field><Field label="ينتهي"><input type="datetime-local" style={input} value={rule.validTo} onChange={e=>setRule({...rule,validTo:e.target.value})}/></Field></div><label style={{display:"flex",gap:9,marginTop:8}}><input type="checkbox" checked={rule.active} onChange={e=>setRule({...rule,active:e.target.checked})}/>القاعدة فعالة</label><button style={{...btn,width:"100%",marginTop:15}}>حفظ قاعدة السعر</button></form>
  </section>
  <section style={{...card,marginBottom:16}}><h2 style={{marginTop:0}}>معاينة سريعة</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{preview.map(p=><div key={p.name} style={{background:"#07111f",border:"1px solid #334155",borderRadius:12,padding:14}}><div style={{color:"#94a3b8"}}>{p.name}</div><div style={{fontSize:24,fontWeight:950,marginTop:5}}>{p.price.toLocaleString("en-US")} د.ع</div><div style={{color:"#c8a66a",marginTop:5}}>{paymentLabels[p.type]||p.type}</div></div>)}</div></section>
  <section style={{...card,marginBottom:16}}><h2 style={{marginTop:0}}>قواعد الأسعار المتقدمة</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{["النوع","القيمة","الوصف","السعر","الحساب","الأولوية","الحالة",""].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{rules.map(r=><tr key={r.id}><td style={td}>{ruleLabels[r.rule_type]||r.rule_type}</td><td style={td}>{r.key_value}</td><td style={td}>{r.label||"—"}</td><td style={td}>{Number(r.price_iqd||0).toLocaleString("en-US")}</td><td style={td}>{paymentLabels[r.payment_type]||r.payment_type}</td><td style={td}>{r.priority}</td><td style={td}>{r.active?"فعال":"موقوف"}</td><td style={td}><button onClick={()=>editRule(r)} style={{...btn,padding:"7px 9px",marginLeft:6}}>تعديل</button><button onClick={()=>removeRule(r.id)} style={{...btn,padding:"7px 9px",background:"#401b1b",color:"#fecaca",borderColor:"#7f1d1d"}}>حذف</button></td></tr>)}</tbody></table></div></section>
  <section style={{...card,marginBottom:16}}><h2 style={{marginTop:0}}>أسعار الشركات</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720}}><thead><tr>{["الشركة","السعر","الحساب","الحالة","ملاحظات",""].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{companies.map(c=><tr key={c.id}><td style={td}>{c.name}</td><td style={td}>{Number(c.price_iqd||0).toLocaleString("en-US")}</td><td style={td}>{paymentLabels[c.billing_type]||c.billing_type}</td><td style={td}>{c.active?"فعال":"موقوف"}</td><td style={td}>{c.notes||"—"}</td><td style={td}><button onClick={()=>editCompany(c)} style={{...btn,padding:"7px 10px"}}>تعديل</button></td></tr>)}</tbody></table></div></section>
  <section style={card}><h2 style={{marginTop:0}}>سجل تغييرات الأسعار</h2><div style={{overflowX:"auto",maxHeight:420}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr>{["الوقت","المستخدم","العملية","النوع","المعرف"].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{audit.map(a=><tr key={a.id}><td style={td}>{new Date(a.created_at).toLocaleString("ar-IQ")}</td><td style={td}>{a.actor||"—"}</td><td style={td}>{a.action}</td><td style={td}>{a.entity_type}</td><td style={td}>{a.entity_id}</td></tr>)}</tbody></table></div></section>
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:7,marginBottom:12}}><span style={{color:"#cbd5e1",fontSize:14,fontWeight:800}}>{label}</span>{children}</label>}
const th:React.CSSProperties={textAlign:"right",padding:10,borderBottom:"1px solid #334155",color:"#94a3b8"};const td:React.CSSProperties={padding:10,borderBottom:"1px solid #1f2d42"};
