"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowRight,BadgeDollarSign,Building2,CalendarDays,CircleDollarSign,FileText,Loader2,Printer,RefreshCw,Search,Users,Wallet,X} from "lucide-react";

type Invoice={id:number;invoice_number:string;company_name:string;period_from:string;period_to:string;issue_date:string;due_date:string;subtotal_iqd:number;status:string;paid_iqd:number;balance_iqd:number};
type Customer={phone:string;customer_name:string;bookings:number;spend:number;last_booking:string;cancelled:number};
type Company={name:string;price_per_passenger:number;credit_limit_iqd:number;due_iqd:number;paid_iqd:number;status:string};
type Profit={settings:Record<string,number>;revenueIqd:number;costIqd:number;profitIqd:number;marginPercent:number;passengers:number;cars:number};
type InvoiceDetail={invoice:any;items:any[];payments:any[];paidIqd:number;balanceIqd:number};
type CustomerDetail={phone:string;name:string;metrics:any;orders:any[]};
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(Number(n||0))+" د.ع";
const day=(v:string)=>new Intl.DateTimeFormat("ar-IQ",{timeZone:"Asia/Baghdad",dateStyle:"medium"}).format(new Date(v));
const status:Record<string,string>={unpaid:"غير مدفوعة",partial:"مدفوعة جزئياً",paid:"مدفوعة",void:"ملغاة"};

export default function BusinessWorkspace(){
 const [token,setToken]=useState("");const [tab,setTab]=useState<"invoices"|"customers"|"profit">("invoices");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const [invoices,setInvoices]=useState<Invoice[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [companies,setCompanies]=useState<Company[]>([]);const [profit,setProfit]=useState<Profit|null>(null);const [invoice,setInvoice]=useState<InvoiceDetail|null>(null);const [customer,setCustomer]=useState<CustomerDetail|null>(null);const [search,setSearch]=useState("");
 const today=new Date().toISOString().slice(0,10),month=today.slice(0,8)+"01";const due=new Date(Date.now()+14*86400000).toISOString().slice(0,10);
 const [newInvoice,setNewInvoice]=useState({companyName:"",from:month,to:today,dueDate:due,notes:""});const [payment,setPayment]=useState({amountIqd:"",note:""});
 useEffect(()=>{const t=sessionStorage.getItem("mainAdminToken")||sessionStorage.getItem("accountingAdminToken")||"";if(!t){location.replace("/admin");return}setToken(t);void load(t)},[]);
 async function api(path:string,opt:RequestInit={},t=token){return fetch(path,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`}})}
 async function load(t=token){setLoading(true);setMessage("");try{const [a,b]=await Promise.all([api("/api/admin/business?action=summary",{},t),api("/api/admin/business?action=companies",{},t)]);const [x,y]=await Promise.all([a.json(),b.json()]);if(!a.ok||!b.ok)throw new Error(x.message||y.message||"تعذر تحميل مركز الأعمال");setInvoices(x.invoices||[]);setCustomers(x.customers||[]);setProfit(x.profit||null);setCompanies(y.companies||[])}catch(e){setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await api("/api/admin/business",{method:"POST",body:JSON.stringify({action:"invoice",...newInvoice})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر إنشاء الفاتورة");return}setInvoice(x.invoice);await load();}finally{setBusy(false)}}
 async function openInvoice(id:number){setBusy(true);try{const r=await api(`/api/admin/business?action=invoice&id=${id}`);const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر فتح الفاتورة");return}setInvoice(x.invoice)}finally{setBusy(false)}}
 async function addPayment(e:FormEvent){e.preventDefault();if(!invoice)return;setBusy(true);try{const r=await api("/api/admin/business",{method:"POST",body:JSON.stringify({action:"payment",invoiceId:invoice.invoice.id,amountIqd:Number(payment.amountIqd),note:payment.note})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر تسجيل الدفعة");return}setPayment({amountIqd:"",note:""});await openInvoice(invoice.invoice.id);await load()}finally{setBusy(false)}}
 async function voidInv(){if(!invoice||!confirm("إلغاء هذه الفاتورة؟"))return;setBusy(true);try{const r=await api("/api/admin/business",{method:"PATCH",body:JSON.stringify({action:"voidInvoice",id:invoice.invoice.id})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر إلغاء الفاتورة");return}setInvoice(x.invoice);await load()}finally{setBusy(false)}}
 async function openCustomer(phone:string){setBusy(true);try{const r=await api(`/api/admin/business?action=customer&phone=${encodeURIComponent(phone)}`);const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر فتح العميل");return}setCustomer(x.customer)}finally{setBusy(false)}}
 async function customerSearch(v:string){setSearch(v);if(v.trim().length<2){if(!v)await load();return}const r=await api(`/api/admin/business?action=customers&q=${encodeURIComponent(v)}`);const x=await r.json();if(r.ok)setCustomers(x.customers||[])}
 async function saveCost(key:string,value:number){setBusy(true);try{const r=await api("/api/admin/business",{method:"POST",body:JSON.stringify({action:"cost",key,value})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر حفظ التكلفة");return}const p=await api("/api/admin/business?action=profit");const px=await p.json();if(p.ok)setProfit(px.profit)}finally{setBusy(false)}}
 const totals=useMemo(()=>invoices.filter(i=>i.status!=="void").reduce((a,i)=>({due:a.due+Number(i.subtotal_iqd||0),paid:a.paid+Number(i.paid_iqd||0),balance:a.balance+Number(i.balance_iqd||0)}),{due:0,paid:0,balance:0}),[invoices]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#eef2f4]"><Loader2 className="size-8 animate-spin text-[#123f58]"/></main>;
 return <main dir="rtl" className="min-h-screen bg-[#eef2f4] text-[#12384b]">
  <header className="sticky top-0 z-30 border-b border-white/10 bg-[#082b3a] text-white"><div className="mx-auto flex max-w-[1500px] items-center gap-3 px-4 py-4 lg:px-8"><button onClick={()=>location.href="/admin/control"} className="grid size-10 place-items-center rounded-xl bg-white/10"><ArrowRight className="size-4"/></button><div className="flex-1"><div className="text-[9px] tracking-[.2em] text-[#d6ad68]">BUSINESS & FINANCE SUITE</div><h1 className="mt-1 text-xl font-bold">مركز الأعمال والمالية</h1></div><button onClick={()=>load()} className="grid size-10 place-items-center rounded-xl bg-white/10"><RefreshCw className="size-4"/></button></div></header>
  <div className="mx-auto max-w-[1500px] p-4 lg:p-8">
   {message&&<div className="mb-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-xs text-red-700">{message}</div>}
   <div className="mb-5 grid gap-3 md:grid-cols-4"><Kpi label="إجمالي الفواتير" value={money(totals.due)} icon={<FileText/>}/><Kpi label="المحصل" value={money(totals.paid)} icon={<Wallet/>}/><Kpi label="المتبقي" value={money(totals.balance)} icon={<CircleDollarSign/>}/><Kpi label="ربح الشهر التقديري" value={money(profit?.profitIqd||0)} icon={<BadgeDollarSign/>}/></div>
   <div className="mb-6 flex gap-2 overflow-auto">{[["invoices","الفواتير",FileText],["customers","Customer 360",Users],["profit","الربحية",BadgeDollarSign]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`flex min-w-max items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold ${tab===id?"bg-[#123f58] text-white":"bg-white text-[#456]"}`}><Icon className="size-4"/>{label}</button>)}</div>
   {tab==="invoices"&&<div className="grid gap-6 xl:grid-cols-[1fr_370px]"><Card title="الفواتير الرسمية" sub="Snapshot للسعر والطلبات وقت الإصدار"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-right text-xs"><thead><tr className="border-y bg-slate-50 text-[9px] text-slate-400"><th className="p-3">رقم الفاتورة</th><th>الشركة</th><th>الفترة</th><th>الاستحقاق</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id} onClick={()=>openInvoice(i.id)} className="cursor-pointer border-b hover:bg-slate-50"><td className="p-3 font-mono font-bold">{i.invoice_number}</td><td>{i.company_name}</td><td>{i.period_from} — {i.period_to}</td><td>{i.due_date}</td><td>{money(i.subtotal_iqd)}</td><td>{money(i.paid_iqd)}</td><td className="font-bold">{money(i.balance_iqd)}</td><td>{status[i.status]||i.status}</td></tr>)}</tbody></table></div></Card><Card title="إنشاء فاتورة" sub="الطلبات المفوترة سابقاً لا تتكرر"><form onSubmit={create} className="space-y-3"><select className="field" required value={newInvoice.companyName} onChange={e=>setNewInvoice({...newInvoice,companyName:e.target.value})}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.name} value={c.name}>{c.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className="field" type="date" value={newInvoice.from} onChange={e=>setNewInvoice({...newInvoice,from:e.target.value})}/><input className="field" type="date" value={newInvoice.to} onChange={e=>setNewInvoice({...newInvoice,to:e.target.value})}/></div><label className="block text-[10px] text-slate-400">تاريخ الاستحقاق<input className="field mt-1" type="date" value={newInvoice.dueDate} onChange={e=>setNewInvoice({...newInvoice,dueDate:e.target.value})}/></label><textarea className="field min-h-20" placeholder="ملاحظات الفاتورة" value={newInvoice.notes} onChange={e=>setNewInvoice({...newInvoice,notes:e.target.value})}/><button disabled={busy} className="w-full rounded-xl bg-[#123f58] px-4 py-3 text-xs font-bold text-white">إصدار فاتورة</button></form></Card></div>}
   {tab==="customers"&&<Card title="Customer 360" sub="ملف موحد لكل رقم هاتف وحجوزاته"><div className="mb-4 flex items-center gap-2 rounded-xl border bg-slate-50 px-3"><Search className="size-4 text-slate-400"/><input className="h-11 flex-1 bg-transparent text-sm outline-none" placeholder="ابحث بالاسم أو رقم الهاتف" value={search} onChange={e=>void customerSearch(e.target.value)}/></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{customers.map(c=><button key={c.phone} onClick={()=>openCustomer(c.phone)} className="rounded-2xl border bg-white p-4 text-right hover:border-[#d6ad68]"><div className="font-bold">{c.customer_name}</div><div dir="ltr" className="mt-1 text-xs text-slate-500">{c.phone}</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Mini label="الحجوزات" value={c.bookings}/><Mini label="الصرف" value={money(c.spend)}/><Mini label="ملغي" value={c.cancelled}/></div></button>)}</div></Card>}
   {tab==="profit"&&profit&&<div className="grid gap-6 xl:grid-cols-[1fr_380px]"><Card title="ربحية الشهر" sub="إيراد ناقص تكاليف التشغيل المسجلة"><div className="grid gap-3 sm:grid-cols-4"><Mini label="الإيراد" value={money(profit.revenueIqd)}/><Mini label="التكلفة" value={money(profit.costIqd)}/><Mini label="الربح" value={money(profit.profitIqd)}/><Mini label="الهامش" value={`${profit.marginPercent}%`}/></div><div className="mt-6 rounded-2xl bg-[#0d3546] p-6 text-white"><div className="text-[10px] text-white/50">مؤشر الربحية الحالي</div><div className="mt-2 text-4xl font-black text-[#d6ad68]">{profit.marginPercent}%</div><p className="mt-3 text-xs leading-6 text-white/55">محسوب من الحجوزات غير الملغاة لهذا الشهر وفق التكاليف المحددة.</p></div></Card><Card title="تكاليف التشغيل" sub="تدخلها الإدارة ويعاد الحساب فوراً"><Cost label="تكلفة الصالة / مسافر" value={profit.settings.lounge_cost_per_passenger||0} onSave={v=>saveCost("lounge_cost_per_passenger",v)}/><Cost label="تكلفة السيارة" value={profit.settings.car_cost||0} onSave={v=>saveCost("car_cost",v)}/><Cost label="تكلفة خدمة الحقائب" value={profit.settings.baggage_cost||0} onSave={v=>saveCost("baggage_cost",v)}/></Card></div>}
  </div>
  {invoice&&<Modal onClose={()=>setInvoice(null)}><div className="flex items-start justify-between gap-4"><button onClick={()=>setInvoice(null)} className="grid size-9 place-items-center rounded-lg bg-slate-100"><X className="size-4"/></button><div className="text-right"><div className="text-[10px] text-slate-400">فاتورة شركة</div><h2 className="mt-1 text-2xl font-black">{invoice.invoice.invoice_number}</h2><div className="mt-1 text-xs text-slate-500">{invoice.invoice.company_name}</div></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="الإجمالي" value={money(invoice.invoice.subtotal_iqd)}/><Mini label="المدفوع" value={money(invoice.paidIqd)}/><Mini label="المتبقي" value={money(invoice.balanceIqd)}/><Mini label="الحالة" value={status[invoice.invoice.status]||invoice.invoice.status}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead><tr className="border-y bg-slate-50"><th className="p-2">الطلب</th><th>التاريخ</th><th>الكابتن</th><th>الصالة</th><th>المسافرون</th><th>سعر الشخص</th><th>الإجمالي</th></tr></thead><tbody>{invoice.items.map(i=><tr key={i.id} className="border-b"><td className="p-2 font-mono">{i.order_reference}</td><td>{day(i.service_date)}</td><td>{i.captain_name}</td><td>{i.lounge_name}</td><td>{i.passengers}</td><td>{money(i.unit_price_iqd)}</td><td>{money(i.line_total_iqd)}</td></tr>)}</tbody></table></div>{invoice.invoice.status!=="void"&&invoice.balanceIqd>0&&<form onSubmit={addPayment} className="mt-5 grid gap-2 sm:grid-cols-[1fr_1.5fr_auto]"><input className="field" required inputMode="numeric" placeholder="مبلغ الدفعة" value={payment.amountIqd} onChange={e=>setPayment({...payment,amountIqd:e.target.value})}/><input className="field" placeholder="ملاحظة" value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/><button className="rounded-xl bg-emerald-700 px-4 py-3 text-xs font-bold text-white">تسجيل دفعة</button></form>}<div className="mt-5 flex gap-2"><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-xl bg-[#123f58] px-4 py-3 text-xs font-bold text-white"><Printer className="size-4"/>طباعة / PDF</button>{invoice.invoice.status!=="void"&&invoice.payments.length===0&&<button onClick={voidInv} className="rounded-xl bg-red-50 px-4 py-3 text-xs font-bold text-red-700">إلغاء الفاتورة</button>}</div></Modal>}
  {customer&&<Modal onClose={()=>setCustomer(null)}><div className="flex items-start justify-between"><button onClick={()=>setCustomer(null)} className="grid size-9 place-items-center rounded-lg bg-slate-100"><X className="size-4"/></button><div className="text-right"><div className="text-[10px] text-slate-400">CUSTOMER 360</div><h2 className="mt-1 text-2xl font-black">{customer.name}</h2><div dir="ltr" className="mt-1 text-xs text-slate-500">{customer.phone}</div></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="الحجوزات" value={customer.metrics.bookings}/><Mini label="إجمالي الصرف" value={money(customer.metrics.spend)}/><Mini label="متوسط الحجز" value={money(customer.metrics.average)}/><Mini label="الملغي" value={customer.metrics.cancelled}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-right text-xs"><thead><tr className="border-y bg-slate-50"><th className="p-2">المرجع</th><th>الرحلة</th><th>المسافرون</th><th>الدفع</th><th>المبلغ</th><th>التاريخ</th></tr></thead><tbody>{customer.orders.map((o:any)=><tr key={o.reference} className="border-b"><td className="p-2 font-mono">{o.reference}</td><td>{o.flight_number}</td><td>{o.passengers}</td><td>{o.payment_method}</td><td>{money(o.total_iqd)}</td><td>{day(o.created_at)}</td></tr>)}</tbody></table></div></Modal>}
 </main>
}
function Card({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm lg:p-6"><h2 className="font-black">{title}</h2><p className="mt-1 text-[10px] text-slate-400">{sub}</p><div className="mt-5">{children}</div></section>}
function Kpi({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="rounded-[22px] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#edf4f6] text-[#286b82]">{icon}</div><div><div className="text-[10px] text-slate-400">{label}</div><div className="mt-1 text-lg font-black">{value}</div></div></div></div>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] text-slate-400">{label}</div><div className="mt-1 break-words font-bold">{value}</div></div>}
function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/55 p-3 backdrop-blur-sm"><div className="mx-auto my-6 max-w-5xl rounded-[26px] bg-white p-5 shadow-2xl lg:p-8">{children}</div></div>}
function Cost({label,value,onSave}:{label:string;value:number;onSave:(v:number)=>void}){const [v,setV]=useState(String(value));useEffect(()=>setV(String(value)),[value]);return <div className="mb-3 rounded-xl border p-3"><div className="text-[10px] text-slate-400">{label}</div><div className="mt-2 flex gap-2"><input className="field" inputMode="numeric" value={v} onChange={e=>setV(e.target.value)}/><button onClick={()=>onSave(Math.max(0,Math.round(Number(v)||0)))} className="rounded-lg bg-[#123f58] px-3 text-xs font-bold text-white">حفظ</button></div></div>}
