"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import OwnerDashboard from "@/components/owner-dashboard";

type Employee={id:number;name:string;username:string;role:string;assignedShift:string;loungeName:string;permissions:string[];active:boolean};
type Sync={pending:number;failed:number;synced:number;last_synced_at?:string|null};
const roles:Record<string,string>={owner:"مالك",manager:"مدير",reception:"موظف استقبال",supervisor:"مسؤول شفت",accountant:"محاسب"};
const loungeNames=["لاونج بغداد","عراق لاونج"];

export default function OpsAdminPage(){
  const [view,setView]=useState<"dashboard"|"employees"|"search"|"sync"|"audit">("dashboard");
  const [data,setData]=useState<any>({summary:{},activity:[],lounges:[],sync:{}});
  const [employees,setEmployees]=useState<Employee[]>([]);
  const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
  const [form,setForm]=useState({name:"",username:"",password:"",role:"reception",assignedShift:"الصباحي",loungeName:"لاونج بغداد"});
  const [filter,setFilter]=useState("الكل");const [query,setQuery]=useState("");const [results,setResults]=useState<any[]>([]);
  const [syncData,setSyncData]=useState<{sync:Sync,pending:any[]}>({sync:{pending:0,failed:0,synced:0},pending:[]});const [audit,setAudit]=useState<any[]>([]);
  const api=async(url:string,init?:RequestInit)=>{const r=await fetch(url,{cache:"no-store",...init});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||"تعذر تنفيذ الطلب");return j};
  const loadDashboard=useCallback(async()=>{try{setData(await api("/api/ops/admin"));setLoading(false)}catch(e:any){setMessage(e.message);setLoading(false)}},[]);
  const loadEmployees=useCallback(async()=>{try{const j=await api("/api/ops/admin?action=employees");setEmployees(j.employees||[])}catch{}},[]);
  const loadSync=useCallback(async()=>{try{setSyncData(await api("/api/ops/admin?action=sync"))}catch(e:any){setMessage(e.message)}},[]);
  const loadAudit=useCallback(async()=>{try{const j=await api("/api/ops/admin?action=audit");setAudit(j.audit||[])}catch(e:any){setMessage(e.message)}},[]);
  useEffect(()=>{loadDashboard();loadEmployees();const t=setInterval(loadDashboard,5000);return()=>clearInterval(t)},[loadDashboard,loadEmployees]);
  useEffect(()=>{if(view==="sync")loadSync();if(view==="audit")loadAudit()},[view,loadSync,loadAudit]);
  const filtered=useMemo(()=>filter==="الكل"?employees:employees.filter(e=>e.loungeName===filter),[employees,filter]);
  async function addEmployee(e:React.FormEvent){e.preventDefault();try{await api("/api/ops/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setForm({name:"",username:"",password:"",role:"reception",assignedShift:"الصباحي",loungeName:"لاونج بغداد"});setMessage("تمت إضافة الموظف");await loadEmployees();await loadDashboard()}catch(e:any){setMessage(e.message)}}
  async function patch(emp:Employee,p:Record<string,unknown>){try{await api("/api/ops/admin",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:emp.id,...p})});setMessage("تم حفظ التعديل");await loadEmployees();await loadDashboard()}catch(e:any){setMessage(e.message)}}
  async function search(e?:React.FormEvent){e?.preventDefault();if(!query.trim())return setResults([]);try{const j=await api(`/api/ops/admin?action=search&q=${encodeURIComponent(query)}`);setResults(j.results||[])}catch(e:any){setMessage(e.message)}}
  async function retry(id?:number){try{await api("/api/ops/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(id?{action:"retrySync",entryId:id}:{action:"retryAllSync"})});setMessage("تمت محاولة المزامنة");await loadSync();await loadDashboard()}catch(e:any){setMessage(e.message)}}
  return <main dir="rtl" style={shell}><div style={{maxWidth:1450,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,flexWrap:"wrap",marginBottom:18}}><div><div style={brand}>BAGHDAD LOUNGE OPERATIONS SYSTEM</div><h1 style={{margin:"6px 0",fontSize:"clamp(25px,4vw,36px)"}}>مركز قيادة الصالات</h1><div style={muted}>صورة مباشرة للصالتين مع أدوات التشغيل والإدارة</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a href="/ops" style={{...btn(false),textDecoration:"none"}}>واجهة الموظف</a><a href="/api/ops/export" style={{...btn(false),textDecoration:"none"}}>تصدير Excel</a></div></header>
    <nav style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:10,marginBottom:10}}>{[["dashboard","نظرة المالك"],["employees","الموظفين والصلاحيات"],["search","البحث"],["sync","Google Sheet"],["audit","سجل التدقيق"]].map(([k,l])=><button key={k} onClick={()=>setView(k as any)} style={{...btn(view===k),whiteSpace:"nowrap"}}>{l}</button>)}<a href="/ops/admin/airlines" style={{...btn(false),whiteSpace:"nowrap",textDecoration:"none"}}>شركات الطيران</a><a href="/ops/admin/settings" style={{...btn(false),whiteSpace:"nowrap",textDecoration:"none"}}>إعدادات الأسعار</a></nav>
    {message&&<div style={{...card,borderColor:"#8a6f3e",marginBottom:14}}>{message}</div>}
    {view==="dashboard"&&<OwnerDashboard data={data}/>} 
    {view==="employees"&&<section style={{display:"grid",gridTemplateColumns:"minmax(290px,390px) 1fr",gap:14,alignItems:"start"}}><form onSubmit={addEmployee} style={card}><SectionTitle title="إضافة موظف" sub="حدد الصالة والشفت والصلاحية"/><Field label="الاسم"><input required style={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="اسم المستخدم"><input required style={input} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Field><Field label="كلمة المرور"><input required minLength={6} type="password" style={input} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field><Field label="الصالة"><select style={input} value={form.loungeName} onChange={e=>setForm({...form,loungeName:e.target.value})}>{loungeNames.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="الشفت"><select style={input} value={form.assignedShift} onChange={e=>setForm({...form,assignedShift:e.target.value})}>{["الصباحي","المسائي","الليلي"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="الصلاحية"><select style={input} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roles).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><button style={{...btn(true),width:"100%"}}>إضافة الموظف</button></form><div style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><SectionTitle title="الموظفين والصلاحيات" sub={`${filtered.length} موظف`}/><select style={{...input,width:180}} value={filter} onChange={e=>setFilter(e.target.value)}><option>الكل</option>{loungeNames.map(x=><option key={x}>{x}</option>)}</select></div><div style={{display:"grid",gap:10}}>{filtered.map(emp=><div key={emp.id} style={{border:"1px solid #26354a",borderRadius:14,padding:13,background:"#0a1423"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><b style={{fontSize:17}}>{emp.name}</b><div style={muted}>@{emp.username}</div></div><button onClick={()=>patch(emp,{active:!emp.active})} style={btn(emp.active)}>{emp.active?"نشط":"موقوف"}</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8,marginTop:12}}><select style={input} value={emp.loungeName} onChange={e=>patch(emp,{loungeName:e.target.value})}>{loungeNames.map(x=><option key={x}>{x}</option>)}</select><select style={input} value={emp.assignedShift} onChange={e=>patch(emp,{assignedShift:e.target.value})}>{["الصباحي","المسائي","الليلي"].map(x=><option key={x}>{x}</option>)}</select><select style={input} value={emp.role} onChange={e=>patch(emp,{role:e.target.value})}>{Object.entries(roles).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div></div>)}</div></div></section>}
    {view==="search"&&<section style={card}><SectionTitle title="بحث العمليات" sub="رقم العملية، اسم المسافر، الرحلة، شركة الطيران أو الشركة"/><form onSubmit={search} style={{display:"flex",gap:8,marginBottom:14}}><input style={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="اكتب كلمة البحث"/><button style={btn(true)}>بحث</button></form><Table headers={["العملية","الصالة","المسافر","الطيران","الرحلة","من","إلى","المبلغ","الموظف","الشفت","المزامنة","التاريخ"]} rows={results.map(r=>[r.reference,r.lounge_name,r.passenger_name,r.airline||"—",r.flight_number||"—",r.origin||"—",r.destination||"—",money(r.amount_iqd),r.employee_name,r.shift_name,syncLabel(r.sheet_sync_status),new Date(r.created_at).toLocaleString("ar-IQ")])}/></section>}
    {view==="sync"&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><SectionTitle title="Google Sheet Sync" sub="أي فشل لا يحذف العملية من قاعدة البيانات"/><button onClick={()=>retry()} style={btn(true)}>إعادة مزامنة الكل</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:9,marginBottom:14}}><Metric t="تمت المزامنة" v={syncData.sync.synced||0}/><Metric t="معلّق" v={syncData.sync.pending||0}/><Metric t="فشل" v={syncData.sync.failed||0}/><Metric t="آخر مزامنة" v={syncData.sync.last_synced_at?new Date(syncData.sync.last_synced_at).toLocaleTimeString("ar-IQ"):"—"}/></div><div style={{display:"grid",gap:8}}>{syncData.pending.length?syncData.pending.map(r=><div key={r.id} style={{border:"1px solid #334155",borderRadius:12,padding:12,display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><b>{r.reference} · {r.passenger_name}</b><div style={muted}>{r.lounge_name} · {r.shift_name} · {r.sheet_sync_status}{r.sheet_sync_error?` · ${r.sheet_sync_error}`:""}</div></div><button onClick={()=>retry(Number(r.id))} style={btn(false)}>إعادة المحاولة</button></div>):<div style={muted}>ماكو عمليات معلقة.</div>}</div></section>}
    {view==="audit"&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><SectionTitle title="سجل التدقيق" sub="كل إنشاء أو تعديل أو فتح/إغلاق شفت يبقى مسجل"/><button onClick={loadAudit} style={btn(false)}>تحديث</button></div><Table headers={["الوقت","المستخدم","الإجراء","النوع","الرقم","الملاحظة"]} rows={audit.map(a=>[new Date(a.created_at).toLocaleString("ar-IQ"),a.actor_name||"النظام",a.action,a.entity_type,a.entity_id||"—",a.note||"—"])}/></section>}
    {loading&&<div style={{...card,marginTop:10}}>جاري تحميل النظام...</div>}
  </div></main>
}
function SectionTitle({title,sub}:{title:string;sub:string}){return <div style={{marginBottom:13}}><h2 style={{margin:0,fontSize:20}}>{title}</h2><div style={{...muted,marginTop:4}}>{sub}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"grid",gap:6,marginBottom:10}}><span style={{fontSize:13,fontWeight:800,color:"#cbd5e1"}}>{label}</span>{children}</label>}
function Metric({t,v}:{t:string;v:any}){return <div style={{...card,padding:12}}><div style={eyebrow}>{t}</div><div style={{fontSize:21,fontWeight:950,marginTop:6}}>{v}</div></div>}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{headers.map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={td}>{String(c??"—")}</td>)}</tr>):<tr><td colSpan={headers.length} style={{...td,textAlign:"center",color:"#94a3b8"}}>لا توجد بيانات</td></tr>}</tbody></table></div>}
const money=(v:any)=>`${Number(v||0).toLocaleString("en-US")} د.ع`;const syncLabel=(s?:string)=>s==="synced"?"تم":s==="failed"?"فشل":s==="pending"?"معلق":"—";
const shell:React.CSSProperties={minHeight:"100vh",background:"linear-gradient(180deg,#06101d,#081526)",color:"#f8fafc",padding:16,fontFamily:"Arial,sans-serif"};const card:React.CSSProperties={background:"#0d1829",border:"1px solid #1f2d42",borderRadius:16,padding:15};const brand:React.CSSProperties={color:"#c8a66a",fontWeight:900,fontSize:13,letterSpacing:.3};const muted:React.CSSProperties={color:"#94a3b8",fontSize:13};const eyebrow:React.CSSProperties={color:"#94a3b8",fontSize:11,fontWeight:800};const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#07111f",color:"#f8fafc",border:"1px solid #334155",borderRadius:10,padding:"10px 11px",fontSize:15};
function btn(active:boolean):React.CSSProperties{return{border:active?"1px solid #c8a66a":"1px solid #334155",background:active?"#c8a66a":"#111d30",color:active?"#07111f":"#e2e8f0",borderRadius:10,padding:"9px 12px",fontWeight:850,cursor:"pointer"}}
const th:React.CSSProperties={textAlign:"right",padding:"10px 8px",fontSize:12,color:"#94a3b8",borderBottom:"1px solid #334155",whiteSpace:"nowrap"};const td:React.CSSProperties={padding:"10px 8px",borderBottom:"1px solid #1d2a3c",fontSize:13,whiteSpace:"nowrap"};