"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Armchair, BadgePercent, BarChart3, BellRing, Building2, Check, ChevronLeft,
  CircleDollarSign, Copy, CreditCard, Download, Edit3, Eye, Filter, Headphones, History, Home,
  LayoutDashboard, Loader2, LogOut, Menu, Minus, Plane, Plus, Power, RefreshCw, Save, Search,
  Settings, ShieldCheck, TicketCheck, Trash2, UserPlus, UserRound, UsersRound, Wallet, X
} from "lucide-react";

type View="dashboard"|"orders"|"operations"|"captains"|"companies"|"promos"|"lounges"|"finance"|"reports"|"activity"|"settings";
type Priority="normal"|"important"|"urgent";
type Booking={id:number;reference:string;customer_name:string;phone:string;flight_number:string;passengers:number;bags:number;total_iqd:number;promo_code:string|null;status:string;created_at:string;source:"customer"|"captain";company:string|null;lounge:string|null;carts:number|null;priority:Priority;internal_note:string;archived_at:string|null};
type Captain={id:number;username:string;name:string;company:string;phone:string;active:boolean};
type Promo={id:number;company_name:string;code:string;discount_percent:number;starts_at:string|null;expires_at:string|null;max_uses:number|null;uses_count:number;active:boolean;created_at:string};
type Overview={stats:{bookings_today:number;new_bookings:number;passengers_today:number;revenue_today:number};captains:{total:number;active:number};promos:{total:number;active:number;uses:number};recent:Booking[];companies:{name:string;captains:number;promos:number;promo_uses:number}[]};
type ActivityRow={id:number;reference:string;action:string;new_value:string|null;actor:string;created_at:string};
type Lounge={id:string;name:string;active:boolean;price_iqd:number;note:string;sort_order:number};
type Ops={lounges:Lounge[];messages:{id:number;text:string;active:boolean;created_at:string}[];watchlist:{id:number;kind:string;value:string;note:string;active:boolean;created_at:string}[];companies:{name:string;price_per_passenger:number;notes:string;orders:number;passengers:number;paid_iqd:number;due_iqd:number}[];monitor:{new_orders:number;delayed_orders:number;oldest_new:string|null;busiest_lounge:string|null;active_company:string|null}};

const statusMap:Record<string,string>={new:"جديد",received:"تم الاستلام",in_progress:"قيد التنفيذ",completed:"مكتمل",cancelled:"ملغي"};
const priorityMap:Record<Priority,string>={normal:"عادي",important:"مهم",urgent:"عاجل"};
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(Number(n||0))+" د.ع";
const dt=(v:string)=>new Intl.DateTimeFormat("ar-IQ",{timeZone:"Asia/Baghdad",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const age=(v:string)=>{const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));return m<60?`${m} د`:m<1440?`${Math.floor(m/60)} س`:`${Math.floor(m/1440)} يوم`};
const dateInput=(v:string|null)=>{if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};

const nav:[string,{id:View;label:string;icon:any}[]][]=[
  ["مركز التحكم",[{id:"dashboard",label:"نظرة عامة",icon:LayoutDashboard},{id:"orders",label:"إدارة الطلبات",icon:TicketCheck},{id:"operations",label:"مراقبة التشغيل",icon:Activity}]],
  ["الشركاء والخدمات",[{id:"captains",label:"الكباتن",icon:UsersRound},{id:"companies",label:"الشركات",icon:Building2},{id:"promos",label:"الخصومات",icon:BadgePercent},{id:"lounges",label:"الصالات",icon:Armchair}]],
  ["الإدارة",[{id:"finance",label:"الحسابات المالية",icon:Wallet},{id:"reports",label:"التقارير",icon:BarChart3},{id:"activity",label:"سجل النشاط",icon:History},{id:"settings",label:"الإعدادات",icon:Settings}]],
];

export default function Admin(){
  const [token,setToken]=useState("");const [login,setLogin]=useState({username:"",password:""});const [view,setView]=useState<View>("dashboard");
  const [overview,setOverview]=useState<Overview|null>(null);const [bookings,setBookings]=useState<Booking[]>([]);const [captains,setCaptains]=useState<Captain[]>([]);const [promos,setPromos]=useState<Promo[]>([]);const [ops,setOps]=useState<Ops|null>(null);const [activity,setActivity]=useState<ActivityRow[]>([]);
  const [selected,setSelected]=useState<Booking|null>(null);const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");const [mobile,setMobile]=useState(false);const [search,setSearch]=useState("");const [status,setStatus]=useState("all");const [source,setSource]=useState("all");
  const [captainModal,setCaptainModal]=useState(false);const [editCaptain,setEditCaptain]=useState<Captain|null>(null);const [captainForm,setCaptainForm]=useState({name:"",company:"",phone:"",username:"",password:""});const [newPassword,setNewPassword]=useState("");
  const [promoModal,setPromoModal]=useState(false);const [editPromo,setEditPromo]=useState<Promo|null>(null);const [promoForm,setPromoForm]=useState({companyName:"",code:"",discountPercent:10,maxUses:"",startsAt:"",expiresAt:""});
  const [newMessage,setNewMessage]=useState("");const [watch,setWatch]=useState({kind:"phone",value:"",note:""});const [payment,setPayment]=useState({companyName:"",amountIqd:"",note:""});

  useEffect(()=>{const t=sessionStorage.getItem("mainAdminToken")||"";if(t){setToken(t);void load(t)}},[]);
  useEffect(()=>{if(!token)return;const i=setInterval(()=>void load(token,true),15000);return()=>clearInterval(i)},[token]);
  async function api(path:string,opt:RequestInit={},t=token){return fetch(path,{...opt,headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}})}
  async function load(t=token,silent=false){if(!silent)setLoading(true);try{const rs=await Promise.all([api("/api/admin/overview",{},t),api("/api/admin/bookings",{},t),api("/api/admin/operations",{},t),api("/api/admin/activity",{},t),api("/api/captain/admin/captains",{},t),api("/api/prmos/promos",{},t)]);if(rs.some(r=>r.status===401)){logout();return}const [a,b,c,d,e,f]=await Promise.all(rs.map(r=>r.json()));if(!rs[0].ok)throw new Error(a.message||"تعذر تحميل لوحة الإدارة");setOverview(a);setBookings(b.bookings||[]);setOps(c);setActivity(d.activity||[]);setCaptains(e.captains||[]);setPromos(f.promos||[])}catch(e){if(!silent)setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{if(!silent)setLoading(false)}}
  async function doLogin(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const r=await api("/api/captain/admin/login",{method:"POST",body:JSON.stringify(login)},"");const x=await r.json();if(!r.ok){setMessage(x.message||"بيانات الدخول غير صحيحة");return}setToken(x.token);sessionStorage.setItem("mainAdminToken",x.token);await load(x.token)}finally{setLoading(false)}}
  function logout(){setToken("");sessionStorage.removeItem("mainAdminToken")}
  async function orderPatch(id:number,p:Record<string,unknown>){const r=await api("/api/admin/bookings",{method:"PATCH",body:JSON.stringify({id,...p})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر تحديث الطلب");return}await load(token,true);setSelected(v=>v?.id===id?{...v,...("status" in p?{status:String(p.status)}:{}),...("priority" in p?{priority:p.priority as Priority}:{}),...("internalNote" in p?{internal_note:String(p.internalNote)}:{})}:v)}
  async function op(method:"POST"|"PATCH"|"DELETE",body?:Record<string,unknown>,q=""){const r=await api(`/api/admin/operations${q}`,{method,body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر تنفيذ الإجراء");return false}await load(token,true);return true}
  async function createCaptain(e:FormEvent){e.preventDefault();const r=await api("/api/captain/admin/captains",{method:"POST",body:JSON.stringify(captainForm)});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر إنشاء الحساب");return}setCaptainForm({name:"",company:"",phone:"",username:"",password:""});setCaptainModal(false);await load(token,true)}
  async function saveCaptain(e:FormEvent){e.preventDefault();if(!editCaptain)return;const r=await api("/api/captain/admin/captains",{method:"PATCH",body:JSON.stringify({...editCaptain,password:newPassword})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر حفظ الحساب");return}setEditCaptain(null);setNewPassword("");await load(token,true)}
  async function toggleCaptain(c:Captain){const r=await api("/api/captain/admin/captains",{method:"PATCH",body:JSON.stringify({...c,active:!c.active,password:""})});if(!r.ok){const x=await r.json();setMessage(x.message||"تعذر تغيير الحالة");return}await load(token,true)}
  async function removeCaptain(c:Captain){if(!confirm(`حذف ${c.name}؟`))return;await api(`/api/captain/admin/captains?id=${c.id}`,{method:"DELETE"});await load(token,true)}
  async function createPromo(e:FormEvent){e.preventDefault();const r=await api("/api/prmos/promos",{method:"POST",body:JSON.stringify({...promoForm,maxUses:promoForm.maxUses?Number(promoForm.maxUses):null})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر إنشاء الرمز");return}setPromoForm({companyName:"",code:"",discountPercent:10,maxUses:"",startsAt:"",expiresAt:""});setPromoModal(false);await load(token,true)}
  async function savePromo(e:FormEvent){e.preventDefault();if(!editPromo)return;const r=await api("/api/prmos/promos",{method:"PATCH",body:JSON.stringify({id:editPromo.id,companyName:editPromo.company_name,code:editPromo.code,discountPercent:editPromo.discount_percent,startsAt:dateInput(editPromo.starts_at),expiresAt:dateInput(editPromo.expires_at),maxUses:editPromo.max_uses,active:editPromo.active})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر حفظ الرمز");return}setEditPromo(null);await load(token,true)}
  async function togglePromo(p:Promo){await api("/api/prmos/promos",{method:"PATCH",body:JSON.stringify({id:p.id,companyName:p.company_name,code:p.code,discountPercent:p.discount_percent,startsAt:dateInput(p.starts_at),expiresAt:dateInput(p.expires_at),maxUses:p.max_uses,active:!p.active})});await load(token,true)}
  async function removePromo(p:Promo){if(!confirm(`حذف ${p.code}؟`))return;await api(`/api/prmos/promos?id=${p.id}`,{method:"DELETE"});await load(token,true)}

  const active=useMemo(()=>bookings.filter(b=>!b.archived_at),[bookings]);const delayed=active.filter(b=>b.status==="new"&&Date.now()-new Date(b.created_at).getTime()>15*60000);const filtered=bookings.filter(b=>{const q=search.toLowerCase();return(!q||[b.reference,b.customer_name,b.phone,b.company||"",b.lounge||""].join(" ").toLowerCase().includes(q))&&(status==="all"||b.status===status)&&(source==="all"||b.source===source)});
  const financeTotal=ops?.companies.reduce((s,c)=>s+Number(c.due_iqd||0),0)||0;const financePaid=ops?.companies.reduce((s,c)=>s+Number(c.paid_iqd||0),0)||0;
  const captainStats=useMemo(()=>captains.map(c=>{const rows=active.filter(b=>b.source==="captain"&&b.customer_name===c.name&&b.company===c.company);return{...c,orders:rows.length,passengers:rows.reduce((s,b)=>s+b.passengers,0)}}),[captains,active]);
  const loungeStats=useMemo(()=>{const m=new Map<string,{orders:number;passengers:number}>();active.forEach(b=>{if(!b.lounge)return;const x=m.get(b.lounge)||{orders:0,passengers:0};x.orders++;x.passengers+=b.passengers;m.set(b.lounge,x)});return m},[active]);
  function exportCsv(){const rows=[["reference","source","name","company","lounge","phone","passengers","status"],...filtered.map(b=>[b.reference,b.source,b.customer_name,b.company||"",b.lounge||"",b.phone,String(b.passengers),b.status])];const blob=new Blob(["\uFEFF"+rows.map(r=>r.map(x=>`"${x.replace(/"/g,'""')}"`).join(",")).join("\n")],{type:"text/csv"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="lounge-orders.csv";a.click();URL.revokeObjectURL(u)}

  if(!token)return <Login login={login} setLogin={setLogin} loading={loading} message={message} submit={doLogin}/>;
  const titles:Record<View,string>={dashboard:"لوحة القيادة",orders:"إدارة الطلبات",operations:"مركز العمليات",captains:"إدارة الكباتن",companies:"الشركات والشركاء",promos:"إدارة الخصومات",lounges:"إدارة الصالات",finance:"الحسابات المالية",reports:"التقارير والتحليلات",activity:"سجل النشاط",settings:"إعدادات النظام"};

  return <main dir="rtl" className="min-h-screen bg-[#f3f5f7] text-[#142f42]">
    <aside className="fixed inset-y-0 right-0 z-40 hidden w-[285px] flex-col bg-[#0b2837] text-white lg:flex"><Brand/><div className="flex-1 overflow-y-auto p-3">{nav.map(([g,items])=><div key={g} className="mb-5"><div className="px-3 py-2 text-[10px] font-bold text-white/30">{g}</div>{items.map(i=><NavButton key={i.id} active={view===i.id} label={i.label} icon={<i.icon/>} badge={i.id==="orders"?(overview?.stats.new_bookings||0):0} onClick={()=>setView(i.id)}/>)}</div>)}</div><div className="border-t border-white/10 p-4"><div className="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><button onClick={logout} className="grid size-9 place-items-center rounded-xl bg-white/5"><LogOut className="size-4"/></button><div className="flex-1 text-right"><div className="text-sm font-semibold">Administrator</div><div className="text-[9px] text-white/35">Full Access</div></div><div className="grid size-9 place-items-center rounded-xl bg-[#d6ad68] font-bold text-[#153b4f]">A</div></div></div></aside>
    <div className="lg:mr-[285px]"><header className="sticky top-0 z-30 flex h-[72px] items-center gap-3 border-b border-slate-200 bg-white/90 px-4 backdrop-blur lg:px-7"><button onClick={()=>setMobile(true)} className="icon lg:hidden"><Menu className="size-5"/></button><div className="flex-1 text-right"><div className="text-[9px] text-slate-400">Lounge Baghdad / Control Center</div><h1 className="mt-1 text-lg font-bold">{titles[view]}</h1></div><div className="relative hidden w-[270px] xl:block"><Search className="absolute right-3 top-3 size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-[#f8fafb] pr-10 pl-3 text-xs outline-none" placeholder="بحث سريع..."/></div><button onClick={()=>load()} className="icon"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/></button></header>
      <div className="p-4 pb-24 lg:p-7">{message&&<div className="mb-5 flex justify-between rounded-xl border border-red-100 bg-red-50 p-3 text-xs text-red-700"><button onClick={()=>setMessage("")}><X className="size-4"/></button>{message}</div>}
        {view==="dashboard"&&<Dashboard overview={overview} delayed={delayed} active={active} captains={captains} promos={promos} ops={ops} onView={setView} onOpen={setSelected}/>} 
        {view==="orders"&&<Orders rows={filtered} total={bookings.length} search={search} setSearch={setSearch} status={status} setStatus={setStatus} source={source} setSource={setSource} open={setSelected} patch={orderPatch} exportCsv={exportCsv}/>} 
        {view==="operations"&&<Operations ops={ops} delayed={delayed} newMessage={newMessage} setNewMessage={setNewMessage} watch={watch} setWatch={setWatch} op={op}/>} 
        {view==="captains"&&<Captains rows={captainStats} create={()=>setCaptainModal(true)} edit={setEditCaptain} toggle={toggleCaptain} remove={removeCaptain}/>} 
        {view==="companies"&&<Companies ops={ops} captains={captains} promos={promos} active={active} go={setView}/>} 
        {view==="promos"&&<Promos rows={promos} create={()=>setPromoModal(true)} edit={setEditPromo} toggle={togglePromo} remove={removePromo}/>} 
        {view==="lounges"&&<Lounges rows={ops?.lounges||[]} stats={loungeStats} op={op}/>} 
        {view==="finance"&&<Finance companies={ops?.companies||[]} total={financeTotal} paid={financePaid} payment={payment} setPayment={setPayment} op={op}/>} 
        {view==="reports"&&<Reports active={active} captains={captainStats} loungeStats={loungeStats}/>} 
        {view==="activity"&&<ActivityLog rows={activity}/>} 
        {view==="settings"&&<SettingsView/>}
      </div>
    </div>
    {mobile&&<div className="fixed inset-0 z-50 bg-black/40 lg:hidden" onClick={()=>setMobile(false)}><aside onClick={e=>e.stopPropagation()} className="absolute inset-y-0 right-0 w-[300px] overflow-y-auto bg-[#0b2837] p-3 text-white"><Brand/>{nav.flatMap(x=>x[1]).map(i=><NavButton key={i.id} active={view===i.id} label={i.label} icon={<i.icon/>} onClick={()=>{setView(i.id);setMobile(false)}}/>)}</aside></div>}
    <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t bg-white/95 px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden"><Bottom icon={<Home/>} label="الرئيسية" active={view==="dashboard"} onClick={()=>setView("dashboard")}/><Bottom icon={<TicketCheck/>} label="الطلبات" active={view==="orders"} onClick={()=>setView("orders")}/><Bottom icon={<Activity/>} label="التشغيل" active={view==="operations"} onClick={()=>setView("operations")}/><Bottom icon={<Wallet/>} label="الحسابات" active={view==="finance"} onClick={()=>setView("finance")}/><Bottom icon={<Menu/>} label="المزيد" active={false} onClick={()=>setMobile(true)}/></nav>
    {selected&&<OrderPanel b={selected} close={()=>setSelected(null)} patch={orderPatch}/>} 
    {captainModal&&<Modal title="إضافة كابتن" close={()=>setCaptainModal(false)}><CaptainForm form={captainForm} setForm={setCaptainForm} submit={createCaptain}/></Modal>}
    {editCaptain&&<Modal title="تعديل الكابتن" close={()=>setEditCaptain(null)}><EditCaptain c={editCaptain} setC={setEditCaptain} password={newPassword} setPassword={setNewPassword} submit={saveCaptain}/></Modal>}
    {promoModal&&<Modal title="إضافة رمز خصم" close={()=>setPromoModal(false)}><PromoForm form={promoForm} setForm={setPromoForm} submit={createPromo}/></Modal>}
    {editPromo&&<Modal title="تعديل رمز الخصم" close={()=>setEditPromo(null)}><EditPromo p={editPromo} setP={setEditPromo} submit={savePromo}/></Modal>}
  </main>
}

function Login({login,setLogin,loading,message,submit}:{login:{username:string;password:string};setLogin:(x:{username:string;password:string})=>void;loading:boolean;message:string;submit:(e:FormEvent)=>void}){return <main dir="rtl" className="min-h-screen bg-[#071f2b] text-white"><div className="grid min-h-screen lg:grid-cols-[1.1fr_.9fr]"><section className="hidden flex-col justify-between border-l border-white/10 p-12 lg:flex"><Brand large/><div><div className="text-xs font-bold tracking-[.18em] text-[#d6ad68]">ENTERPRISE CONTROL CENTER</div><h1 className="mt-5 text-5xl font-semibold leading-[1.18]">إدارة عميقة.<br/>رؤية أوضح.<br/><span className="text-[#d6ad68]">تشغيل أقوى.</span></h1><p className="mt-5 max-w-lg leading-8 text-white/45">كل طلبات الشركة وكباتنها وشركائها وصالاتها وحساباتها من شاشة واحدة.</p></div><div className="text-xs text-white/25">Lounge Baghdad Operations Platform</div></section><section className="flex items-center justify-center p-5"><div className="w-full max-w-md"><div className="mb-7 lg:hidden"><Brand large/></div><h2 className="text-3xl font-semibold">دخول الإدارة</h2><p className="mt-2 text-sm text-white/45">وصول آمن لمركز التحكم الكامل.</p><form onSubmit={submit} className="mt-7 rounded-[26px] border border-white/10 bg-white/5 p-6"><FieldDark label="اسم المستخدم" value={login.username} onChange={v=>setLogin({...login,username:v})}/><div className="mt-4"><FieldDark label="كلمة المرور" value={login.password} onChange={v=>setLogin({...login,password:v})} password/></div>{message&&<div className="mt-4 rounded-xl bg-red-500/10 p-3 text-center text-xs text-red-300">{message}</div>}<button disabled={loading} className="mt-6 flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#d6ad68] font-bold text-[#14394c]">{loading?<Loader2 className="size-5 animate-spin"/>:<ShieldCheck className="size-5"/>}دخول مركز الإدارة</button></form></div></section></div></main>}
function Dashboard({overview,delayed,active,captains,promos,ops,onView,onOpen}:{overview:Overview|null;delayed:Booking[];active:Booking[];captains:Captain[];promos:Promo[];ops:Ops|null;onView:(v:View)=>void;onOpen:(b:Booking)=>void}){return <div className="space-y-5"><Hero newCount={overview?.stats.new_bookings||0} delayed={delayed.length} active={active.length}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="طلبات اليوم" value={overview?.stats.bookings_today||0} sub={`${overview?.stats.new_bookings||0} جديد`} icon={<TicketCheck/>}/><Kpi label="المسافرون اليوم" value={overview?.stats.passengers_today||0} sub="كل المصادر" icon={<UsersRound/>}/><Kpi label="قيمة حجوزات الزبائن" value={money(overview?.stats.revenue_today||0)} sub="اليوم" icon={<CircleDollarSign/>} small/><Kpi label="طلبات متأخرة" value={delayed.length} sub="أكثر من 15 دقيقة" icon={<AlertTriangle/>} danger={delayed.length>0}/></div><div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><Card title="آخر حركة تشغيل" sub="أحدث الطلبات"><Table headers={["الطلب","المصدر","الاسم","المسافرون","الحالة","العمر",""]}>{(overview?.recent||[]).slice(0,7).map(b=><tr key={`${b.source}-${b.id}`} className="border-b last:border-0"><Cell mono>{b.reference}</Cell><Cell><Source s={b.source}/></Cell><Cell><b>{b.customer_name}</b><div className="text-[9px] text-slate-400">{b.company||b.lounge||b.flight_number||"—"}</div></Cell><Cell>{b.passengers}</Cell><Cell><Status s={b.status}/></Cell><Cell>{age(b.created_at)}</Cell><Cell><button className="icon" onClick={()=>onOpen(b)}><Eye className="size-4"/></button></Cell></tr>)}</Table></Card><div className="space-y-5"><Card title="حالة التشغيل" sub="قراءة مباشرة"><Health label="طلبات جديدة" value={ops?.monitor.new_orders||0}/><Health label="طلبات متأخرة" value={ops?.monitor.delayed_orders||0} danger/><Health label="أكثر صالة" value={ops?.monitor.busiest_lounge||"—"}/><Health label="أكثر شركة" value={ops?.monitor.active_company||"—"}/></Card><Card title="وصول سريع"><div className="grid grid-cols-2 gap-2"><Quick label="الكباتن" icon={<UsersRound/>} onClick={()=>onView("captains")}/><Quick label="الخصومات" icon={<BadgePercent/>} onClick={()=>onView("promos")}/><Quick label="الحسابات" icon={<Wallet/>} onClick={()=>onView("finance")}/><a href="/reception" className="quick"><Headphones className="size-4"/>الاستقبال</a></div></Card></div></div><div className="grid gap-3 md:grid-cols-3"><MiniStat label="الكباتن الفعالين" value={captains.filter(c=>c.active).length}/><MiniStat label="رموز الخصم الفعالة" value={promos.filter(p=>p.active).length}/><MiniStat label="الصالات المفتوحة" value={ops?.lounges.filter(l=>l.active).length||0}/></div></div>}
function Orders({rows,total,search,setSearch,status,setStatus,source,setSource,open,patch,exportCsv}:{rows:Booking[];total:number;search:string;setSearch:(v:string)=>void;status:string;setStatus:(v:string)=>void;source:string;setSource:(v:string)=>void;open:(b:Booking)=>void;patch:(id:number,p:Record<string,unknown>)=>void;exportCsv:()=>void}){return <div className="space-y-5"><Title title="إدارة الطلبات" sub="كل طلبات الزبائن والكباتن في مكان واحد" action={<button onClick={exportCsv} className="btn"><Download className="size-4"/>تصدير</button>}/><Card title="الطلبات" sub={`${rows.length} ظاهر من ${total}`}><div className="mb-4 grid gap-2 md:grid-cols-[1fr_180px_180px_auto]"><div className="relative"><Search className="absolute right-3 top-3 size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="field pr-10" placeholder="رقم الطلب، الاسم، الهاتف، الشركة..."/></div><Select value={status} set={setStatus} options={[...Object.entries(statusMap).map(([v,l])=>[v,l]),["all","كل الحالات"]]}/><Select value={source} set={setSource} options={[["all","كل المصادر"],["captain","الكباتن"],["customer","الزبائن"]]}/><span className="icon"><Filter className="size-4"/></span></div><Table headers={["الطلب","المصدر","الاسم","الشركة / الصالة","الهاتف","المسافرون","الأولوية","الحالة","الوقت",""]}>{rows.map(b=><tr key={`${b.source}-${b.id}`} className="border-b last:border-0 hover:bg-slate-50"><Cell mono>{b.reference}</Cell><Cell><Source s={b.source}/></Cell><Cell><b>{b.customer_name}</b></Cell><Cell>{b.company||b.lounge||"—"}</Cell><Cell><a href={`tel:${b.phone}`} dir="ltr" className="text-[#2a7188]">{b.phone}</a></Cell><Cell>{b.passengers}</Cell><Cell>{priorityMap[b.priority]||"عادي"}</Cell><Cell><Status s={b.status}/></Cell><Cell>{age(b.created_at)}</Cell><Cell><button className="icon" onClick={()=>open(b)}><Eye className="size-4"/></button></Cell></tr>)}</Table></Card></div>}
function Operations({ops,delayed,newMessage,setNewMessage,watch,setWatch,op}:{ops:Ops|null;delayed:Booking[];newMessage:string;setNewMessage:(v:string)=>void;watch:{kind:string;value:string;note:string};setWatch:(x:{kind:string;value:string;note:string})=>void;op:any}){return <div className="space-y-5"><Title title="مركز العمليات" sub="مراقبة حية ورسائل النظام وقائمة الحظر"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="طلبات جديدة" value={ops?.monitor.new_orders||0} sub="الآن" icon={<BellRing/>}/><Kpi label="متأخرة" value={delayed.length} sub="تحتاج متابعة" icon={<AlertTriangle/>} danger={delayed.length>0}/><Kpi label="الصالة الأنشط" value={ops?.monitor.busiest_lounge||"—"} sub="حسب الحركة" icon={<Armchair/>} small/><Kpi label="الشركة الأنشط" value={ops?.monitor.active_company||"—"} sub="آخر 24 ساعة" icon={<Building2/>} small/></div><div className="grid gap-5 xl:grid-cols-2"><Card title="رسائل الكباتن" sub="تظهر داخل بوابة الكابتن"><form onSubmit={async e=>{e.preventDefault();if(await op("POST",{action:"message",text:newMessage}))setNewMessage("")}} className="flex gap-2"><input className="field" value={newMessage} onChange={e=>setNewMessage(e.target.value)} placeholder="اكتب رسالة تشغيلية..."/><button className="btn-primary"><Plus className="size-4"/>نشر</button></form><div className="mt-4 space-y-2">{ops?.messages.map(m=><div key={m.id} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3"><button onClick={()=>op("DELETE",undefined,`?action=message&id=${m.id}`)} className="text-red-500"><Trash2 className="size-4"/></button><button onClick={()=>op("PATCH",{action:"message",id:m.id,active:!m.active})}><Power className={`size-4 ${m.active?"text-emerald-600":"text-slate-400"}`}/></button><div className="flex-1 text-right text-sm">{m.text}</div></div>)}</div></Card><Card title="الحظر والمراقبة" sub="رقم مسافر أو كابتن أو شركة"><form onSubmit={async e=>{e.preventDefault();if(await op("POST",{action:"watch",...watch}))setWatch({kind:"phone",value:"",note:""})}} className="grid gap-2 sm:grid-cols-3"><Select value={watch.kind} set={v=>setWatch({...watch,kind:v})} options={[["phone","رقم"],["captain","كابتن"],["company","شركة"]]}/><input className="field" value={watch.value} onChange={e=>setWatch({...watch,value:e.target.value})} placeholder="القيمة"/><input className="field" value={watch.note} onChange={e=>setWatch({...watch,note:e.target.value})} placeholder="السبب"/><button className="btn-primary sm:col-span-3"><Plus className="size-4"/>إضافة للقائمة</button></form><div className="mt-4 space-y-2">{ops?.watchlist.slice(0,8).map(w=><div key={w.id} className="flex items-center gap-2 rounded-xl border p-3"><button onClick={()=>op("DELETE",undefined,`?action=watch&id=${w.id}`)} className="text-red-500"><Trash2 className="size-4"/></button><div className="flex-1 text-right"><b className="text-xs">{w.value}</b><div className="text-[9px] text-slate-400">{w.note||w.kind}</div></div></div>)}</div></Card></div></div>}
function Captains({rows,create,edit,toggle,remove}:{rows:(Captain&{orders:number;passengers:number})[];create:()=>void;edit:(c:Captain)=>void;toggle:(c:Captain)=>void;remove:(c:Captain)=>void}){return <div className="space-y-5"><Title title="إدارة الكباتن" sub="إنشاء وتعديل وإيقاف الحسابات من نفس لوحة الأدمن" action={<button onClick={create} className="btn-primary"><UserPlus className="size-4"/>كابتن جديد</button>}/><Card title="دليل الكباتن" sub={`${rows.length} حساب`}><Table headers={["الكابتن","الشركة","اليوزر","الهاتف","الطلبات","المسافرون","الحالة","الإجراءات"]}>{rows.map(c=><tr key={c.id} className="border-b last:border-0"><Cell><b>{c.name}</b></Cell><Cell>{c.company||"—"}</Cell><Cell mono>@{c.username}</Cell><Cell>{c.phone||"—"}</Cell><Cell>{c.orders}</Cell><Cell>{c.passengers}</Cell><Cell><span className={c.active?"good":"muted"}>{c.active?"فعال":"موقوف"}</span></Cell><Cell><div className="flex gap-1"><button className="icon" onClick={()=>edit(c)}><Edit3 className="size-4"/></button><button className="icon" onClick={()=>toggle(c)}><Power className="size-4"/></button><button className="icon text-red-500" onClick={()=>remove(c)}><Trash2 className="size-4"/></button></div></Cell></tr>)}</Table></Card></div>}
function Companies({ops,captains,promos,active,go}:{ops:Ops|null;captains:Captain[];promos:Promo[];active:Booking[];go:(v:View)=>void}){const names=Array.from(new Set([...(ops?.companies.map(c=>c.name)||[]),...captains.map(c=>c.company),...promos.map(p=>p.company_name)].filter(Boolean))).sort();return <div className="space-y-5"><Title title="الشركات والشركاء" sub="ملف موحد لكل شركة وحركتها وحسابها"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{names.map(n=>{const a=ops?.companies.find(c=>c.name===n);const balance=Number(a?.due_iqd||0)-Number(a?.paid_iqd||0);return <div key={n} className="rounded-[22px] border bg-white p-5"><div className="flex items-center justify-end gap-3"><div className="text-right"><h3 className="font-bold">{n}</h3><p className="text-[9px] text-slate-400">Partner Company</p></div><div className="grid size-11 place-items-center rounded-2xl bg-[#10394e] text-white"><Building2 className="size-5"/></div></div><div className="mt-4 grid grid-cols-4 gap-2"><MiniStat label="كباتن" value={captains.filter(c=>c.company===n).length}/><MiniStat label="طلبات" value={active.filter(b=>b.company===n).length}/><MiniStat label="مسافرين" value={a?.passengers||0}/><MiniStat label="برومو" value={promos.filter(p=>p.company_name===n).length}/></div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><span className={balance>0?"font-bold text-red-600":"font-bold text-emerald-600"}>{money(balance)}</span><span className="float-left text-xs text-slate-400">المتبقي</span></div><div className="mt-3 flex gap-2"><button className="btn flex-1" onClick={()=>go("finance")}>الحساب</button><button className="btn flex-1" onClick={()=>go("captains")}>الكباتن</button></div></div>})}</div></div>}
function Promos({rows,create,edit,toggle,remove}:{rows:Promo[];create:()=>void;edit:(p:Promo)=>void;toggle:(p:Promo)=>void;remove:(p:Promo)=>void}){return <div className="space-y-5"><Title title="إدارة الخصومات" sub="كل رموز الشركات داخل نفس مركز الإدارة" action={<button onClick={create} className="btn-primary"><Plus className="size-4"/>رمز جديد</button>}/><Card title="رموز الخصم" sub={`${rows.length} رمز`}><Table headers={["الشركة","الرمز","الخصم","الاستخدام","الانتهاء","الحالة","الإجراءات"]}>{rows.map(p=><tr key={p.id} className="border-b last:border-0"><Cell><b>{p.company_name}</b></Cell><Cell><button onClick={()=>navigator.clipboard?.writeText(p.code)} className="inline-flex gap-1 rounded-lg bg-slate-100 px-2 py-1 font-mono text-xs"><Copy className="size-3"/>{p.code}</button></Cell><Cell><b>{p.discount_percent}%</b></Cell><Cell>{p.uses_count}{p.max_uses?` / ${p.max_uses}`:""}</Cell><Cell>{p.expires_at?dt(p.expires_at):"بدون"}</Cell><Cell><span className={p.active?"good":"muted"}>{p.active?"فعال":"موقوف"}</span></Cell><Cell><div className="flex gap-1"><button className="icon" onClick={()=>edit(p)}><Edit3 className="size-4"/></button><button className="icon" onClick={()=>toggle(p)}><Power className="size-4"/></button><button className="icon text-red-500" onClick={()=>remove(p)}><Trash2 className="size-4"/></button></div></Cell></tr>)}</Table></Card></div>}
function Lounges({rows,stats,op}:{rows:Lounge[];stats:Map<string,{orders:number;passengers:number}>;op:any}){return <div className="space-y-5"><Title title="إدارة الصالات" sub="الاسم والسعر والحالة تنعكس على التشغيل"/><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{rows.map(l=><LoungeCard key={l.id} lounge={l} stat={stats.get(l.name)} save={(x:Lounge)=>op("PATCH",{action:"lounge",id:x.id,name:x.name,active:x.active,priceIqd:x.price_iqd,note:x.note,sortOrder:x.sort_order})}/>)}</div></div>}
function LoungeCard({lounge,stat,save}:{lounge:Lounge;stat?:{orders:number;passengers:number};save:(l:Lounge)=>void}){const [x,setX]=useState(lounge);useEffect(()=>setX(lounge),[lounge]);return <div className="rounded-[22px] border bg-white p-5"><div className="flex items-center justify-between"><button onClick={()=>setX({...x,active:!x.active})} className={x.active?"good":"muted"}>{x.active?"مفتوحة":"متوقفة"}</button><div><b>{x.name}</b><div className="text-[9px] text-slate-400">{stat?.orders||0} طلب · {stat?.passengers||0} مسافر</div></div></div><input className="field mt-4" value={x.name} onChange={e=>setX({...x,name:e.target.value})}/><input className="field mt-2" dir="ltr" type="number" value={x.price_iqd} onChange={e=>setX({...x,price_iqd:Number(e.target.value)})}/><textarea className="field mt-2 min-h-20 py-2" value={x.note} onChange={e=>setX({...x,note:e.target.value})}/><button className="btn-primary mt-3 w-full" onClick={()=>save(x)}><Save className="size-4"/>حفظ</button></div>}
function Finance({companies,total,paid,payment,setPayment,op}:{companies:Ops["companies"];total:number;paid:number;payment:{companyName:string;amountIqd:string;note:string};setPayment:(x:{companyName:string;amountIqd:string;note:string})=>void;op:any}){return <div className="space-y-5"><Title title="الحسابات المالية" sub="المستحقات والمدفوعات وأرصدة الشركات"/><div className="grid gap-3 sm:grid-cols-3"><Kpi label="إجمالي المستحق" value={money(total)} sub="كل الشركات" icon={<Wallet/>} small/><Kpi label="المدفوع" value={money(paid)} sub="مسجل" icon={<CreditCard/>} small/><Kpi label="المتبقي" value={money(total-paid)} sub="قيد التحصيل" icon={<CircleDollarSign/>} small danger={total-paid>0}/></div><div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card title="حسابات الشركات"><Table headers={["الشركة","المسافرون","سعر الشخص","المستحق","المدفوع","المتبقي"]}>{companies.map(c=><tr key={c.name} className="border-b last:border-0"><Cell><b>{c.name}</b></Cell><Cell>{c.passengers}</Cell><Cell>{money(c.price_per_passenger)}</Cell><Cell>{money(c.due_iqd)}</Cell><Cell>{money(c.paid_iqd)}</Cell><Cell><b className={c.due_iqd-c.paid_iqd>0?"text-red-600":"text-emerald-600"}>{money(c.due_iqd-c.paid_iqd)}</b></Cell></tr>)}</Table></Card><Card title="تسجيل دفعة"><form onSubmit={async e=>{e.preventDefault();if(await op("POST",{action:"payment",companyName:payment.companyName,amountIqd:Number(payment.amountIqd),note:payment.note}))setPayment({companyName:"",amountIqd:"",note:""})}} className="space-y-3"><Select value={payment.companyName} set={v=>setPayment({...payment,companyName:v})} options={[["","اختر الشركة"],...companies.map(c=>[c.name,c.name])]}/><input className="field" dir="ltr" type="number" value={payment.amountIqd} onChange={e=>setPayment({...payment,amountIqd:e.target.value})} placeholder="المبلغ"/><textarea className="field min-h-20 py-2" value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})} placeholder="ملاحظة"/><button className="btn-primary w-full"><CreditCard className="size-4"/>تسجيل الدفعة</button></form></Card></div></div>}
function Reports({active,captains,loungeStats}:{active:Booking[];captains:(Captain&{orders:number;passengers:number})[];loungeStats:Map<string,{orders:number;passengers:number}>}){const hours=Array.from({length:24},(_,h)=>({h,count:active.filter(b=>Number(new Intl.DateTimeFormat("en",{timeZone:"Asia/Baghdad",hour:"2-digit",hourCycle:"h23"}).format(new Date(b.created_at)))===h).length}));const max=Math.max(1,...hours.map(x=>x.count));return <div className="space-y-5"><Title title="التقارير والتحليلات" sub="نشاط الكباتن والصالات وساعات الضغط"/><Card title="ساعات الضغط"><div dir="ltr" className="flex h-52 items-end gap-1">{hours.map(x=><div key={x.h} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-[#2a7188]" style={{height:Math.max(4,x.count/max*150)}}/><span className="text-[8px] text-slate-400">{x.h}</span></div>)}</div></Card><div className="grid gap-5 xl:grid-cols-2"><Rank title="أفضل الكباتن" rows={captains.sort((a,b)=>b.orders-a.orders).slice(0,10).map(c=>[c.name,`${c.orders} طلب · ${c.passengers} مسافر`])}/><Rank title="نشاط الصالات" rows={[...loungeStats.entries()].sort((a,b)=>b[1].passengers-a[1].passengers).map(([n,x])=>[n,`${x.orders} طلب · ${x.passengers} مسافر`])}/></div></div>}
function ActivityLog({rows}:{rows:ActivityRow[]}){return <div className="space-y-5"><Title title="سجل النشاط" sub="آخر التغييرات داخل النظام"/><Card title="Audit Log"><div>{rows.map(r=><div key={r.id} className="flex gap-3 border-b py-4 last:border-0"><div className="grid size-9 place-items-center rounded-full bg-slate-100 text-[#2a7188]"><History className="size-4"/></div><div className="flex-1 text-right"><div className="flex justify-between"><span className="text-[9px] text-slate-400">{dt(r.created_at)}</span><b>{r.reference}</b></div><p className="mt-1 text-xs text-slate-500">{r.action}{r.new_value?` — ${r.new_value}`:""}</p></div></div>)}</div></Card></div>}
function SettingsView(){return <div className="space-y-5"><Title title="إعدادات النظام" sub="بوابات النظام والوصول السريع"/><div className="grid gap-5 xl:grid-cols-2"><Card title="بوابات التشغيل"><Link href="/reception" icon={<Headphones/>} title="شاشة الاستقبال"/><Link href="/captain" icon={<UsersRound/>} title="بوابة الكباتن"/><Link href="/prmos" icon={<BadgePercent/>} title="لوحة الخصومات المستقلة"/></Card><Card title="حالة المنصة"><Health label="قاعدة البيانات" value="متصلة"/><Health label="التحديث التلقائي" value="كل 15 ثانية"/><Health label="واجهة الحاسوب" value="Desktop First"/><Health label="واجهة الهاتف" value="Responsive"/></Card></div></div>}
function OrderPanel({b,close,patch}:{b:Booking;close:()=>void;patch:(id:number,p:Record<string,unknown>)=>void}){const [note,setNote]=useState(b.internal_note||"");return <div className="fixed inset-0 z-50 bg-black/40" onClick={close}><aside onClick={e=>e.stopPropagation()} className="absolute inset-y-0 left-0 w-full max-w-[500px] overflow-y-auto bg-white p-5 shadow-2xl"><div className="flex justify-between"><button className="icon" onClick={close}><X className="size-4"/></button><div className="text-right"><div className="font-mono text-xs text-slate-400">{b.reference}</div><h2 className="mt-2 text-xl font-bold">{b.customer_name}</h2></div></div><div className="mt-5 grid grid-cols-2 gap-2"><Info l="الهاتف" v={b.phone}/><Info l="المسافرون" v={String(b.passengers)}/><Info l="الحقائب" v={String(b.bags)}/><Info l="الشركة" v={b.company||"—"}/><Info l="الصالة" v={b.lounge||"—"}/><Info l="الوقت" v={dt(b.created_at)}/></div><h3 className="mt-5 text-xs font-bold">الحالة</h3><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries(statusMap).map(([k,l])=><button key={k} onClick={()=>patch(b.id,{status:k})} className={`rounded-xl p-2 text-[10px] ${b.status===k?"bg-[#10394e] text-white":"bg-slate-100"}`}>{l}</button>)}</div><h3 className="mt-5 text-xs font-bold">الأولوية</h3><div className="mt-2 grid grid-cols-3 gap-2">{Object.entries(priorityMap).map(([k,l])=><button key={k} onClick={()=>patch(b.id,{priority:k})} className={`rounded-xl p-2 text-xs ${b.priority===k?"bg-[#10394e] text-white":"bg-slate-100"}`}>{l}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} className="field mt-5 min-h-28 py-2" placeholder="ملاحظة داخلية"/><button className="btn-primary mt-2" onClick={()=>patch(b.id,{internalNote:note})}><Save className="size-4"/>حفظ الملاحظة</button></aside></div>}

function CaptainForm({form,setForm,submit}:{form:any;setForm:(x:any)=>void;submit:(e:FormEvent)=>void}){return <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><F label="اسم الكابتن" value={form.name} set={(v)=>setForm({...form,name:v})}/><F label="الشركة" value={form.company} set={(v)=>setForm({...form,company:v})}/><F label="الهاتف" value={form.phone} set={(v)=>setForm({...form,phone:v})} ltr/><F label="اليوزر" value={form.username} set={(v)=>setForm({...form,username:v})} ltr/><F label="الباسورد" value={form.password} set={(v)=>setForm({...form,password:v})} ltr password wide/><button className="btn-primary sm:col-span-2"><Check className="size-4"/>إنشاء الحساب</button></form>}
function EditCaptain({c,setC,password,setPassword,submit}:{c:Captain;setC:(x:Captain)=>void;password:string;setPassword:(v:string)=>void;submit:(e:FormEvent)=>void}){return <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><F label="الاسم" value={c.name} set={v=>setC({...c,name:v})}/><F label="الشركة" value={c.company} set={v=>setC({...c,company:v})}/><F label="الهاتف" value={c.phone} set={v=>setC({...c,phone:v})} ltr/><F label="اليوزر" value={c.username} set={v=>setC({...c,username:v})} ltr/><F label="باسورد جديد — اختياري" value={password} set={setPassword} ltr password wide/><button className="btn-primary sm:col-span-2"><Save className="size-4"/>حفظ</button></form>}
function PromoForm({form,setForm,submit}:{form:any;setForm:(x:any)=>void;submit:(e:FormEvent)=>void}){return <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><F label="الشركة" value={form.companyName} set={v=>setForm({...form,companyName:v})}/><F label="الرمز" value={form.code} set={v=>setForm({...form,code:v.toUpperCase().replace(/\s/g,"")})} ltr/><Percent value={form.discountPercent} set={v=>setForm({...form,discountPercent:v})}/><F label="حد الاستخدام" value={form.maxUses} set={v=>setForm({...form,maxUses:v})} ltr/><F label="البداية" value={form.startsAt} set={v=>setForm({...form,startsAt:v})} ltr type="datetime-local"/><F label="الانتهاء" value={form.expiresAt} set={v=>setForm({...form,expiresAt:v})} ltr type="datetime-local"/><button className="btn-primary sm:col-span-2"><Check className="size-4"/>إنشاء الرمز</button></form>}
function EditPromo({p,setP,submit}:{p:Promo;setP:(x:Promo)=>void;submit:(e:FormEvent)=>void}){return <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><F label="الشركة" value={p.company_name} set={v=>setP({...p,company_name:v})}/><F label="الرمز" value={p.code} set={v=>setP({...p,code:v})} ltr/><Percent value={p.discount_percent} set={v=>setP({...p,discount_percent:v})}/><F label="حد الاستخدام" value={p.max_uses===null?"":String(p.max_uses)} set={v=>setP({...p,max_uses:v?Number(v):null})} ltr/><F label="البداية" value={dateInput(p.starts_at)} set={v=>setP({...p,starts_at:v||null})} ltr type="datetime-local"/><F label="الانتهاء" value={dateInput(p.expires_at)} set={v=>setP({...p,expires_at:v||null})} ltr type="datetime-local"/><button className="btn-primary sm:col-span-2"><Save className="size-4"/>حفظ</button></form>}

function Brand({large=false}:{large?:boolean}){return <div className={`flex items-center gap-3 ${large?"p-0":"border-b border-white/10 p-5"}`}><div className={`${large?"size-14":"size-11"} grid place-items-center rounded-2xl bg-[#d6ad68] text-[#14394c]`}><Plane className="size-6 -rotate-45"/></div><div><div className="text-[9px] tracking-[.18em] text-white/40">LOUNGE BAGHDAD</div><div className={`${large?"text-xl":"text-base"} mt-1 font-semibold`}>Enterprise Console</div></div></div>}
function NavButton({active,label,icon,badge=0,onClick}:{active:boolean;label:string;icon:ReactNode;badge?:number;onClick:()=>void}){return <button onClick={onClick} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${active?"bg-[#d6ad68] font-semibold text-[#14394c]":"text-white/60 hover:bg-white/5 hover:text-white"}`}><span className="relative [&>svg]:size-4">{icon}{badge>0&&<span className="absolute -left-3 -top-2 min-w-4 rounded-full bg-red-500 px-1 text-[8px] leading-4 text-white">{badge}</span>}</span><span className="flex-1 text-right">{label}</span>{active&&<ChevronLeft className="size-3"/>}</button>}
function Bottom({icon,label,active,onClick}:{icon:ReactNode;label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 text-[9px] ${active?"text-[#123f58]":"text-slate-400"}`}><span className="[&>svg]:size-4">{icon}</span>{label}</button>}
function Hero({newCount,delayed,active}:{newCount:number;delayed:number;active:number}){return <div className="rounded-[24px] bg-[#10394e] p-6 text-white shadow-xl"><div className="text-[10px] font-bold tracking-[.16em] text-[#d6ad68]">OPERATIONS OVERVIEW</div><h2 className="mt-3 text-2xl font-semibold lg:text-3xl">مركز الشركة تحت السيطرة</h2><p className="mt-2 text-sm text-white/50">{newCount} طلب جديد · {delayed} متأخر · {active} طلب محفوظ</p></div>}
function Title({title,sub,action}:{title:string;sub:string;action?:ReactNode}){return <div className="flex items-end justify-between gap-4"><div>{action}</div><div className="text-right"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-xs text-slate-400">{sub}</p></div></div>}
function Card({title,sub,children}:{title:string;sub?:string;children:ReactNode}){return <section className="rounded-[20px] border border-slate-200 bg-white shadow-sm"><div className="border-b px-5 py-4 text-right"><h3 className="font-bold">{title}</h3>{sub&&<p className="mt-1 text-[9px] text-slate-400">{sub}</p>}</div><div className="p-4 lg:p-5">{children}</div></section>}
function Kpi({label,value,sub,icon,danger=false,small=false}:{label:string;value:string|number;sub:string;icon:ReactNode;danger?:boolean;small?:boolean}){return <div className={`rounded-[20px] border bg-white p-4 ${danger?"border-red-100":"border-slate-200"}`}><div className="flex items-start justify-between"><div className={`grid size-10 place-items-center rounded-xl ${danger?"bg-red-50 text-red-600":"bg-[#eaf2f5] text-[#2a7188]"}`}>{icon}</div><div className="text-right"><div className="text-[9px] text-slate-400">{label}</div><div className={`mt-2 font-bold ${small?"text-lg":"text-2xl"}`}>{value}</div></div></div><div className="mt-3 border-t pt-2 text-left text-[9px] text-slate-400">{sub}</div></div>}
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right"><thead><tr className="border-y bg-slate-50 text-[9px] text-slate-400">{headers.map((h,i)=><th key={i} className="px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Cell({children,mono=false}:{children?:ReactNode;mono?:boolean}){return <td className={`px-3 py-3 text-xs ${mono?"font-mono":""}`}>{children}</td>}
function Source({s}:{s:string}){return <span className={`rounded-full px-2 py-1 text-[9px] ${s==="captain"?"bg-sky-50 text-sky-700":"bg-slate-100 text-slate-600"}`}>{s==="captain"?"كابتن":"زبون"}</span>}
function Status({s}:{s:string}){return <span className="rounded-full bg-slate-100 px-2 py-1 text-[9px]">{statusMap[s]||s}</span>}
function Health({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <div className="mb-2 flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className={danger&&Number(value)>0?"font-bold text-red-600":"font-bold"}>{value}</span><span className="text-xs text-slate-500">{label}</span></div>}
function Quick({label,icon,onClick}:{label:string;icon:ReactNode;onClick:()=>void}){return <button onClick={onClick} className="quick">{icon}{label}</button>}
function MiniStat({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3 text-center"><div className="font-bold">{value}</div><div className="mt-1 text-[8px] text-slate-400">{label}</div></div>}
function Rank({title,rows}:{title:string;rows:string[][]}){return <Card title={title}>{rows.map((r,i)=><div key={i} className="flex items-center gap-3 border-b py-3 last:border-0"><span className="grid size-8 place-items-center rounded-lg bg-slate-100 text-xs font-bold">{i+1}</span><div className="flex-1 text-right"><b className="text-sm">{r[0]}</b><div className="text-[9px] text-slate-400">{r[1]}</div></div></div>)}</Card>}
function Link({href,icon,title}:{href:string;icon:ReactNode;title:string}){return <a href={href} className="flex items-center justify-between border-b py-4 last:border-0"><ChevronLeft className="size-4 text-slate-300"/><div className="flex items-center gap-2"><b className="text-sm">{title}</b><span className="text-[#2a7188] [&>svg]:size-4">{icon}</span></div></a>}
function Info({l,v}:{l:string;v:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] text-slate-400">{l}</div><div className="mt-1 text-sm font-bold">{v}</div></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-4" onClick={close}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-t-[24px] bg-white p-5 sm:rounded-[24px]"><div className="mb-5 flex justify-between"><button className="icon" onClick={close}><X className="size-4"/></button><h2 className="text-xl font-bold">{title}</h2></div>{children}</div></div>}
function F({label,value,set,ltr=false,password=false,wide=false,type="text"}:{label:string;value:string;set:(v:string)=>void;ltr?:boolean;password?:boolean;wide?:boolean;type?:string}){return <label className={wide?"sm:col-span-2":""}><span className="text-[10px] text-slate-500">{label}</span><input className="field mt-1" dir={ltr?"ltr":"rtl"} type={password?"password":type} value={value} onChange={e=>set(e.target.value)} /></label>}
function Percent({value,set}:{value:number;set:(v:number)=>void}){return <label><span className="text-[10px] text-slate-500">نسبة الخصم</span><div className="mt-1 flex h-11 items-center rounded-xl border p-1"><button type="button" onClick={()=>set(Math.max(1,value-1))} className="icon"><Minus className="size-4"/></button><b className="flex-1 text-center">{value}%</b><button type="button" onClick={()=>set(Math.min(100,value+1))} className="icon bg-[#10394e] text-white"><Plus className="size-4"/></button></div></label>}
function Select({value,set,options}:{value:string;set:(v:string)=>void;options:string[][]}){return <select value={value} onChange={e=>set(e.target.value)} className="field">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function FieldDark({label,value,onChange,password=false}:{label:string;value:string;onChange:(v:string)=>void;password?:boolean}){return <label><span className="text-xs text-white/50">{label}</span><input dir="ltr" type={password?"password":"text"} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 h-14 w-full rounded-2xl border border-white/10 bg-black/10 px-4 text-left outline-none focus:border-[#d6ad68]"/></label>}
