import { adminSessionFromRequest, roleCan } from "@/lib/admin-auth";
import { captain360, company360, createTask, executiveDashboard, globalSearch, listCaptains360, listCompanies360, listTasks, maintenanceState, morningBrief, saveCompany360, setSetting, updateTask } from "@/lib/admin-control-db";
import { createApproval } from "@/lib/admin-security-db";

export const runtime="nodejs";export const dynamic="force-dynamic";
function auth(request:Request){const s=adminSessionFromRequest(request);if(!s)return {response:Response.json({message:"غير مصرح"},{status:401}),session:null};if(!["owner","manager"].includes(s.role))return {response:Response.json({message:"هذه الصفحة مخصصة للإدارة"},{status:403}),session:s};return {response:null,session:s}}

export async function GET(request:Request){const a=auth(request);if(a.response)return a.response;try{const u=new URL(request.url);const action=u.searchParams.get("action")||"dashboard";if(action==="dashboard")return Response.json({dashboard:await executiveDashboard(),brief:await morningBrief(),maintenance:await maintenanceState(),tasks:await listTasks()},{headers:{"Cache-Control":"no-store"}});if(action==="companies")return Response.json({companies:await listCompanies360()},{headers:{"Cache-Control":"no-store"}});if(action==="company")return Response.json({company:await company360(String(u.searchParams.get("name")||""))},{headers:{"Cache-Control":"no-store"}});if(action==="captains")return Response.json({captains:await listCaptains360()},{headers:{"Cache-Control":"no-store"}});if(action==="captain")return Response.json({captain:await captain360(Number(u.searchParams.get("id")||0))},{headers:{"Cache-Control":"no-store"}});if(action==="search")return Response.json({results:await globalSearch(String(u.searchParams.get("q")||""))},{headers:{"Cache-Control":"no-store"}});if(action==="tasks")return Response.json({tasks:await listTasks()},{headers:{"Cache-Control":"no-store"}});return Response.json({message:"إجراء غير معروف"},{status:400})}catch(error){console.error("Control GET",error);return Response.json({message:"تعذر تحميل مركز الإدارة"},{status:500})}}

export async function POST(request:Request){const a=auth(request);if(a.response)return a.response;try{const b=await request.json() as Record<string,unknown>;const action=String(b.action||"");const actor=a.session?.name||a.session?.username||"admin";if(action==="task"){const title=String(b.title||"").trim();if(title.length<2)return Response.json({message:"اكتب عنوان المهمة"},{status:400});return Response.json({task:await createTask({title,details:String(b.details||""),entityType:String(b.entityType||"general"),entityKey:String(b.entityKey||""),priority:String(b.priority||"normal"),dueAt:b.dueAt?String(b.dueAt):null,actor})},{status:201})}return Response.json({message:"إجراء غير معروف"},{status:400})}catch(error){console.error("Control POST",error);return Response.json({message:"تعذر تنفيذ الإجراء"},{status:500})}}

export async function PATCH(request:Request){const a=auth(request);if(a.response)return a.response;try{const b=await request.json() as Record<string,unknown>;const action=String(b.action||"");const actor=a.session?.name||a.session?.username||"admin";if(action==="task")return Response.json({task:await updateTask(Number(b.id),String(b.status||"done"))});if(action==="setting"){if(!roleCan(a.session!.role,"settings")&&a.session!.role!=="manager")return Response.json({message:"لا تملك صلاحية الإعدادات"},{status:403});return Response.json({setting:await setSetting(String(b.key||""),String(b.value??""))})}if(action==="company"){
  const companyName=String(b.companyName||"").trim();if(companyName.length<2)return Response.json({message:"اسم الشركة غير صحيح"},{status:400});
  const payload={companyName,status:String(b.status||"normal"),creditLimitIqd:Math.max(0,Math.round(Number(b.creditLimitIqd)||0)),billingCycle:String(b.billingCycle||"monthly"),contactName:String(b.contactName||""),contactPhone:String(b.contactPhone||""),tags:String(b.tags||""),notes:String(b.notes||""),pricePerPassenger:Math.max(0,Math.round(Number(b.pricePerPassenger)||0))};
  if(a.session!.role==='manager'){
    const current:any=await company360(companyName);const currentPrice=Number(current?.summary?.price_per_passenger||0),currentLimit=Number(current?.summary?.credit_limit_iqd||0);
    if(currentPrice!==payload.pricePerPassenger||currentLimit!==payload.creditLimitIqd){
      const approval=await createApproval({kind:'company_change',entityKey:companyName,title:`تغيير مالي لشركة ${companyName}`,payload,requestedBy:actor,requestedRole:a.session!.role});
      return Response.json({pendingApproval:true,approval,message:'تم إرسال تغيير السعر/الحد الائتماني لموافقة المالك'},{status:202});
    }
  }
  return Response.json({company:await saveCompany360({...payload,actor})})
}return Response.json({message:"إجراء غير معروف"},{status:400})}catch(error){console.error("Control PATCH",error);return Response.json({message:"تعذر حفظ التغيير"},{status:500})}}
