"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Bell, BellRing, CheckCircle2, Clock3, Headphones, Loader2, LogOut, Phone, RefreshCw, ShieldCheck, TicketCheck, UsersRound } from "lucide-react";

type Booking={id:number;reference:string;customer_name:string;phone:string;passengers:number;bags:number;carts:number|null;status:string;created_at:string;source:"customer"|"captain";company:string|null;lounge:string|null;priority:"normal"|"important"|"urgent";archived_at:string|null};
const statuses=[['new','جديد'],['received','تم الاستلام'],['in_progress','قيد التنفيذ'],['completed','مكتمل'],['cancelled','ملغي']] as const;
function mins(v:string){return Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000))}
function ago(v:string){const m=mins(v);return m<1?'الآن':m<60?`منذ ${m} د`:`منذ ${Math.floor(m/60)} س`}

export default function ReceptionPage(){
  const [token,setToken]=useState('');const [login,setLogin]=useState({username:'',password:''});const [items,setItems]=useState<Booking[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [sound,setSound]=useState(false);const prev=useRef(0);
  useEffect(()=>{const t=sessionStorage.getItem('receptionAdminToken')||'';if(t){setToken(t);void load(t)}},[]);
  useEffect(()=>{if(!token)return;const t=setInterval(()=>void load(token,true),10000);return()=>clearInterval(t)},[token]);
  async function api(path:string,opts:RequestInit={},t=token){return fetch(path,{...opts,headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{})}})}
  function beep(){try{const Ctx=window.AudioContext||(window as any).webkitAudioContext;const c=new Ctx();const o=c.createOscillator();const g=c.createGain();o.frequency.value=900;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.14)}catch{}}
  async function load(t=token,silent=false){if(!silent)setLoading(true);try{const r=await api('/api/admin/bookings',{},t);if(r.status===401){logout();return}const x=await r.json();if(!r.ok)throw new Error(x.message||'تعذر تحميل الطلبات');const active=(x.bookings||[]).filter((b:Booking)=>!b.archived_at);const n=active.filter((b:Booking)=>b.status==='new').length;if(silent&&sound&&n>prev.current)beep();prev.current=n;setItems(active)}catch(e){if(!silent)setError(e instanceof Error?e.message:'حدث خطأ')}finally{if(!silent)setLoading(false)}}
  async function signIn(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await api('/api/captain/admin/login',{method:'POST',body:JSON.stringify(login)},'');const x=await r.json();if(!r.ok){setError(x.message||'تعذر الدخول');return}setToken(x.token);sessionStorage.setItem('receptionAdminToken',x.token);await load(x.token)}finally{setLoading(false)}}
  async function status(id:number,s:string){const r=await api('/api/admin/bookings',{method:'PATCH',body:JSON.stringify({id,status:s})});if(r.ok)await load(token,true)}
  function logout(){setToken('');sessionStorage.removeItem('receptionAdminToken');setItems([])}
  const sorted=useMemo(()=>[...items].sort((a,b)=>{const p={urgent:0,important:1,normal:2};return (p[a.priority]??2)-(p[b.priority]??2)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime()}),[items]);
  const newCount=items.filter(x=>x.status==='new').length;const delayed=items.filter(x=>x.status==='new'&&mins(x.created_at)>=15).length;

  if(!token)return <main dir="rtl" className="min-h-screen bg-[#103e56] px-5 py-12 text-white"><div className="mx-auto max-w-sm"><div className="mb-8 text-center"><div className="mx-auto grid size-16 place-items-center rounded-[22px] bg-[#d8b06d] text-[#123f58]"><Headphones className="size-8"/></div><h1 className="mt-5 text-2xl font-semibold">مركز الاستقبال</h1><p className="mt-2 text-sm text-white/60">واجهة مبسطة لمتابعة الطلبات فقط</p></div><form onSubmit={signIn} className="rounded-[28px] bg-white p-5 text-slate-900"><label className="text-xs text-slate-500">اسم المستخدم</label><input value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} dir="ltr" className="mt-2 h-14 w-full rounded-2xl border bg-[#f7f9fa] px-4"/><label className="mt-4 block text-xs text-slate-500">كلمة المرور</label><input value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} type="password" dir="ltr" className="mt-2 h-14 w-full rounded-2xl border bg-[#f7f9fa] px-4"/>{error&&<p className="mt-3 text-center text-sm text-red-600">{error}</p>}<button className="mt-5 flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#123f58] font-semibold text-white">{loading?<Loader2 className="size-5 animate-spin"/>:<ShieldCheck className="size-5"/>}دخول</button></form></div></main>;

  return <main dir="rtl" className="min-h-screen bg-[#f3f6f7] text-[#173448]"><header className="sticky top-0 z-20 bg-[#103e56] text-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3"><div className="flex gap-2"><button onClick={logout} className="grid size-10 place-items-center rounded-full bg-white/10"><LogOut className="size-5"/></button><button onClick={()=>{setSound(!sound);if(!sound)beep()}} className={`grid size-10 place-items-center rounded-full ${sound?'bg-[#d8b06d] text-[#123f58]':'bg-white/10'}`}>{sound?<BellRing className="size-5"/>:<Bell className="size-5"/>}</button></div><div className="text-right"><p className="text-[9px] text-white/50">RECEPTION MODE</p><h1 className="text-lg font-semibold">مركز الاستقبال</h1></div></div></header><div className="mx-auto max-w-3xl space-y-4 px-4 py-5"><div className="grid grid-cols-3 gap-3"><Box label="جديد" value={newCount}/><Box label="متأخر" value={delayed}/><Box label="الطلبات الحالية" value={items.length}/></div><button onClick={()=>load()} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs"><RefreshCw className={`size-4 ${loading?'animate-spin':''}`}/>تحديث</button>{sorted.map(b=>{const late=b.status==='new'&&mins(b.created_at)>=15;return <article key={`${b.source}-${b.id}`} className={`rounded-[22px] border bg-white p-4 ${late?'border-red-200':''}`}><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><a href={`tel:${b.phone}`} className="grid size-10 place-items-center rounded-xl bg-[#edf4f6] text-[#2b7289]"><Phone className="size-4"/></a>{late&&<span className="grid size-10 place-items-center rounded-xl bg-red-50 text-red-600"><AlertTriangle className="size-4"/></span>}</div><div className="text-right"><div className="flex items-center justify-end gap-2"><span className="text-[10px] text-slate-400">{b.reference}</span><h3 className="font-semibold">{b.customer_name}</h3></div><p className="mt-1 text-xs text-slate-400">{b.source==='captain'?`${b.company||'بدون شركة'} · ${b.lounge||'بدون صالة'}`:'حجز زبون'} · {ago(b.created_at)}</p></div></div><div className="mt-3 grid grid-cols-3 gap-2"><Box label="المسافرون" value={b.passengers}/><Box label="الحقائب" value={b.bags}/><Box label="العربات" value={b.carts||0}/></div><div className="mt-3 flex gap-2 overflow-x-auto">{statuses.map(([k,l])=><button key={k} onClick={()=>status(b.id,k)} className={`shrink-0 rounded-lg px-3 py-2 text-[10px] ${b.status===k?'bg-[#123f58] text-white':'bg-[#f2f6f7] text-slate-500'}`}>{l}</button>)}</div></article>})}{!sorted.length&&<div className="rounded-[22px] border border-dashed bg-white p-10 text-center text-sm text-slate-400">ماكو طلبات حالية</div>}</div></main>
}
function Box({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-white px-2 py-3 text-center"><div className="text-lg font-semibold text-[#153f57]">{value}</div><div className="mt-1 text-[9px] text-slate-400">{label}</div></div>}
