"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import { AlertTriangle,ArrowRight,BadgeDollarSign,Ban,Building2,CheckCircle2,CircleDollarSign,Landmark,Loader2,MessageSquareText,Plus,RefreshCw,Save,Settings2,ShieldAlert,ToggleLeft,ToggleRight,Trash2 } from "lucide-react";

type Lounge={id:string;name:string;active:boolean;price_iqd:number;note:string;sort_order:number};
type Message={id:number;text:string;active:boolean;created_at:string};
type Watch={id:number;kind:"phone"|"captain"|"company";value:string;note:string;active:boolean;created_at:string};
type Company={name:string;price_per_passenger:number;notes:string;orders:number;passengers:number;paid_iqd:number;due_iqd:number};
type Data={lounges:Lounge[];messages:Message[];watchlist:Watch[];companies:Company[];monitor:{new_orders:number;delayed_orders:number;oldest_new:string|null;busiest_lounge:string|null;active_company:string|null}};
type Tab="monitor"|"lounges"|"messages"|"watch"|"companies";
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(Number(n||0))+" د.ع";

export default function OperationsCenter(){
  const [token,setToken]=useState("");const [data,setData]=useState<Data|null>(null);const [tab,setTab]=useState<Tab>("monitor");const [loading,setLoading]=useState(true);const [msg,setMsg]=useState("");
  const [newMessage,setNewMessage]=useState("");const [watch,setWatch]=useState({kind:"phone",value:"",note:""});const [payment,setPayment]=useState({companyName:"",amountIqd:"",note:""});
  useEffect(()=>{const t=sessionStorage.getItem("mainAdminToken")||"";setToken(t);if(t)void load(t);else setLoading(false)},[]);
  async function api(path:string,options:RequestInit={},useToken=token){return fetch(path,{...options,headers:{"Content-Type":"application/json",...(useToken?{Authorization:`Bearer ${useToken}`}:{})}})}
  async function load(t=token){setLoading(true);setMsg("");try{const r=await api("/api/admin/operations",{},t);if(r.status===401){setMsg("سجل دخولك من لوحة الإدارة أولاً");return}const x=await r.json();if(!r.ok)throw new Error(x.message||"تعذر التحميل");setData(x)}catch(e){setMsg(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
  async function patch(body:Record<string,unknown>){const r=await api("/api/admin/operations",{method:"PATCH",body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setMsg(x.message||"تعذر الحفظ");return false}await load();return true}
  async function post(body:Record<string,unknown>){const r=await api("/api/admin/operations",{method:"POST",body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setMsg(x.message||"تعذر الحفظ");return false}await load();return true}
  async function del(action:string,id:number){const r=await api(`/api/admin/operations?action=${action}&id=${id}`,{method:"DELETE"});if(!r.ok){const x=await r.json();setMsg(x.message||"تعذر الحذف");return}await load()}
  const outstanding=useMemo(()=>data?.companies.reduce((s,c)=>s+Math.max(0,Number(c.due_iqd)-Number(c.paid_iqd)),0)||0,[data]);

  if(loading&&!data)return <main className="grid min-h-screen place-items-center bg-[#f3f6f7]"><Loader2 className="size-8 animate-spin text-[#123f58]"/></main>;
  if(!token)return <main dir="rtl" className="min-h-screen bg-[#f3f6f7] p-5"><div className="mx-auto mt-20 max-w-sm rounded-[24px] bg-white p-6 text-center"><ShieldAlert className="mx-auto size-10 text-amber-600"/><h1 className="mt-3 text-xl font-semibold">التشغيل والإعدادات</h1><p className="mt-2 text-sm text-slate-500">سجل دخولك أولاً من لوحة الإدارة.</p><a href="/admin" className="mt-5 block rounded-xl bg-[#123f58] px-4 py-3 text-white">فتح لوحة الإدارة</a></div></main>;

  return <main dir="rtl" className="min-h-screen bg-[#f3f6f7] pb-10 text-[#173448]">
    <header className="sticky top-0 z-20 bg-[#103e56] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><a href="/admin" className="grid size-10 place-items-center rounded-full bg-white/10"><ArrowRight className="size-5"/></a><div className="text-right"><p className="text-[9px] tracking-[.15em] text-white/45">OPERATIONS</p><h1 className="text-lg font-semibold">التشغيل والإعدادات</h1></div></div></header>
    <div className="mx-auto max-w-6xl px-4 py-5">
      {msg&&<div className="mb-4 rounded-2xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-800">{msg}</div>}
      <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{([['monitor','مراقبة التشغيل'],['lounges','الصالات'],['messages','رسائل النظام'],['watch','الحظر والتنبيهات'],['companies','حسابات الشركات']] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-medium ${tab===k?"bg-[#123f58] text-white":"border border-[#dfe7ea] bg-white text-slate-500"}`}>{l}</button>)}<button onClick={()=>load()} className="grid size-10 shrink-0 place-items-center rounded-xl bg-white"><RefreshCw className="size-4"/></button></div>

      {tab==="monitor"&&<div className="space-y-4">
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric icon={<AlertTriangle/>} label="طلبات جديدة" value={data?.monitor.new_orders||0}/><Metric icon={<ShieldAlert/>} label="متأخرة +15 دقيقة" value={data?.monitor.delayed_orders||0} warn/><Metric icon={<Landmark/>} label="أكثر صالة ضغطاً" value={data?.monitor.busiest_lounge||"—"} small/><Metric icon={<Building2/>} label="أنشط شركة 24 ساعة" value={data?.monitor.active_company||"—"} small/><Metric icon={<CircleDollarSign/>} label="رصيد الشركات المتبقي" value={money(outstanding)} small/></div>
        <section className="rounded-[24px] border border-[#e0e8ec] bg-white p-5"><h2 className="font-semibold">حالة النظام</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Status label="الصالات المفتوحة" value={`${data?.lounges.filter(x=>x.active).length||0} من ${data?.lounges.length||0}`}/><Status label="رسائل فعالة" value={String(data?.messages.filter(x=>x.active).length||0)}/><Status label="عناصر مراقبة فعالة" value={String(data?.watchlist.filter(x=>x.active).length||0)}/></div></section>
      </div>}

      {tab==="lounges"&&<section><Title title="إدارة الصالات" sub="أي صالة توقفها هنا تختفي من بوابة الكابتن فوراً"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.lounges.map(l=><LoungeCard key={l.id} lounge={l} onSave={patch}/>)}</div></section>}

      {tab==="messages"&&<section><Title title="رسائل النظام" sub="تنبيه يظهر للكباتن داخل بوابتهم"/><form onSubmit={async e=>{e.preventDefault();if(await post({action:"message",text:newMessage}))setNewMessage("")}} className="mb-4 flex gap-2 rounded-[20px] bg-white p-3"><input value={newMessage} onChange={e=>setNewMessage(e.target.value)} placeholder="مثال: صالة بابل متوقفة مؤقتاً..." className="h-11 flex-1 rounded-xl border px-3 text-sm"/><button className="grid size-11 place-items-center rounded-xl bg-[#123f58] text-white"><Plus className="size-4"/></button></form><div className="space-y-2">{data?.messages.map(m=><div key={m.id} className="flex items-center justify-between gap-3 rounded-[18px] border bg-white p-4"><div className="flex gap-2"><button onClick={()=>del("message",m.id)} className="grid size-9 place-items-center rounded-xl bg-red-50 text-red-600"><Trash2 className="size-4"/></button><button onClick={()=>patch({action:"message",id:m.id,active:!m.active})} className="grid size-9 place-items-center rounded-xl bg-[#f2f6f7] text-[#2b7289]">{m.active?<ToggleRight/>:<ToggleLeft/>}</button></div><div className="text-right"><p className="text-sm font-medium">{m.text}</p><p className="mt-1 text-[10px] text-slate-400">{m.active?"فعالة وتظهر للكباتن":"متوقفة"}</p></div></div>)}</div></section>}

      {tab==="watch"&&<section><Title title="الحظر والتنبيهات" sub="امنع رقم مسافر أو كابتن أو شركة من إرسال طلب جديد"/><form onSubmit={async(e:FormEvent)=>{e.preventDefault();if(await post({action:"watch",...watch}))setWatch({kind:"phone",value:"",note:""})}} className="mb-4 grid gap-2 rounded-[20px] bg-white p-3 sm:grid-cols-4"><select value={watch.kind} onChange={e=>setWatch({...watch,kind:e.target.value})} className="h-11 rounded-xl border px-3 text-sm"><option value="phone">رقم مسافر</option><option value="captain">اسم كابتن</option><option value="company">شركة</option></select><input value={watch.value} onChange={e=>setWatch({...watch,value:e.target.value})} placeholder="القيمة" className="h-11 rounded-xl border px-3 text-sm"/><input value={watch.note} onChange={e=>setWatch({...watch,note:e.target.value})} placeholder="سبب أو ملاحظة" className="h-11 rounded-xl border px-3 text-sm"/><button className="h-11 rounded-xl bg-[#123f58] text-sm font-medium text-white">إضافة</button></form><div className="space-y-2">{data?.watchlist.map(w=><div key={w.id} className="flex items-center justify-between gap-3 rounded-[18px] border bg-white p-4"><div className="flex gap-2"><button onClick={()=>del("watch",w.id)} className="grid size-9 place-items-center rounded-xl bg-red-50 text-red-600"><Trash2 className="size-4"/></button><button onClick={()=>patch({action:"watch",id:w.id,active:!w.active})} className="grid size-9 place-items-center rounded-xl bg-[#f2f6f7] text-[#2b7289]">{w.active?<ToggleRight/>:<ToggleLeft/>}</button></div><div className="text-right"><p className="text-sm font-semibold">{w.value}</p><p className="mt-1 text-[10px] text-slate-400">{w.kind==="phone"?"رقم مسافر":w.kind==="captain"?"كابتن":"شركة"} · {w.note||"بدون ملاحظة"}</p></div></div>)}</div></section>}

      {tab==="companies"&&<section><Title title="حسابات الشركات" sub="حدد سعر المسافر وسجل الدفعات حتى تعرف المتبقي"/><div className="mb-4 grid gap-3 lg:grid-cols-2">{data?.companies.map(c=><CompanyCard key={c.name} company={c} onSave={patch} onPayment={(companyName)=>setPayment({...payment,companyName})}/>)}</div>{payment.companyName&&<form onSubmit={async e=>{e.preventDefault();if(await post({action:"payment",companyName:payment.companyName,amountIqd:Number(payment.amountIqd),note:payment.note}))setPayment({companyName:"",amountIqd:"",note:""})}} className="sticky bottom-3 rounded-[22px] border bg-white p-4 shadow-xl"><div className="mb-3 flex items-center justify-between"><button type="button" onClick={()=>setPayment({companyName:"",amountIqd:"",note:""})} className="text-xs text-slate-400">إلغاء</button><h3 className="font-semibold">تسجيل دفعة — {payment.companyName}</h3></div><div className="grid gap-2 sm:grid-cols-3"><input type="number" value={payment.amountIqd} onChange={e=>setPayment({...payment,amountIqd:e.target.value})} placeholder="المبلغ د.ع" className="h-11 rounded-xl border px-3"/><input value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})} placeholder="ملاحظة اختيارية" className="h-11 rounded-xl border px-3"/><button className="h-11 rounded-xl bg-[#123f58] text-white">تسجيل الدفعة</button></div></form>}</section>}
    </div>
  </main>
}

function Metric({icon,label,value,warn=false,small=false}:{icon:React.ReactNode;label:string;value:string|number;warn?:boolean;small?:boolean}){return <div className={`rounded-[20px] border p-4 ${warn?"border-red-100 bg-red-50":"border-[#e0e8ec] bg-white"}`}><div className="flex items-center justify-between"><span className={`grid size-9 place-items-center rounded-xl ${warn?"bg-red-100 text-red-600":"bg-[#edf4f6] text-[#2b7289]"}`}>{icon}</span><span className={`max-w-[70%] text-left font-semibold ${small?"text-sm":"text-2xl"}`}>{value}</span></div><p className="mt-3 text-[10px] text-slate-400">{label}</p></div>}
function Status({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between rounded-xl bg-[#f7f9fa] p-3"><CheckCircle2 className="size-4 text-emerald-600"/><div className="text-right"><p className="text-xs font-semibold">{value}</p><p className="text-[9px] text-slate-400">{label}</p></div></div>}
function Title({title,sub}:{title:string;sub:string}){return <div className="mb-4"><p className="text-xs text-slate-400">{sub}</p><h2 className="mt-1 text-xl font-semibold">{title}</h2></div>}
function LoungeCard({lounge,onSave}:{lounge:Lounge;onSave:(b:Record<string,unknown>)=>Promise<boolean>}){const [x,setX]=useState(lounge);useEffect(()=>setX(lounge),[lounge]);return <article className="rounded-[22px] border bg-white p-4"><div className="flex items-center justify-between"><button onClick={()=>setX({...x,active:!x.active})} className={`rounded-full px-3 py-1.5 text-[10px] ${x.active?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{x.active?"مفتوحة":"متوقفة"}</button><Landmark className="size-5 text-[#2b7289]"/></div><input value={x.name} onChange={e=>setX({...x,name:e.target.value})} className="mt-3 h-10 w-full rounded-xl border px-3 text-right font-semibold"/><label className="mt-3 block text-[10px] text-slate-400">سعر الشخص — اختياري</label><input type="number" value={x.price_iqd} onChange={e=>setX({...x,price_iqd:Number(e.target.value)})} className="mt-1 h-10 w-full rounded-xl border px-3"/><input value={x.note} onChange={e=>setX({...x,note:e.target.value})} placeholder="ملاحظة للصالة" className="mt-2 h-10 w-full rounded-xl border px-3 text-sm"/><button onClick={()=>onSave({action:"lounge",id:x.id,name:x.name,active:x.active,priceIqd:x.price_iqd,note:x.note,sortOrder:x.sort_order})} className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#123f58] text-xs text-white"><Save className="size-4"/>حفظ</button></article>}
function CompanyCard({company,onSave,onPayment}:{company:Company;onSave:(b:Record<string,unknown>)=>Promise<boolean>;onPayment:(n:string)=>void}){const [price,setPrice]=useState(company.price_per_passenger);const [notes,setNotes]=useState(company.notes);useEffect(()=>{setPrice(company.price_per_passenger);setNotes(company.notes)},[company]);const remaining=Math.max(0,Number(company.due_iqd)-Number(company.paid_iqd));return <article className="rounded-[22px] border bg-white p-4"><div className="flex items-center justify-between"><BadgeDollarSign className="size-5 text-[#2b7289]"/><div className="text-right"><h3 className="font-semibold">{company.name}</h3><p className="mt-1 text-[10px] text-slate-400">{company.orders} طلب · {company.passengers} مسافر</p></div></div><div className="mt-3 grid grid-cols-3 gap-2"><Mini label="الإجمالي" value={money(company.due_iqd)}/><Mini label="المدفوع" value={money(company.paid_iqd)}/><Mini label="المتبقي" value={money(remaining)}/></div><label className="mt-3 block text-[10px] text-slate-400">سعر المسافر للشركة</label><input type="number" value={price} onChange={e=>setPrice(Number(e.target.value))} className="mt-1 h-10 w-full rounded-xl border px-3"/><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات الحساب" className="mt-2 h-10 w-full rounded-xl border px-3 text-sm"/><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>onPayment(company.name)} className="h-10 rounded-xl bg-[#edf4f6] text-xs font-medium text-[#2b7289]">تسجيل دفعة</button><button onClick={()=>onSave({action:"company",companyName:company.name,pricePerPassenger:price,notes})} className="h-10 rounded-xl bg-[#123f58] text-xs font-medium text-white">حفظ الحساب</button></div></article>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f7f9fa] p-2 text-center"><div className="truncate text-[10px] font-semibold">{value}</div><div className="mt-1 text-[8px] text-slate-400">{label}</div></div>}
