"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { ArchiveRestore,DatabaseBackup,FileClock,RefreshCw,ShieldCheck,TriangleAlert,Workflow } from "lucide-react";

type Quality={total:number;counts:Record<string,number>;duplicateCompanies:any[];captainIssues:any[];zeroPriceCompanies:any[];stalePromos:any[];bookingIssues:any[];overdueInvoices:any[];orphanPayments:any[]};
type Summary={quality:Quality;backups:any[];audit:any[];runs:any[]};
const labels:Record<string,string>={duplicateCompanies:'أسماء شركات مكررة',captainIssues:'مشاكل بيانات الكباتن',zeroPriceCompanies:'شركات بدون سعر',stalePromos:'بروموكودات غير صالحة لكنها فعالة',bookingIssues:'حجوزات تحتاج مراجعة',overdueInvoices:'فواتير متأخرة',orphanPayments:'دفعات غير مرتبطة بملف شركة'};
const fmt=(n:any)=>Number(n||0).toLocaleString('en-US');
export default function GovernancePage(){
 const [data,setData]=useState<Summary|null>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[audit,setAudit]=useState<any[]>([]),[label,setLabel]=useState('نسخة احتياطية يدوية'),[restoreId,setRestoreId]=useState<number|''>('');
 const token=typeof window!=='undefined'?sessionStorage.getItem('mainAdminToken')||'':'';
 async function req(url:string,init?:RequestInit){const r=await fetch(url,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.message||'تعذر تنفيذ الطلب');return j}
 async function load(){setLoading(true);setMsg('');try{const j=await req('/api/admin/governance');setData(j);setAudit(j.audit||[])}catch(e){setMsg(e instanceof Error?e.message:'تعذر التحميل')}finally{setLoading(false)}}
 useEffect(()=>{if(!token){location.href='/admin';return}void load()},[]);
 async function searchAudit(){try{const j=await req(`/api/admin/governance?action=audit&q=${encodeURIComponent(q)}`);setAudit(j.audit||[])}catch(e){setMsg(e instanceof Error?e.message:'تعذر البحث')}}
 async function makeBackup(){try{setMsg('');await req('/api/admin/governance',{method:'POST',body:JSON.stringify({action:'backup',label})});setMsg('تم إنشاء النسخة الاحتياطية');await load()}catch(e){setMsg(e instanceof Error?e.message:'تعذر إنشاء النسخة')}}
 async function restore(){if(!restoreId)return;const c=prompt('هذا الاسترجاع يعيد بيانات الإعدادات والملفات الرئيسية فقط، ولا يلمس الطلبات والفواتير والدفعات. اكتب RESTORE للتأكيد');if(c!=='RESTORE')return;try{await req('/api/admin/governance',{method:'POST',body:JSON.stringify({action:'restore',id:restoreId,confirmation:c})});setMsg('تم الاسترجاع بنجاح');await load()}catch(e){setMsg(e instanceof Error?e.message:'تعذر الاسترجاع')}}
 async function runInvoices(){if(!confirm('تشغيل الفوترة الشهرية يدوياً للفترة السابقة؟ العملية تمنع التكرار تلقائياً.'))return;try{const j=await req('/api/admin/governance',{method:'POST',body:JSON.stringify({action:'monthlyInvoices',force:true})});setMsg(j.run?.invoicesCreated!==undefined?`تم إنشاء ${j.run.invoicesCreated} فاتورة`:'تم التشغيل');await load()}catch(e){setMsg(e instanceof Error?e.message:'تعذر تشغيل الفوترة')}}
 const score=useMemo(()=>Math.max(0,100-Math.min(100,(data?.quality.total||0)*5)),[data]);
 return <main dir="rtl" className="min-h-screen bg-[#071a24] text-white p-4 md:p-8">
  <div className="mx-auto max-w-7xl space-y-5">
   <header className="rounded-3xl border border-white/10 bg-white/[.04] p-5 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="text-xs tracking-[.25em] text-[#d8b06d]">GOVERNANCE & RELIABILITY</div><h1 className="mt-2 text-2xl md:text-3xl font-bold">مركز الحوكمة والموثوقية</h1><p className="mt-2 text-sm text-white/60">Audit • Backup • Data Quality • Monthly Automation</p></div><div className="flex gap-2"><button onClick={load} className="btn"><RefreshCw className="size-4"/> تحديث</button><Link href="/admin" className="btn">رجوع للأدمن</Link></div></header>
   {msg&&<div className="rounded-2xl border border-[#d8b06d]/30 bg-[#d8b06d]/10 px-4 py-3 text-sm">{msg}</div>}
   {loading?<div className="rounded-3xl border border-white/10 p-10 text-center text-white/60">جاري فحص النظام...</div>:data&&<>
    <section className="grid md:grid-cols-4 gap-3"><Kpi title="جودة البيانات" value={`${score}%`} icon={<ShieldCheck/>}/><Kpi title="المشاكل المكتشفة" value={fmt(data.quality.total)} icon={<TriangleAlert/>}/><Kpi title="النسخ الاحتياطية" value={fmt(data.backups.length)} icon={<DatabaseBackup/>}/><Kpi title="تشغيلات الفوترة" value={fmt(data.runs.length)} icon={<Workflow/>}/></section>
    <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-lg font-bold">Data Quality Center</h2><p className="text-sm text-white/55 mt-1">فحص مباشر لقاعدة البيانات، مو أرقام ثابتة.</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{Object.entries(data.quality.counts).map(([k,v])=><div key={k} className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="text-xs text-white/55">{labels[k]||k}</div><div className={`mt-2 text-2xl font-bold ${v?'text-amber-300':'text-emerald-300'}`}>{fmt(v)}</div></div>)}</div>
      <div className="grid lg:grid-cols-2 gap-4 mt-5"><IssueBox title="الشركات بدون سعر" rows={data.quality.zeroPriceCompanies} render={(x:any)=>`${x.name} — السعر ${fmt(x.price)}`}/><IssueBox title="الكباتن المحتاجين تصحيح" rows={data.quality.captainIssues} render={(x:any)=>`${x.name} — ${x.company||'بدون شركة'} — ${x.phone||'بدون رقم'}`}/><IssueBox title="البروموكودات غير الصالحة" rows={data.quality.stalePromos} render={(x:any)=>`${x.company_name} — ${x.code}`}/><IssueBox title="الفواتير المتأخرة" rows={data.quality.overdueInvoices} render={(x:any)=>`${x.invoice_number} — ${x.company_name} — ${x.due_date}`}/></div>
    </section>
    <section className="grid lg:grid-cols-2 gap-4"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center gap-2"><DatabaseBackup className="size-5 text-[#d8b06d]"/><h2 className="text-lg font-bold">Backup / Restore</h2></div><p className="text-xs text-white/50 mt-2">النسخة تشمل ملفات الشركات والكباتن والخصومات وإعدادات التشغيل. الاسترجاع لا يكتب فوق الطلبات والفواتير والدفعات.</p><div className="flex gap-2 mt-4"><input className="field flex-1" value={label} onChange={e=>setLabel(e.target.value)}/><button onClick={makeBackup} className="btn">إنشاء نسخة</button></div><div className="mt-4 space-y-2 max-h-72 overflow-auto">{data.backups.map((b:any)=><button key={b.id} onClick={()=>setRestoreId(b.id)} className={`w-full text-right rounded-2xl border p-3 ${restoreId===b.id?'border-[#d8b06d] bg-[#d8b06d]/10':'border-white/10 bg-black/10'}`}><div className="font-semibold">#{b.id} — {b.label}</div><div className="text-xs text-white/50 mt-1">{b.row_count} سجل • {new Date(b.created_at).toLocaleString('ar-IQ')}</div></button>)}</div><button disabled={!restoreId} onClick={restore} className="btn mt-3 w-full"><ArchiveRestore className="size-4"/> استرجاع النسخة المحددة</button></div>
      <div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center gap-2"><Workflow className="size-5 text-[#d8b06d]"/><h2 className="text-lg font-bold">الفوترة الشهرية التلقائية</h2></div><p className="text-sm text-white/55 mt-2">النظام يفحص يومياً، وفي أول يوم من الشهر ينشئ فواتير الشهر السابق للشركات ذات دورة الفوترة الشهرية، مع منع إنشاء نفس الفاتورة مرتين.</p><button onClick={runInvoices} className="btn mt-4">تشغيل يدوي الآن</button><div className="mt-4 space-y-2 max-h-72 overflow-auto">{data.runs.map((r:any)=><div key={r.id} className="rounded-2xl border border-white/10 p-3"><div className="font-semibold">{r.period_from} → {r.period_to}</div><div className="text-xs text-white/50 mt-1">تم فحص {r.companies_checked} شركة • تم إنشاء {r.invoices_created} فاتورة • {r.created_by}</div></div>)}</div></div></section>
    <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="flex items-center gap-2"><FileClock className="size-5 text-[#d8b06d]"/><h2 className="text-lg font-bold">Audit Trail</h2></div><p className="text-xs text-white/50 mt-1">التغييرات تسجل من قاعدة البيانات نفسها مع Before / After.</p></div><div className="flex gap-2"><input className="field" placeholder="شركة، فاتورة، جدول، مستخدم..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void searchAudit()}}/><button onClick={searchAudit} className="btn">بحث</button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="text-white/45"><tr><th className="p-2 text-right">الوقت</th><th className="p-2 text-right">الجدول</th><th className="p-2 text-right">العملية</th><th className="p-2 text-right">السجل</th><th className="p-2 text-right">المنفذ</th></tr></thead><tbody>{audit.map((a:any)=><tr key={a.id} className="border-t border-white/8"><td className="p-2 whitespace-nowrap">{new Date(a.created_at).toLocaleString('ar-IQ')}</td><td className="p-2">{a.table_name}</td><td className="p-2">{a.action}</td><td className="p-2">{a.record_key||'—'}</td><td className="p-2">{a.actor}</td></tr>)}</tbody></table></div></section>
   </>}
  </div>
 </main>
}
function Kpi({title,value,icon}:{title:string;value:string;icon:React.ReactNode}){return <div className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center justify-between text-white/55 text-sm"><span>{title}</span><span className="text-[#d8b06d] [&>svg]:size-5">{icon}</span></div><div className="mt-3 text-3xl font-bold">{value}</div></div>}
function IssueBox({title,rows,render}:{title:string;rows:any[];render:(x:any)=>string}){return <div className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="font-semibold">{title} <span className="text-white/40">({rows.length})</span></div><div className="mt-3 space-y-2 max-h-48 overflow-auto">{rows.length?rows.map((r,i)=><div key={i} className="rounded-xl bg-white/[.04] px-3 py-2 text-sm text-white/75">{render(r)}</div>):<div className="text-sm text-emerald-300">ماكو مشاكل</div>}</div></div>}
