"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Banknote, CarFront, Check, CreditCard, FileText, Loader2, Luggage, Minus, PlaneLanding, PlaneTakeoff, Plus, Tag, Upload, Users } from "lucide-react";
import { BAGHDAD_AIRLINES, OTHER_AIRLINE } from "@/lib/airlines";

type Lang="ar"|"en";
type Promo={code:string;companyName:string;discountPercent:number};
type FormState={tripType:"departure"|"arrival";transport:"self"|"chauffeur";side:"karkh"|"rusafa";name:string;phone:string;airline:string;flightNumber:string;date:string;time:string;passengers:number;bags:number;address:string;landmark:string;notes:string;payment:"cash"|"wayl";promoCode:string};
const initial:FormState={tripType:"departure",transport:"self",side:"karkh",name:"",phone:"",airline:"",flightNumber:"",date:"",time:"",passengers:1,bags:0,address:"",landmark:"",notes:"",payment:"cash",promoCode:""};
const text={
 ar:{arrange:"رتّب تجربتك الآن",intro:"أدخل تفاصيل رحلتك وسيقوم فريقنا بمتابعة الحجز معك مباشرة.",trip:"ما نوع رحلتك؟",departure:"مغادرة من المطار",arrival:"استقبال من المطار",depDesc:"ترتيب وصولك ودخولك إلى الصالة قبل السفر",arrDesc:"استقبالك بعد الوصول وتجربة أكثر راحة",transport:"خدمة الوصول",carQ:"هل تحتاج سيارة خاصة؟",self:"سأصل بنفسي",selfDesc:"حجز الصالة فقط بدون سيارة",car:"أحتاج سيارة خاصة",carDesc:"سيارة خاصة من أو إلى مطار بغداد",side:"الجانب",karkh:"الكرخ",rusafa:"الرصافة",address:"العنوان الكامل",landmark:"أقرب نقطة دالة (اختياري)",traveler:"تفاصيل المسافر",name:"الاسم الكامل",phone:"رقم الهاتف",airline:"شركة الطيران",select:"اختر شركة الطيران",flight:"رقم الرحلة",date:"التاريخ",time:"الوقت",passengers:"عدد المسافرين",bags:"عدد الحقائب",kids:"الأطفال دون 12 سنة دخولهم مجاناً.",notes:"ملاحظات إضافية (اختياري)",ticket:"عندك تذكرة جاهزة؟",ticketText:"ارفع صورة التذكرة أو PDF ونعبّي معلومات الرحلة تلقائياً.",upload:"ارفع التذكرة",reading:"جارٍ قراءة التذكرة...",ticketReady:"تمت قراءة التذكرة. راجع المعلومات.",ticketError:"تعذرت قراءة التذكرة.",payment:"اختر طريقة الدفع",cash:"الدفع كاش",cashDesc:"الدفع عند تقديم الخدمة",wayl:"الدفع الإلكتروني",waylDesc:"دفع آمن عن طريق Wayl",promo:"رمز خصم الشركات",promoText:"أدخل رمز شركتك وسيتم التحقق منه مباشرة من النظام.",apply:"تطبيق",checking:"تحقق...",invalid:"رمز الخصم غير صحيح أو منتهي أو موقوف.",summary:"ملخص الحجز",lounge:"دخول الصالة",extra:"خدمة حقائب إضافية",discount:"خصم",total:"المجموع النهائي",back:"رجوع",next:"التالي",confirm:"تأكيد الحجز",booking:"جاري الحجز",success:"تم استلام طلبك بنجاح",successText:"احتفظ برقم الحجز وسيقوم فريقنا بالتواصل معك.",error:"تعذر إتمام الحجز، تحقق من المعلومات وحاول مرة أخرى"},
 en:{arrange:"Arrange your experience",intro:"Enter your flight details and our team will follow up directly.",trip:"What type of trip is this?",departure:"Departure",arrival:"Arrival",depDesc:"Lounge access before departure",arrDesc:"Comfortable welcome after landing",transport:"Airport access",carQ:"Do you need a private car?",self:"I will arrive myself",selfDesc:"Lounge only, no private car",car:"Private car",carDesc:"Private transfer to or from Baghdad Airport",side:"Baghdad side",karkh:"Karkh",rusafa:"Rusafa",address:"Full address",landmark:"Nearest landmark (optional)",traveler:"Traveler details",name:"Full name",phone:"Phone number",airline:"Airline",select:"Select airline",flight:"Flight number",date:"Date",time:"Time",passengers:"Passengers",bags:"Bags",kids:"Children under 12 enter free.",notes:"Additional notes (optional)",ticket:"Have your ticket?",ticketText:"Upload an image or PDF and we will fill the flight details.",upload:"Upload ticket",reading:"Reading ticket...",ticketReady:"Ticket read. Please review the details.",ticketError:"Could not read the ticket.",payment:"Choose payment method",cash:"Cash",cashDesc:"Pay when service is provided",wayl:"Online payment",waylDesc:"Secure payment via Wayl",promo:"Company promo code",promoText:"Enter your company code. It is checked live against our system.",apply:"Apply",checking:"Checking...",invalid:"This promo code is invalid, expired or inactive.",summary:"Booking summary",lounge:"Lounge access",extra:"Extra baggage handling",discount:"Discount",total:"Final total",back:"Back",next:"Next",confirm:"Confirm booking",booking:"Booking...",success:"Booking received successfully",successText:"Keep your booking reference. Our team will contact you.",error:"Could not complete the booking. Please check the details and try again."}
} as const;

export function BookingExperienceLive({lang}:{lang:Lang}){
 const t=text[lang],rtl=lang==="ar";
 const [step,setStep]=useState(1);const [form,setForm]=useState<FormState>(initial);const [promo,setPromo]=useState<Promo|null>(null);const [promoStatus,setPromoStatus]=useState<"idle"|"checking"|"valid"|"invalid">("idle");const [loading,setLoading]=useState(false);const [extracting,setExtracting]=useState(false);const [ticketMessage,setTicketMessage]=useState("");const [error,setError]=useState("");const [result,setResult]=useState<{reference:string;paymentUrl?:string}|null>(null);
 const loungeTotal=form.passengers*40000;const carTotal=form.transport==="chauffeur"?75000:0;const extraTotal=form.bags>4?10000:0;const subtotal=loungeTotal+carTotal+extraTotal;const discount=promo?Math.round(subtotal*promo.discountPercent/100):0;const total=subtotal-discount;
 const money=(n:number)=>lang==="ar"?new Intl.NumberFormat("ar-IQ").format(n)+" د.ع":"IQD "+new Intl.NumberFormat("en-US").format(n);
 const patch=<K extends keyof FormState>(k:K,v:FormState[K])=>setForm(x=>({...x,[k]:v}));
 const canContinue=useMemo(()=>step<3||Boolean(form.name.trim()&&/^\+?[0-9\s-]{8,20}$/.test(form.phone)&&form.airline&&form.flightNumber.trim()&&form.date&&form.time),[step,form]);

 useEffect(()=>{const code=new URLSearchParams(window.location.search).get("promo");if(code){const normalized=code.trim().toUpperCase();setForm(v=>({...v,promoCode:normalized}));void validatePromo(normalized,true)}},[]);
 async function validatePromo(code=form.promoCode,auto=false){const normalized=code.trim().toUpperCase();if(!normalized){setPromo(null);setPromoStatus("idle");return false}setPromoStatus("checking");setError("");try{const r=await fetch("/api/promos/validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:normalized})});const x=await r.json();if(!r.ok||!x.valid){setPromo(null);setPromoStatus("invalid");return false}const applied={code:String(x.code),companyName:String(x.companyName),discountPercent:Number(x.discountPercent)};setPromo(applied);setForm(v=>({...v,promoCode:applied.code}));setPromoStatus("valid");if(auto)setStep(4);return true}catch{setPromo(null);setPromoStatus("invalid");return false}}
 async function submit(){setLoading(true);setError("");try{if(form.promoCode){const ok=promo&&promo.code===form.promoCode?true:await validatePromo(form.promoCode);if(!ok)throw new Error(t.invalid)}const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const x=await r.json();if(!r.ok)throw new Error(x.error||t.error);setResult(x);if(x.paymentUrl)window.location.href=x.paymentUrl}catch(e){setError(e instanceof Error?e.message:t.error)}finally{setLoading(false)}}
 async function extractTicket(file?:File){if(!file)return;setExtracting(true);setTicketMessage("");try{const body=new FormData();body.append("ticket",file);const r=await fetch("/api/ticket/extract",{method:"POST",body});const x=await r.json();if(!r.ok)throw new Error(x.error||t.ticketError);const d=x.details||{};setForm(v=>({...v,name:typeof d.name==="string"?d.name:v.name,airline:typeof d.airline==="string"?d.airline:v.airline,flightNumber:typeof d.flightNumber==="string"?d.flightNumber.toUpperCase():v.flightNumber,date:typeof d.date==="string"?d.date:v.date,time:typeof d.time==="string"?d.time:v.time,tripType:d.tripType==="arrival"||d.tripType==="departure"?d.tripType:v.tripType}));setTicketMessage(t.ticketReady)}catch(e){setTicketMessage(e instanceof Error?e.message:t.ticketError)}finally{setExtracting(false)}}

 if(result&&!result.paymentUrl)return <section id="booking" dir={rtl?"rtl":"ltr"} className="bg-[#f5f6f7] px-5 py-20 text-[#081a2b]"><div className="mx-auto max-w-xl rounded-xl border bg-white p-10 text-center shadow-xl"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#081a2b] text-white"><Check size={30}/></div><h2 className="mt-6 text-2xl font-bold">{t.success}</h2><p className="mt-3 text-sm text-slate-500">{t.successText}</p><div className="mt-6 border border-dashed border-[#b9a476] bg-[#f7f5ef] p-4 font-mono text-xl tracking-widest">{result.reference}</div>{promo&&<p className="mt-4 text-xs text-emerald-700">{rtl?`تم تطبيق خصم شركة ${promo.companyName} بنسبة ${promo.discountPercent}%`:`${promo.companyName} discount applied: ${promo.discountPercent}%`}</p>}</div></section>;

 return <section id="booking" dir={rtl?"rtl":"ltr"} className="booking-section relative bg-[#ded3bd] px-5 py-20 text-[#061827] lg:px-14 lg:py-28"><div className="booking-pattern absolute inset-0"/><div className="relative mx-auto max-w-5xl"><div className="mb-12 text-center"><p className="text-[9px] tracking-[.18em] text-[#a65f3c]">LB · BUSINESS CLASS RESERVATION</p><h2 className="mt-4 text-3xl font-medium sm:text-5xl">{t.arrange}</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-7 text-[#6f685e]">{t.intro}</p></div><div className="booking-shell grid overflow-hidden bg-[#061827] text-[#f5eddf] lg:grid-cols-[1fr_340px]"><div className="p-5 sm:p-8 lg:p-10">
  {step===1&&<><div className="mb-8 rounded-xl border bg-[#f8fafb] p-5 text-[#081a2b]"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#081a2b] text-[#d2bb8b]"><FileText size={18}/></span><div><b className="text-sm">{t.ticket}</b><p className="mt-1 text-[11px] text-[#71818e]">{t.ticketText}</p></div></div><label className="mt-4 flex h-12 cursor-pointer items-center justify-center gap-2 rounded-lg bg-[#081a2b] text-xs font-bold text-white">{extracting?<Loader2 className="size-4 animate-spin"/>:<Upload className="size-4"/>}{extracting?t.reading:t.upload}<input type="file" className="sr-only" accept="image/*,application/pdf" disabled={extracting} onChange={e=>{void extractTicket(e.target.files?.[0]);e.currentTarget.value=""}}/></label>{ticketMessage&&<p className="mt-3 text-[11px] text-emerald-700">{ticketMessage}</p>}</div><Title title={t.trip}/><div className="grid gap-3 sm:grid-cols-2"><Choice active={form.tripType==="departure"} onClick={()=>patch("tripType","departure")} icon={<PlaneTakeoff/>} title={t.departure} desc={t.depDesc}/><Choice active={form.tripType==="arrival"} onClick={()=>patch("tripType","arrival")} icon={<PlaneLanding/>} title={t.arrival} desc={t.arrDesc}/></div></>}
  {step===2&&<><Title title={t.carQ}/><div className="grid gap-3 sm:grid-cols-2"><Choice active={form.transport==="self"} onClick={()=>patch("transport","self")} icon={<Users/>} title={t.self} desc={t.selfDesc}/><Choice active={form.transport==="chauffeur"} onClick={()=>patch("transport","chauffeur")} icon={<CarFront/>} title={t.car} desc={t.carDesc}/></div>{form.transport==="chauffeur"&&<div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label={t.side}><select className="field" value={form.side} onChange={e=>patch("side",e.target.value as FormState["side"])}><option value="karkh">{t.karkh}</option><option value="rusafa">{t.rusafa}</option></select></Field><Field label={t.address}><input className="field" value={form.address} onChange={e=>patch("address",e.target.value)}/></Field><div className="sm:col-span-2"><Field label={t.landmark}><input className="field" value={form.landmark} onChange={e=>patch("landmark",e.target.value)}/></Field></div></div>}</>}
  {step===3&&<><Title title={t.traveler}/><div className="grid gap-5 sm:grid-cols-2"><Field label={t.name}><input className="field" value={form.name} onChange={e=>patch("name",e.target.value)}/></Field><Field label={t.phone}><input className="field" dir="ltr" inputMode="tel" value={form.phone} onChange={e=>patch("phone",e.target.value)}/></Field><Field label={t.airline}><select className="field" value={form.airline} onChange={e=>patch("airline",e.target.value)}><option value="">{t.select}</option>{BAGHDAD_AIRLINES.map(a=><option key={a.code} value={`${a.en} (${a.code})`}>{rtl?a.ar:a.en} — {a.code}</option>)}<option value={`${OTHER_AIRLINE.en} (${OTHER_AIRLINE.code})`}>{OTHER_AIRLINE.en}</option></select></Field><Field label={t.flight}><input className="field" dir="ltr" value={form.flightNumber} onChange={e=>patch("flightNumber",e.target.value.toUpperCase())}/></Field><Field label={t.date}><input className="field" type="date" value={form.date} onChange={e=>patch("date",e.target.value)}/></Field><Field label={t.time}><input className="field" type="time" value={form.time} onChange={e=>patch("time",e.target.value)}/></Field><Counter label={t.passengers} value={form.passengers} min={1} max={20} onChange={v=>patch("passengers",v)}/><Counter label={t.bags} value={form.bags} min={0} max={40} onChange={v=>patch("bags",v)}/><p className="sm:col-span-2 text-[11px] text-[#8f897f]">{t.kids}</p><div className="sm:col-span-2"><Field label={t.notes}><textarea className="field min-h-24" value={form.notes} onChange={e=>patch("notes",e.target.value)}/></Field></div></div></>}
  {step===4&&<><Title title={t.payment}/><div className="grid gap-3 sm:grid-cols-2"><Choice active={form.payment==="cash"} onClick={()=>patch("payment","cash")} icon={<Banknote/>} title={t.cash} desc={t.cashDesc}/><Choice active={form.payment==="wayl"} onClick={()=>patch("payment","wayl")} icon={<CreditCard/>} title={t.wayl} desc={t.waylDesc}/></div><div className="mt-5 rounded-xl border border-[#d2bb8b]/45 bg-[#fbf8f1] p-5 text-[#081a2b]"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#081a2b] text-[#d2bb8b]"><Tag size={17}/></span><div><b className="text-sm">{t.promo}</b><p className="mt-1 text-[11px] text-[#71818e]">{t.promoText}</p></div></div><div className="mt-4 flex gap-2"><input className="field min-w-0 flex-1 uppercase" dir="ltr" value={form.promoCode} onChange={e=>{patch("promoCode",e.target.value.toUpperCase());setPromo(null);setPromoStatus("idle")}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void validatePromo()}}}/><button type="button" disabled={promoStatus==="checking"} onClick={()=>void validatePromo()} className="min-w-24 rounded-lg bg-[#081a2b] px-4 text-xs font-bold text-white">{promoStatus==="checking"?t.checking:t.apply}</button></div>{promoStatus==="invalid"&&<p className="mt-3 text-[11px] text-red-600">{t.invalid}</p>}{promo&&<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-[11px] text-emerald-800"><b>{rtl?`تم تطبيق خصم شركة ${promo.companyName}`:`${promo.companyName} discount applied`}</b><div className="mt-1">{promo.discountPercent}% · − {money(discount)}</div></div>}</div>{error&&<div className="mt-5 border border-red-500/30 bg-red-950/20 p-3 text-sm text-red-300">{error}</div>}</>}
  <div className="mt-10 flex justify-between border-t border-white/10 pt-6"><button disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))} className="flex items-center gap-2 text-sm disabled:invisible">{rtl?<ArrowRight size={16}/>:<ArrowLeft size={16}/>} {t.back}</button>{step<4?<button disabled={!canContinue} onClick={()=>setStep(s=>Math.min(4,s+1))} className="flex items-center gap-2 bg-[#d2bb8b] px-6 py-3 text-sm font-bold text-[#081a2b] disabled:opacity-40">{t.next}{rtl?<ArrowLeft size={16}/>:<ArrowRight size={16}/>}</button>:<button disabled={loading||promoStatus==="checking"} onClick={submit} className="flex min-w-40 items-center justify-center gap-2 bg-[#d2bb8b] px-6 py-3 text-sm font-bold text-[#081a2b] disabled:opacity-50">{loading?<Loader2 className="size-4 animate-spin"/>:null}{loading?t.booking:t.confirm}</button>}</div>
 </div><aside className="booking-summary border-t border-white/10 bg-[#04131f] p-6 lg:border-r lg:p-8"><p className="text-[11px] tracking-[.12em] text-[#d2bb8b]">{t.summary}</p><div className="mt-7 space-y-4 text-sm"><Summary label={t.trip} value={form.tripType==="departure"?t.departure:t.arrival}/><Summary label={t.passengers} value={String(form.passengers)} icon={<Users size={14}/>}/><Summary label={t.bags} value={String(form.bags)} icon={<Luggage size={14}/>}/>{promo&&<Summary label={rtl?"الشركة":"Company"} value={promo.companyName}/>}</div><div className="my-7 h-px bg-white/10"/><div className="space-y-3 text-xs text-[#a19b92]"><Row label={`${t.lounge} × ${form.passengers}`} value={money(loungeTotal)}/>{carTotal>0&&<Row label={t.car} value={money(carTotal)}/>} {extraTotal>0&&<Row label={t.extra} value={money(extraTotal)}/>} {promo&&<div className="flex justify-between gap-4 text-emerald-300"><span>{t.discount} {promo.companyName} ({promo.discountPercent}%)</span><span>− {money(discount)}</span></div>}</div><div className="mt-5 flex items-end justify-between border-t border-dashed border-white/15 pt-5"><span className="text-sm">{t.total}</span><strong className="text-xl text-[#d2bb8b]">{money(total)}</strong></div></aside></div></div></section>
}
function Title({title}:{title:string}){return <div className="mb-7"><h3 className="text-xl sm:text-2xl">{title}</h3></div>}
function Choice({active,onClick,icon,title,desc}:{active:boolean;onClick:()=>void;icon:React.ReactNode;title:string;desc:string}){return <button type="button" onClick={onClick} className={`choice min-h-32 rounded-lg p-5 text-right ${active?"active":""}`}><span className={active?"text-[#a98e59]":"text-[#71818e]"}>{icon}</span><span className="mt-4 block text-sm">{title}</span><span className="mt-2 block text-[11px] leading-5 text-[#71818e]">{desc}</span></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
function Counter({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void}){return <div><span className="label">{label}</span><div className="flex h-12 items-center justify-between rounded-lg border bg-white px-2 text-[#081a2b]"><button type="button" onClick={()=>onChange(Math.max(min,value-1))} disabled={value<=min}><Minus size={15}/></button><b>{value}</b><button type="button" onClick={()=>onChange(Math.min(max,value+1))} disabled={value>=max}><Plus size={15}/></button></div></div>}
function Summary({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return <div className="flex justify-between gap-3"><span className="flex items-center gap-2 text-[#6f6b65]">{icon}{label}</span><span className="text-[#c5bfb6]">{value}</span></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4"><span>{label}</span><span>{value}</span></div>}
