"use client";
import { useEffect,useRef,useState } from "react";
import { usePathname } from "next/navigation";
function fieldByLabel(text:string){const labels=Array.from(document.querySelectorAll("label"));return labels.find(l=>l.textContent?.includes(text))?.querySelector("input,select,textarea") as HTMLInputElement|HTMLSelectElement|null}
function setNative(el:HTMLInputElement|HTMLSelectElement|null,value:string){if(!el)return;const proto=el instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,"value")?.set;setter?.call(el,value);el.dispatchEvent(new Event(el instanceof HTMLSelectElement?"change":"input",{bubbles:true}))}
export default function OpsPricingBridge(){const pathname=usePathname();const timer=useRef<number|null>(null);const [open,setOpen]=useState(false);const [category,setCategory]=useState("adult");const [age,setAge]=useState("");const [code,setCode]=useState("");const [priceInfo,setPriceInfo]=useState("");const [reasons,setReasons]=useState<string[]>([]);const [reason,setReason]=useState("");const ctx=useRef({category:"adult",age:"",code:""});useEffect(()=>{ctx.current={category,age,code}},[category,age,code]);
 useEffect(()=>{if(pathname!=="/ops")return;let alive=true;const originalFetch=window.fetch.bind(window);let lastKey="";async function apply(){const company=String(fieldByLabel("الجهة / الشركة")?.value||"").trim();const airline=String(fieldByLabel("شركة الطيران")?.value||"").trim();let lounge="",shift="";try{const sr=await originalFetch("/api/ops/shift",{cache:"no-store"});if(sr.ok){const sd=await sr.json();lounge=String(sd.shift?.lounge_name||"");shift=String(sd.shift?.shift_name||"")}}catch{}const q=new URLSearchParams({action:"resolve",company,airline,lounge,shift,category:ctx.current.category,code:ctx.current.code});if(ctx.current.age)q.set("age",ctx.current.age);try{const r=await originalFetch(`/api/ops/pricing?${q.toString()}`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();const p=d.pricing;if(!p||!alive)return;setNative(fieldByLabel("المبلغ"),String(p.priceIqd??40000));setNative(fieldByLabel("طريقة الحساب"),String(p.paymentType||"cash"));const amount=fieldByLabel("المبلغ");if(amount){amount.readOnly=!Boolean(p.settings?.allow_manual_override);amount.title=`${p.label||"السعر المعتمد"} — ${Number(p.priceIqd||0).toLocaleString("en-US")} د.ع`}setReasons(Array.isArray(p.settings?.discount_reasons)?p.settings.discount_reasons.map(String):[]);setPriceInfo(`${p.label||"السعر المعتمد"}: ${Number(p.priceIqd||0).toLocaleString("en-US")} د.ع`) }catch{}}
 const wrapped=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==="string"?input:input instanceof URL?input.toString():(input as Request).url;if(url.includes("/api/ops/entries")&&String(init?.method||"GET").toUpperCase()==="POST"&&typeof init?.body==="string"){try{const body=JSON.parse(init.body);body.passengerCategory=ctx.current.category;body.passengerAge=ctx.current.age?Number(ctx.current.age):undefined;body.specialCode=ctx.current.code;init={...init,body:JSON.stringify(body)}}catch{}}return originalFetch(input as any,init)};window.fetch=wrapped as typeof window.fetch;
 const tick=()=>{const key=[fieldByLabel("الجهة / الشركة")?.value||"",fieldByLabel("شركة الطيران")?.value||"",ctx.current.category,ctx.current.age,ctx.current.code].join("|");if(key!==lastKey){lastKey=key;apply()}const amount=fieldByLabel("المبلغ");if(amount&&!amount.value)apply()};apply();timer.current=window.setInterval(tick,650);return()=>{alive=false;if(timer.current)window.clearInterval(timer.current);window.fetch=originalFetch}},[pathname]);
 function chooseReason(v:string){setReason(v);if(!v)return;const notes=fieldByLabel("ملاحظات");if(notes){const old=String(notes.value||"").trim();setNative(notes,old?`${old} | سبب تعديل السعر: ${v}`:`سبب تعديل السعر: ${v}`)}}
 if(pathname!=="/ops")return null;return <><button type="button" onClick={()=>setOpen(v=>!v)} style={{position:"fixed",left:14,bottom:14,zIndex:80,border:"1px solid #c8a66a",background:"#c8a66a",color:"#07111f",borderRadius:999,padding:"10px 14px",fontWeight:900,boxShadow:"0 8px 24px rgba(0,0,0,.35)"}}>تفاصيل التسعير</button>{open?<div dir="rtl" style={{position:"fixed",left:14,bottom:66,zIndex:90,width:"min(360px,calc(100vw - 28px))",background:"#0d1829",color:"#f8fafc",border:"1px solid #334155",borderRadius:16,padding:14,boxShadow:"0 18px 50px rgba(0,0,0,.5)"}}><div style={{fontWeight:950,fontSize:18}}>تفاصيل تسعير المسافر</div><div style={{color:"#94a3b8",fontSize:12,margin:"4px 0 12px"}}>اختياري — للفئات والعمر والكود الخاص وأسباب تعديل السعر.</div><label style={{display:"grid",gap:5,marginBottom:9}}>الفئة<select value={category} onChange={e=>setCategory(e.target.value)} style={inp}><option value="adult">بالغ</option><option value="child">طفل</option><option value="infant">رضيع</option><option value="vip">VIP</option></select></label><label style={{display:"grid",gap:5,marginBottom:9}}>العمر<input inputMode="numeric" value={age} onChange={e=>setAge(e.target.value.replace(/\D/g,""))} style={inp} placeholder="اختياري"/></label><label style={{display:"grid",gap:5,marginBottom:9}}>كود/شخص خاص<input value={code} onChange={e=>setCode(e.target.value)} style={inp} placeholder="مثال VIP-001"/></label>{reasons.length?<label style={{display:"grid",gap:5,marginBottom:9}}>سبب الخصم/تعديل السعر<select value={reason} onChange={e=>chooseReason(e.target.value)} style={inp}><option value="">اختر السبب</option>{reasons.map(r=><option key={r} value={r}>{r}</option>)}</select></label>:null}{priceInfo?<div style={{borderTop:"1px solid #334155",paddingTop:10,color:"#86efac",fontWeight:900}}>{priceInfo}</div>:null}</div>:null}</>}
const inp:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#07111f",color:"#f8fafc",border:"1px solid #334155",borderRadius:10,padding:"10px 11px",fontSize:15};
