"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,ArrowRight,Building2,CheckCircle2,CircleDollarSign,Database,FileText,HeartPulse,Loader2,LockKeyhole,Play,Power,Printer,RefreshCw,ShieldCheck,Trash2,UserPlus,UsersRound,Wallet,Wrench} from "lucide-react";

type User={id:number;username:string;name:string;role:"owner"|"manager"|"reception"|"accountant";active:boolean;last_login_at:string|null;created_at:string};
type Rule={id:number;kind:string;name:string;threshold_value:number;active:boolean;updated_at:string};
type Health={database:{ok:boolean;latencyMs:number};telegram:{ok:boolean;configured:boolean};payments:{ok:boolean;configured:boolean};unresolvedErrors:number;checkedAt:string};
type ErrorRow={id:number;source:string;message:string;details:string;resolved:boolean;created_at:string};
type Company={name:string;price_per_passenger:number;passengers:number;paid_iqd:number;due_iqd:number};
type Statement={companyName:string;from:string;to:string;pricePerPassenger:number;orders:any[];passengers:number;dueIqd:number;payments:any[];paidIqd:number;balanceIqd:number;notes:string};
const roleLabel:Record<string,string>={owner:"مالك النظام",manager:"مدير",reception:"استقبال",accountant:"محاسب"};
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(Number(n||0))+" د.ع";
const fmt=(v:string)=>new Intl.DateTimeFormat("ar-IQ",{timeZone:"Asia/Baghdad",dateStyle:"medium",timeStyle:"short"}).format(new Date(v));

export default function SystemCenter(){
 const [token,setToken]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const [users,setUsers]=useState<User[]>([]);const [rules,setRules]=useState<Rule[]>([]);const [health,setHealth]=useState<Health|null>(null);const [errors,setErrors]=useState<ErrorRow[]>([]);const [companies,setCompanies]=useState<Company[]>([]);const [session,setSession]=useState<any>(null);
 const [userForm,setUserForm]=useState({name:"",username:"",password:"",role:"manager"});
 const today=new Date().toISOString().slice(0,10);const monthStart=today.slice(0,8)+"01";const [statementForm,setStatementForm]=useState({company:"",from:monthStart,to:today});const [statement,setStatement]=useState<Statement|null>(null);
 useEffect(()=>{const t=sessionStorage.getItem("mainAdminToken")||"";setToken(t);if(t)void load(t);else setLoading(false)},[]);
 async function api(path:string,opt:RequestInit={},t=token){return fetch(path,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`}})}
 async function load(t=token){setLoading(true);setMessage("");try{const [ov,er,op]=await Promise.all([api("/api/admin/enterprise",{},t),api("/api/admin/enterprise?action=errors",{},t),api("/api/admin/operations",{},t)]);if(ov.status===401){location.href="/admin";return}const a=await ov.json();const b=er.ok?await er.json():{errors:[]};const c=op.ok?await op.json():{companies:[]};if(!ov.ok)throw new Error(a.message||"تعذر تحميل المركز المتقدم");setSession(a.session);setUsers(a.users||[]);setRules(a.rules||[]);setHealth(a.health||null);setErrors(b.errors||[]);setCompanies(c.companies||[])}catch(e){setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
 async function createUser(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await api("/api/admin/enterprise",{method:"POST",body:JSON.stringify({action:"user",...userForm})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر إنشاء المستخدم");return}setUserForm({name:"",username:"",password:"",role:"manager"});await load()}finally{setBusy(false)}}
 async function patchUser(u:User,p:Record<string,unknown>){const r=await api("/api/admin/enterprise",{method:"PATCH",body:JSON.stringify({action:"user",id:u.id,...p})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر تعديل المستخدم");return}await load()}
 async function removeUser(u:User){if(!confirm(`حذف حساب ${u.name}؟`))return;const r=await api(`/api/admin/enterprise?id=${u.id}`,{method:"DELETE"});if(!r.ok){const x=await r.json();setMessage(x.message||"تعذر الحذف");return}await load()}
 async function patchRule(r:Rule,p:Record<string,unknown>){const q=await api("/api/admin/enterprise",{method:"PATCH",body:JSON.stringify({action:"rule",id:r.id,thresholdValue:r.threshold_value,active:r.active,...p})});if(!q.ok){const x=await q.json();setMessage(x.message||"تعذر تعديل القاعدة");return}await load()}
 async function runRules(){setBusy(true);try{const r=await api("/api/admin/enterprise",{method:"POST",body:JSON.stringify({action:"run-rules"})});const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر تشغيل القواعد");return}setMessage(`تم فحص القواعد — ${x.affected||0} طلب تم تحديثه`);await load()}finally{setBusy(false)}}
 async function resolveError(e:ErrorRow){await api("/api/admin/enterprise",{method:"PATCH",body:JSON.stringify({action:"error",id:e.id,resolved:!e.resolved})});await load()}
 async function getStatement(e:FormEvent){e.preventDefault();setBusy(true);try{const q=new URLSearchParams({action:"statement",company:statementForm.company,from:statementForm.from,to:statementForm.to});const r=await api(`/api/admin/enterprise?${q}`);const x=await r.json();if(!r.ok){setMessage(x.message||"تعذر إنشاء الكشف");return}setStatement(x.statement)}finally{setBusy(false)}}
 const unresolved=useMemo(()=>errors.filter(e=>!e.resolved),[errors]);
 if(!token&&!loading)return <main dir="rtl" className="grid min-h-screen place-items-center bg-[#071f2b] p-6 text-white"><div className="text-center"><LockKeyhole className="mx-auto size-10 text-[#d6ad68]"/><h1 className="mt-4 text-2xl font-bold">يجب تسجيل الدخول أولاً</h1><a href="/admin" className="mt-5 inline-flex rounded-xl bg-[#d6ad68] px-5 py-3 font-bold text-[#12394d]">العودة للأدمن</a></div></main>;
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#f3f5f7]"><Loader2 className="size-8 animate-spin text-[#1f647b]"/></main>;
 return <main dir="rtl" className="min-h-screen bg-[#f3f5f7] text-[#12364a] print:bg-white">
  <header className="sticky top-0 z-30 border-b bg-[#092a39]/95 text-white backdrop-blur print:hidden"><div className="mx-auto flex max-w-[1600px] items-center gap-3 px-4 py-4 lg:px-8"><a href="/admin" className="grid size-10 place-items-center rounded-xl bg-white/10"><ArrowRight className="size-4"/></a><div className="flex-1"><div className="text-[9px] tracking-[.16em] text-[#d6ad68]">ENTERPRISE ADMINISTRATION</div><h1 className="mt-1 text-xl font-bold">مركز الإدارة المتقدم</h1></div><div className="hidden text-left md:block"><div className="text-xs font-bold">{session?.name||"Administrator"}</div><div className="text-[9px] text-white/45">{roleLabel[session?.role]||session?.role}</div></div><button onClick={()=>load()} className="grid size-10 place-items-center rounded-xl bg-white/10"><RefreshCw className="size-4"/></button></div></header>
  <div className="mx-auto max-w-[1600px] space-y-6 p-4 pb-20 lg:p-8 print:p-0">
   {message&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800 print:hidden">{message}</div>}
   <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 print:hidden"><Kpi icon={<Database/>} label="قاعدة البيانات" value={health?.database.ok?"متصلة":"مشكلة"} sub={health?`${health.database.latencyMs}ms`:"—"} ok={health?.database.ok}/><Kpi icon={<Activity/>} label="Telegram" value={health?.telegram.ok?"جاهز":"غير جاهز"} sub={health?.telegram.configured?"Configured":"Not configured"} ok={health?.telegram.ok}/><Kpi icon={<Wallet/>} label="بوابة الدفع" value={health?.payments.ok?"جاهزة":"تحتاج مراجعة"} sub={health?.payments.configured?"Configured":"Not configured"} ok={health?.payments.ok}/><Kpi icon={<AlertTriangle/>} label="أخطاء مفتوحة" value={unresolved.length} sub="آخر 7 أيام" ok={unresolved.length===0}/></section>
   <div className="grid gap-6 2xl:grid-cols-2 print:hidden">
    <Card title="الموظفون والصلاحيات" sub="حساب مستقل لكل موظف بدل مشاركة حساب الأدمن"><form onSubmit={createUser} className="grid gap-2 md:grid-cols-5"><input className="field" placeholder="اسم الموظف" value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/><input dir="ltr" className="field" placeholder="username" value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})}/><input dir="ltr" type="password" className="field" placeholder="Password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/><select className="field" value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option value="manager">مدير</option><option value="reception">استقبال</option><option value="accountant">محاسب</option><option value="owner">مالك النظام</option></select><button disabled={busy} className="btn-primary"><UserPlus className="size-4"/>إضافة</button></form><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead><tr className="border-y bg-slate-50 text-[9px] text-slate-400"><th className="p-3">الموظف</th><th>الحساب</th><th>الصلاحية</th><th>آخر دخول</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b"><td className="p-3 font-bold">{u.name}</td><td dir="ltr">@{u.username}</td><td>{roleLabel[u.role]}</td><td>{u.last_login_at?fmt(u.last_login_at):"لم يدخل"}</td><td><button onClick={()=>patchUser(u,{active:!u.active})} className={`rounded-full px-2 py-1 text-[9px] ${u.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{u.active?"فعال":"موقوف"}</button></td><td><button onClick={()=>removeUser(u)} className="text-red-500"><Trash2 className="size-4"/></button></td></tr>)}</tbody></table></div></Card>
    <Card title="Automation Rules" sub="قواعد تشغيل تنفذ فعلياً على الطلبات"><div className="space-y-3">{rules.map(r=><div key={r.id} className="rounded-2xl border p-4"><div className="flex items-center gap-3"><button onClick={()=>patchRule(r,{active:!r.active})} className={`grid size-10 place-items-center rounded-xl ${r.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-400"}`}><Power className="size-4"/></button><div className="flex-1 text-right"><b>{r.name}</b><div className="mt-1 text-[9px] text-slate-400">{r.kind==="delay_priority"?"الطلب الجديد المتأخر يتحول عاجل":"أرشفة الطلبات المكتملة/الملغية القديمة"}</div></div><div className="flex items-center gap-2"><input type="number" min="1" className="w-20 rounded-xl border p-2 text-center" value={r.threshold_value} onChange={e=>patchRule(r,{thresholdValue:Number(e.target.value)})}/><span className="text-[10px] text-slate-400">{r.kind==="delay_priority"?"دقيقة":"يوم"}</span></div></div></div>)}</div><button disabled={busy} onClick={runRules} className="btn-primary mt-4 w-full"><Play className="size-4"/>تشغيل القواعد الآن</button></Card>
   </div>
   <div className="grid gap-6 2xl:grid-cols-[1.1fr_.9fr] print:hidden">
    <Card title="Health & Error Monitor" sub="تشخيص سريع للمشاكل التشغيلية"><div className="grid gap-2 sm:grid-cols-3"><Health name="Database" ok={Boolean(health?.database.ok)} info={health?`${health.database.latencyMs} ms`:"—"}/><Health name="Telegram" ok={Boolean(health?.telegram.ok)} info={health?.telegram.configured?"configured":"missing config"}/><Health name="Payments" ok={Boolean(health?.payments.ok)} info={health?.payments.configured?"configured":"check env"}/></div><div className="mt-4 max-h-[360px] overflow-auto rounded-xl border">{errors.length===0?<div className="p-8 text-center text-sm text-slate-400"><CheckCircle2 className="mx-auto mb-2 size-7 text-emerald-500"/>ماكو أخطاء مسجلة</div>:errors.map(e=><div key={e.id} className="flex gap-3 border-b p-3 last:border-0"><button onClick={()=>resolveError(e)} className={`mt-1 size-3 rounded-full ${e.resolved?"bg-emerald-400":"bg-red-500"}`}/><div className="flex-1 text-right"><div className="flex justify-between gap-3"><span className="text-[9px] text-slate-400">{fmt(e.created_at)}</span><b className="text-xs">{e.source}</b></div><p className="mt-1 text-xs text-slate-600">{e.message}</p></div></div>)}</div></Card>
    <Card title="كشف حساب شركة" sub="ينشئ كشف للفترة مع الطلبات والدفعات"><form onSubmit={getStatement} className="grid gap-2 sm:grid-cols-2"><select className="field sm:col-span-2" value={statementForm.company} onChange={e=>setStatementForm({...statementForm,company:e.target.value})}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.name}>{c.name}</option>)}</select><label className="text-[9px] text-slate-400">من<input type="date" className="field mt-1" value={statementForm.from} onChange={e=>setStatementForm({...statementForm,from:e.target.value})}/></label><label className="text-[9px] text-slate-400">إلى<input type="date" className="field mt-1" value={statementForm.to} onChange={e=>setStatementForm({...statementForm,to:e.target.value})}/></label><button disabled={busy} className="btn-primary sm:col-span-2"><FileText className="size-4"/>إنشاء كشف الحساب</button></form>{statement&&<div className="mt-4 rounded-2xl bg-[#0d3447] p-4 text-white"><div className="text-[9px] text-white/45">{statement.companyName}</div><div className="mt-3 grid grid-cols-3 gap-2"><Mini l="المسافرين" v={statement.passengers}/><Mini l="المستحق" v={money(statement.dueIqd)}/><Mini l="المتبقي" v={money(statement.balanceIqd)}/></div><button onClick={()=>window.print()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#d6ad68] p-3 font-bold text-[#12394d]"><Printer className="size-4"/>طباعة / حفظ PDF</button></div>}</Card>
   </div>
   {statement&&<StatementPrint s={statement}/>} 
  </div>
 </main>
}
function Kpi({icon,label,value,sub,ok}:{icon:any;label:string;value:any;sub:string;ok?:boolean}){return <div className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between"><div className={`grid size-10 place-items-center rounded-xl ${ok?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{icon}</div><div className="text-right"><div className="text-[9px] text-slate-400">{label}</div><b className="mt-2 block text-lg">{value}</b></div></div><div className="mt-3 border-t pt-2 text-[9px] text-slate-400">{sub}</div></div>}
function Card({title,sub,children}:{title:string;sub:string;children:any}){return <section className="rounded-[22px] border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-[9px] text-slate-400">{sub}</p></div><div className="p-5">{children}</div></section>}
function Health({name,ok,info}:{name:string;ok:boolean;info:string}){return <div className={`rounded-xl border p-3 ${ok?"border-emerald-100 bg-emerald-50/40":"border-amber-100 bg-amber-50"}`}><div className="flex justify-between"><span className={`size-2 rounded-full ${ok?"bg-emerald-500":"bg-amber-500"}`}/><b className="text-xs">{name}</b></div><div className="mt-2 text-[9px] text-slate-500">{info}</div></div>}
function Mini({l,v}:{l:string;v:any}){return <div className="rounded-xl bg-white/5 p-3 text-center"><b className="text-sm">{v}</b><div className="mt-1 text-[8px] text-white/40">{l}</div></div>}
function StatementPrint({s}:{s:Statement}){return <section className="hidden print:block print:text-black"><div className="mb-8 flex items-start justify-between border-b-2 border-black pb-5"><div><h1 className="text-2xl font-bold">LOUNGE BAGHDAD</h1><p>Company Statement</p></div><div className="text-right"><h2 className="text-xl font-bold">كشف حساب شركة</h2><p>{s.companyName}</p><p>{s.from} — {s.to}</p></div></div><div className="mb-6 grid grid-cols-4 gap-3"><PrintBox l="عدد الطلبات" v={s.orders.length}/><PrintBox l="المسافرين" v={s.passengers}/><PrintBox l="المستحق" v={money(s.dueIqd)}/><PrintBox l="المتبقي" v={money(s.balanceIqd)}/></div><table className="w-full border-collapse text-right text-xs"><thead><tr><th className="border p-2">الطلب</th><th className="border p-2">الكابتن</th><th className="border p-2">الصالة</th><th className="border p-2">المسافرين</th><th className="border p-2">التاريخ</th><th className="border p-2">الحساب</th></tr></thead><tbody>{s.orders.map((o:any)=><tr key={o.reference}><td className="border p-2">{o.reference}</td><td className="border p-2">{o.captain_name}</td><td className="border p-2">{o.lounge_name}</td><td className="border p-2">{o.passengers}</td><td className="border p-2">{fmt(o.created_at)}</td><td className="border p-2">{money(Number(o.passengers)*s.pricePerPassenger)}</td></tr>)}</tbody></table><div className="mt-8 text-left"><b>المدفوع: {money(s.paidIqd)}</b><br/><b>المتبقي: {money(s.balanceIqd)}</b></div></section>}
function PrintBox({l,v}:{l:string;v:any}){return <div className="border p-3"><div className="text-[9px]">{l}</div><b>{v}</b></div>}
