import { neon } from "@neondatabase/serverless";
function connectionString(){const v=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NEON_DATABASE_URL;if(!v)throw new Error("DATABASE_URL is not configured");return v}
function sql(){return neon(connectionString())}
export async function ensureOpsCompanies(){const db=sql();await db`CREATE TABLE IF NOT EXISTS ops_companies(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,price_iqd BIGINT NOT NULL DEFAULT 40000,billing_type TEXT NOT NULL DEFAULT 'credit',active BOOLEAN NOT NULL DEFAULT TRUE,notes TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS ops_companies_active_idx ON ops_companies(active,name)`;await db`CREATE TABLE IF NOT EXISTS ops_company_settlements(id BIGSERIAL PRIMARY KEY,company_id BIGINT NOT NULL REFERENCES ops_companies(id),period_from DATE NOT NULL,period_to DATE NOT NULL,passengers INT NOT NULL DEFAULT 0,amount_iqd BIGINT NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','invoiced','paid','settled')),invoice_reference TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS ops_company_settlement_idx ON ops_company_settlements(company_id,status,period_to DESC)`}
export async function listOpsCompanies(){await ensureOpsCompanies();const db=sql();return db`SELECT c.id::int,c.name,c.price_iqd,c.billing_type,c.active,c.notes,c.created_at,COUNT(e.id)::int passengers_total,COALESCE(SUM(e.amount_iqd),0)::bigint amount_total FROM ops_companies c LEFT JOIN ops_entries e ON LOWER(e.billing_company)=LOWER(c.name) GROUP BY c.id ORDER BY c.active DESC,c.name ASC`}
export async function getOpsCompanyPrice(name:string){await ensureOpsCompanies();const db=sql();const rows=await db`SELECT id::int,name,price_iqd,billing_type FROM ops_companies WHERE active=TRUE AND LOWER(name)=LOWER(${name.trim()}) LIMIT 1`;return rows[0]||null}
export async function upsertOpsCompany(input:{id?:number;name:string;priceIqd:number;billingType:string;active?:boolean;notes?:string}){await ensureOpsCompanies();const db=sql();if(input.id){const rows=await db`UPDATE ops_companies SET name=${input.name.trim()},price_iqd=${Math.max(0,Math.round(input.priceIqd||40000))},billing_type=${input.billingType||'credit'},active=${input.active!==false},notes=${input.notes||''},updated_at=NOW() WHERE id=${input.id} RETURNING id::int,name,price_iqd,billing_type,active,notes`;return rows[0]}const rows=await db`INSERT INTO ops_companies(name,price_iqd,billing_type,active,notes) VALUES(${input.name.trim()},${Math.max(0,Math.round(input.priceIqd||40000))},${input.billingType||'credit'},${input.active!==false},${input.notes||''}) ON CONFLICT(name) DO UPDATE SET price_iqd=EXCLUDED.price_iqd,billing_type=EXCLUDED.billing_type,active=EXCLUDED.active,notes=EXCLUDED.notes,updated_at=NOW() RETURNING id::int,name,price_iqd,billing_type,active,notes`;return rows[0]}
export async function createCompanySettlement(input:{companyId:number;from:string;to:string;status?:string;invoiceReference?:string;notes?:string}){await ensureOpsCompanies();const db=sql();const companies=await db`SELECT name FROM ops_companies WHERE id=${input.companyId}`;if(!companies[0])throw new Error('الشركة غير موجودة');const name=String((companies[0] as any).name);const totals=await db`SELECT COUNT(*)::int passengers,COALESCE(SUM(amount_iqd),0)::bigint amount_iqd FROM ops_entries WHERE LOWER(billing_company)=LOWER(${name}) AND created_at::date BETWEEN ${input.from}::date AND ${input.to}::date`;const t:any=totals[0]||{};const rows=await db`INSERT INTO ops_company_settlements(company_id,period_from,period_to,passengers,amount_iqd,status,invoice_reference,notes) VALUES(${input.companyId},${input.from}::date,${input.to}::date,${Number(t.passengers||0)},${Number(t.amount_iqd||0)},${input.status||'pending'},${input.invoiceReference||''},${input.notes||''}) RETURNING id::int,company_id::int,period_from,period_to,passengers,amount_iqd,status,invoice_reference,notes,created_at`;return rows[0]}
export async function listCompanySettlements(){await ensureOpsCompanies();const db=sql();return db`SELECT s.id::int,s.company_id::int,c.name company_name,s.period_from,s.period_to,s.passengers,s.amount_iqd,s.status,s.invoice_reference,s.notes,s.created_at FROM ops_company_settlements s JOIN ops_companies c ON c.id=s.company_id ORDER BY s.created_at DESC LIMIT 200`}
export async function updateCompanySettlement(id:number,status:string,invoiceReference?:string,notes?:string){await ensureOpsCompanies();const db=sql();const rows=await db`UPDATE ops_company_settlements SET status=${status},invoice_reference=COALESCE(${invoiceReference??null},invoice_reference),notes=COALESCE(${notes??null},notes),updated_at=NOW() WHERE id=${id} RETURNING id::int,company_id::int,period_from,period_to,passengers,amount_iqd,status,invoice_reference,notes`;return rows[0]||null}
