"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Building2,CircleDollarSign,Download,FileText,Loader2,LogOut,Printer,RefreshCw,Search,Wallet} from "lucide-react";

type Company={name:string;price_per_passenger:number;notes:string;orders:number;passengers:number;paid_iqd:number;due_iqd:number};
type Order={reference:string;captain_name:string;captain_phone:string;lounge_name:string;passengers:number;bags:number;carts:number;passenger_phone:string;status:string;created_at:string};
type Payment={id:number;amount_iqd:number;note:string;created_at:string};
type PromoBooking={reference:string;customer_name:string;phone:string;passengers:number;total_iqd:number;discount_iqd:number;created_at:string;code:string};
type Statement={companyName:string;from:string;to:string;pricePerPassenger:number;notes:string;opening:{passengers:number;dueIqd:number;paidIqd:number;balanceIqd:number};orders:Order[];passengers:number;dueIqd:number;payments:Payment[];paidIqd:number;balanceIqd:number;closingBalanceIqd:number;promoBookings:PromoBooking[];promoBookingsCount:number;promoPassengers:number;promoDiscountIqd:number};
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(Number(n||0))+" د.ع";
const dt=(v:string)=>new Intl.DateTimeFormat("ar-IQ",{timeZone:"Asia/Baghdad",dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const statusLabel:Record<string,string>={new:"جديد",received:"تم الاستلام",in_progress:"قيد التنفيذ",completed:"مكتمل",cancelled:"ملغي"};

export default function AccountingPage(){
 const [token,setToken]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [name,setName]=useState("المحاسب");const [companies,setCompanies]=useState<Company[]>([]);const [statement,setStatement]=useState<Statement|null>(null);const [search,setSearch]=useState("");
 const today=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Baghdad"});const monthStart=today.slice(0,8)+"01";const [form,setForm]=useState({company:"",from:monthStart,to:today});const [payment,setPayment]=useState({companyName:"",amountIqd:"",note:""});
 useEffect(()=>{const t=sessionStorage.getItem("accountingAdminToken")||sessionStorage.getItem("mainAdminToken")||"";if(!t){location.replace("/admin");return}setToken(t);void load(t)},[]);
 async function api(path:string,opt:RequestInit={},t=token){return fetch(path,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`}})}
 async function load(t=token){setLoading(true);setError("");try{const r=await api("/api/admin/accounting",{},t);const x=await r.json();if(r.status===401||r.status===403){logout();return}if(!r.ok)throw new Error(x.message||"تعذر تحميل الحسابات");setName(x.session?.name||"المحاسب");setCompanies(x.companies||[])}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
 async function fetchStatement(company=form.company,from=form.from,to=form.to){if(!company)return;setBusy(true);setError("");try{const q=new URLSearchParams({company,from,to});const r=await api(`/api/admin/accounting?${q}`);const x=await r.json();if(!r.ok)throw new Error(x.message||"تعذر إنشاء الكشف");setStatement(x.statement);setForm({company,from,to});setPayment(v=>({...v,companyName:company}))}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الكشف")}finally{setBusy(false)}}
 async function statementSubmit(e:FormEvent){e.preventDefault();await fetchStatement()}
 async function paymentSubmit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const amount=Number(payment.amountIqd.replace(/,/g,""));if(!payment.companyName||!Number.isFinite(amount)||amount<=0)throw new Error("اختر الشركة وأدخل مبلغ صحيح");const r=await api("/api/admin/accounting",{method:"POST",body:JSON.stringify({...payment,amountIqd:amount})});const x=await r.json();if(!r.ok)throw new Error(x.message||"تعذر تسجيل الدفعة");setPayment(v=>({...v,amountIqd:"",note:""}));await load();if(form.company)await fetchStatement()}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل الدفعة")}finally{setBusy(false)}}
 function logout(){sessionStorage.removeItem("accountingAdminToken");sessionStorage.removeItem("mainAdminToken");location.replace("/admin")}
 function exportCsv(){if(!statement)return;const rows=[["نوع","المرجع","التاريخ","الوصف","مسافرون","مدين","دائن"],["رصيد افتتاحي","",statement.from,"الرصيد قبل بداية الفترة","",statement.opening.balanceIqd>0?statement.opening.balanceIqd:0,statement.opening.balanceIqd<0?Math.abs(statement.opening.balanceIqd):0],...statement.orders.map(o=>["طلب",o.reference,o.created_at,`${o.captain_name} - ${o.lounge_name}`,o.passengers,o.status==="cancelled"?0:o.passengers*statement.pricePerPassenger,0]),...statement.payments.map(p=>["دفعة",String(p.id),p.created_at,p.note||"دفعة",0,0,p.amount_iqd])];const csv="\uFEFF"+rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`statement-${statement.companyName}-${statement.from}-${statement.to}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const filtered=useMemo(()=>companies.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())),[companies,search]);
 const totals=useMemo(()=>companies.reduce((a,c)=>({due:a.due+Number(c.due_iqd||0),paid:a.paid+Number(c.paid_iqd||0)}),{due:0,paid:0}),[companies]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#eef2f4]"><Loader2 className="size-8 animate-spin text-[#1f647b]"/></main>;
 return <main dir="rtl" className="min-h-screen bg-[#eef2f4] text-[#14384b] print:bg-white">
  <header className="sticky top-0 z-30 border-b border-white/10 bg-[#072a39] text-white print:hidden"><div className="mx-auto flex max-w-[1550px] items-center gap-3 px-4 py-4 lg:px-8"><div className="grid size-11 place-items-center rounded-2xl bg-[#d6ad68] text-[#12394d]"><Wallet className="size-5"/></div><div className="flex-1"><div className="text-[9px] tracking-[.18em] text-[#d6ad68]">FINANCE & COMPANY LEDGER</div><h1 className="mt-1 text-xl font-bold">مركز الحسابات وكشوف الشركات</h1><p className="mt-1 text-[10px] text-white/50">{name} · بيانات مالية مباشرة من قاعدة البيانات</p></div><button onClick={()=>load()} className="grid size-10 place-items-center rounded-xl bg-white/10"><RefreshCw className="size-4"/></button><button onClick={logout} className="grid size-10 place-items-center rounded-xl bg-white/10"><LogOut className="size-4"/></button></div></header>
  <div className="mx-auto max-w-[1550px] space-y-6 p-4 lg:p-8 print:p-0">
   {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700 print:hidden">{error}</div>}
   <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 print:hidden"><Kpi label="إجمالي المستحق" value={money(totals.due)} icon={<CircleDollarSign/>}/><Kpi label="إجمالي المدفوع" value={money(totals.paid)} icon={<Wallet/>}/><Kpi label="الرصيد المتبقي" value={money(totals.due-totals.paid)} icon={<FileText/>}/><Kpi label="عدد الشركات" value={String(companies.length)} icon={<Building2/>}/></section>
   <div className="grid gap-6 2xl:grid-cols-[1.5fr_.65fr] print:hidden">
    <Card title="حسابات الشركات" sub="اضغط على أي شركة لفتح كشفها مباشرة"><div className="mb-4 flex items-center gap-2 rounded-xl border bg-slate-50 px-3"><Search className="size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث باسم الشركة..." className="h-11 flex-1 bg-transparent text-xs outline-none"/></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-right text-xs"><thead><tr className="border-y bg-slate-50 text-[9px] text-slate-400"><th className="p-3">الشركة</th><th>الطلبات</th><th>المسافرون</th><th>سعر الشخص</th><th>المستحق</th><th>المدفوع</th><th>المتبقي</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.name} className="border-b hover:bg-slate-50"><td className="p-3 font-bold">{c.name}</td><td>{c.orders}</td><td>{c.passengers}</td><td>{money(c.price_per_passenger)}</td><td>{money(c.due_iqd)}</td><td className="text-emerald-700">{money(c.paid_iqd)}</td><td className={`font-bold ${Number(c.due_iqd)-Number(c.paid_iqd)>0?"text-amber-700":"text-emerald-700"}`}>{money(Number(c.due_iqd)-Number(c.paid_iqd))}</td><td><button onClick={()=>{setForm(v=>({...v,company:c.name}));setPayment(v=>({...v,companyName:c.name}));void fetchStatement(c.name)}} className="rounded-lg bg-[#eaf2f5] px-3 py-2 text-[10px] font-bold text-[#1f6077]">فتح الكشف</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-8 text-center text-sm text-slate-400">ماكو شركات مطابقة</div>}</div></Card>
    <div className="space-y-6"><Card title="إنشاء كشف حساب" sub="حدد الشركة والفترة المالية"><form onSubmit={statementSubmit} className="space-y-3"><select className="field" value={form.company} onChange={e=>{setForm({...form,company:e.target.value});setPayment(v=>({...v,companyName:e.target.value}))}}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.name} value={c.name}>{c.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><label className="text-[9px] text-slate-400">من<input className="field mt-1" type="date" value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/></label><label className="text-[9px] text-slate-400">إلى<input className="field mt-1" type="date" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}/></label></div><button disabled={busy||!form.company} className="btn w-full">{busy?<Loader2 className="size-4 animate-spin"/>:<FileText className="size-4"/>}إنشاء الكشف</button></form></Card><Card title="تسجيل دفعة" sub="تدخل مباشرة في دفتر الشركة"><form onSubmit={paymentSubmit} className="space-y-3"><select className="field" value={payment.companyName} onChange={e=>setPayment({...payment,companyName:e.target.value})}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.name} value={c.name}>{c.name}</option>)}</select><input className="field" inputMode="numeric" placeholder="المبلغ بالدينار" value={payment.amountIqd} onChange={e=>setPayment({...payment,amountIqd:e.target.value.replace(/[^0-9]/g,"")})}/><input className="field" placeholder="رقم وصل أو ملاحظة" value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/><button disabled={busy||!payment.companyName||!payment.amountIqd} className="btn w-full">تسجيل الدفعة</button></form></Card></div>
   </div>
   {statement&&<StatementView statement={statement} exportCsv={exportCsv}/>} 
  </div>
 </main>
}

function StatementView({statement,exportCsv}:{statement:Statement;exportCsv:()=>void}){const billable=statement.orders.filter(o=>o.status!=="cancelled");return <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm print:border-0 print:p-0 print:shadow-none lg:p-8"><div className="flex flex-wrap items-start justify-between gap-4 border-b pb-6"><div className="flex gap-2 print:hidden"><button onClick={()=>window.print()} className="btn"><Printer className="size-4"/>طباعة / PDF</button><button onClick={exportCsv} className="btn-secondary"><Download className="size-4"/>Excel CSV</button></div><div className="text-right"><div className="text-[10px] font-bold tracking-[.16em] text-[#b18b50]">LOUNGE BAGHDAD · COMPANY STATEMENT</div><h2 className="mt-2 text-3xl font-bold">{statement.companyName}</h2><p className="mt-2 text-xs text-slate-500">كشف حساب من {statement.from} إلى {statement.to}</p>{statement.notes&&<p className="mt-2 text-[10px] text-slate-400">{statement.notes}</p>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Mini label="الرصيد الافتتاحي" value={money(statement.opening.balanceIqd)}/><Mini label="مستحقات الفترة" value={money(statement.dueIqd)}/><Mini label="دفعات الفترة" value={money(statement.paidIqd)}/><Mini label="الرصيد الختامي" value={money(statement.closingBalanceIqd)} strong/><Mini label="مسافرو الفترة" value={String(statement.passengers)}/></div>
 <div className="mt-8 grid gap-8 xl:grid-cols-[1.3fr_.7fr]"><div><h3 className="mb-3 font-bold">حركة الطلبات</h3><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[760px] text-right text-xs"><thead><tr className="bg-slate-50 text-[9px] text-slate-400"><th className="p-3">الطلب</th><th>التاريخ</th><th>الكابتن</th><th>الصالة</th><th>المسافرون</th><th>الحالة</th><th>المبلغ</th></tr></thead><tbody>{statement.orders.map(o=><tr key={o.reference} className={`border-t ${o.status==="cancelled"?"bg-red-50/40 text-slate-400":""}`}><td className="p-3 font-mono">{o.reference}</td><td>{dt(o.created_at)}</td><td>{o.captain_name}</td><td>{o.lounge_name}</td><td>{o.passengers}</td><td>{statusLabel[o.status]||o.status}</td><td className="font-bold">{o.status==="cancelled"?"0":money(o.passengers*statement.pricePerPassenger)}</td></tr>)}</tbody></table>{!statement.orders.length&&<div className="p-8 text-center text-sm text-slate-400">لا توجد طلبات في هذه الفترة</div>}</div><div className="mt-3 text-[10px] text-slate-400">الطلبات المحتسبة: {billable.length} · سعر الشخص: {money(statement.pricePerPassenger)} · الطلب الملغي لا يدخل ضمن المستحق.</div></div>
 <div><h3 className="mb-3 font-bold">الدفعات</h3><div className="rounded-xl border">{statement.payments.length?statement.payments.map(p=><div key={p.id} className="flex items-center justify-between gap-3 border-b p-3 last:border-0"><div><b className="text-emerald-700">{money(p.amount_iqd)}</b><div className="mt-1 text-[9px] text-slate-400">{p.note||"دفعة"}</div></div><div className="text-[9px] text-slate-400">{dt(p.created_at)}</div></div>):<div className="p-8 text-center text-xs text-slate-400">لا توجد دفعات ضمن الفترة</div>}</div><div className="mt-5 rounded-2xl bg-[#082b3a] p-5 text-white"><div className="text-[10px] text-white/50">الرصيد المطلوب بعد نهاية الفترة</div><div className="mt-2 text-2xl font-bold text-[#d6ad68]">{money(statement.closingBalanceIqd)}</div></div></div></div>
 {statement.promoBookingsCount>0&&<div className="mt-8 border-t pt-6"><div className="flex items-end justify-between gap-4"><div><h3 className="font-bold">حجوزات استخدمت خصم الشركة</h3><p className="mt-1 text-[10px] text-slate-400">للمتابعة التسويقية فقط ولا تدخل تلقائياً في ذمم الكباتن.</p></div><div className="text-left text-xs"><b>{statement.promoBookingsCount} حجز</b><div className="text-emerald-700">خصومات {money(statement.promoDiscountIqd)}</div></div></div><div className="mt-3 overflow-x-auto rounded-xl border"><table className="w-full min-w-[650px] text-right text-xs"><thead><tr className="bg-slate-50"><th className="p-3">الحجز</th><th>الزبون</th><th>المسافرون</th><th>كود الخصم</th><th>قيمة الخصم</th><th>التاريخ</th></tr></thead><tbody>{statement.promoBookings.map(o=><tr key={o.reference} className="border-t"><td className="p-3 font-mono">{o.reference}</td><td>{o.customer_name}</td><td>{o.passengers}</td><td dir="ltr">{o.code}</td><td>{money(o.discount_iqd)}</td><td>{dt(o.created_at)}</td></tr>)}</tbody></table></div></div>}
 </section>}
function Card({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><p className="mt-1 text-[10px] text-slate-400">{sub}</p><div className="mt-4">{children}</div></section>}
function Kpi({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#edf4f6] text-[#286b82]">{icon}</div><div><div className="text-[10px] text-slate-400">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div></div></div>}
function Mini({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`rounded-xl p-4 ${strong?"bg-[#fff7e8] ring-1 ring-[#e7c98e]":"bg-slate-50"}`}><div className="text-[9px] text-slate-400">{label}</div><div className={`mt-1 font-bold ${strong?"text-lg text-[#986c28]":""}`}>{value}</div></div>}
