"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowRight,Building2,CircleDollarSign,FileText,Loader2,LogOut,Printer,RefreshCw,Wallet} from "lucide-react";

type Company={name:string;price_per_passenger:number;notes:string;orders:number;passengers:number;paid_iqd:number;due_iqd:number};
type Statement={companyName:string;from:string;to:string;pricePerPassenger:number;orders:{reference:string;captain_name:string;lounge_name:string;passengers:number;created_at:string}[];passengers:number;dueIqd:number;payments:{amount_iqd:number;note:string;created_at:string}[];paidIqd:number;balanceIqd:number;notes:string};
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(Number(n||0))+" د.ع";
const date=(v:string)=>new Intl.DateTimeFormat("ar-IQ",{timeZone:"Asia/Baghdad",dateStyle:"medium"}).format(new Date(v));

export default function AccountingPage(){
 const [token,setToken]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [name,setName]=useState("المحاسب");const [companies,setCompanies]=useState<Company[]>([]);const [statement,setStatement]=useState<Statement|null>(null);
 const today=new Date().toISOString().slice(0,10);const monthStart=today.slice(0,8)+"01";const [form,setForm]=useState({company:"",from:monthStart,to:today});const [payment,setPayment]=useState({companyName:"",amountIqd:"",note:""});
 useEffect(()=>{const t=sessionStorage.getItem("accountingAdminToken")||sessionStorage.getItem("mainAdminToken")||"";if(!t){location.replace("/admin");return}setToken(t);void load(t)},[]);
 async function api(path:string,opt:RequestInit={},t=token){return fetch(path,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`}})}
 async function load(t=token){setLoading(true);setError("");try{const r=await api("/api/admin/accounting",{},t);const x=await r.json();if(r.status===401||r.status===403){logout();return}if(!r.ok)throw new Error(x.message||"تعذر تحميل الحسابات");setName(x.session?.name||"المحاسب");setCompanies(x.companies||[])}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
 async function statementSubmit(e:FormEvent){e.preventDefault();if(!form.company)return;setBusy(true);setError("");try{const q=new URLSearchParams(form);const r=await api(`/api/admin/accounting?${q}`);const x=await r.json();if(!r.ok){setError(x.message||"تعذر إنشاء الكشف");return}setStatement(x.statement)}finally{setBusy(false)}}
 async function paymentSubmit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await api("/api/admin/accounting",{method:"POST",body:JSON.stringify(payment)});const x=await r.json();if(!r.ok){setError(x.message||"تعذر تسجيل الدفعة");return}setPayment({companyName:"",amountIqd:"",note:""});await load();if(form.company)await statementSubmit({preventDefault(){}} as FormEvent)}finally{setBusy(false)}}
 function logout(){sessionStorage.removeItem("accountingAdminToken");sessionStorage.removeItem("mainAdminToken");location.replace("/admin")}
 const totals=useMemo(()=>companies.reduce((a,c)=>({due:a.due+Number(c.due_iqd||0),paid:a.paid+Number(c.paid_iqd||0)}),{due:0,paid:0}),[companies]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#f3f6f7]"><Loader2 className="size-8 animate-spin text-[#1f647b]"/></main>;
 return <main dir="rtl" className="min-h-screen bg-[#f3f6f7] text-[#16384b] print:bg-white">
  <header className="sticky top-0 z-30 bg-[#082b3a] text-white print:hidden"><div className="mx-auto flex max-w-[1450px] items-center gap-3 px-4 py-4 lg:px-8"><div className="grid size-11 place-items-center rounded-2xl bg-[#d6ad68] text-[#12394d]"><Wallet className="size-5"/></div><div className="flex-1"><div className="text-[9px] tracking-[.18em] text-[#d6ad68]">ACCOUNTING WORKSPACE</div><h1 className="mt-1 text-xl font-bold">مركز الحسابات</h1><p className="mt-1 text-[10px] text-white/45">{name} · صلاحية محاسب فقط</p></div><button onClick={()=>load()} className="grid size-10 place-items-center rounded-xl bg-white/10"><RefreshCw className="size-4"/></button><button onClick={logout} className="grid size-10 place-items-center rounded-xl bg-white/10"><LogOut className="size-4"/></button></div></header>
  <div className="mx-auto max-w-[1450px] space-y-6 p-4 lg:p-8 print:p-0">
   {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700 print:hidden">{error}</div>}
   <section className="grid gap-3 sm:grid-cols-3 print:hidden"><Kpi label="إجمالي المستحق" value={money(totals.due)} icon={<CircleDollarSign/>}/><Kpi label="إجمالي المدفوع" value={money(totals.paid)} icon={<Wallet/>}/><Kpi label="الرصيد المتبقي" value={money(totals.due-totals.paid)} icon={<FileText/>}/></section>
   <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr] print:hidden"><Card title="حسابات الشركات" sub="عرض مالي فقط بدون صلاحيات تشغيل"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right text-xs"><thead><tr className="border-y bg-slate-50 text-[9px] text-slate-400"><th className="p-3">الشركة</th><th>الطلبات</th><th>المسافرون</th><th>سعر الشخص</th><th>المستحق</th><th>المدفوع</th><th>المتبقي</th></tr></thead><tbody>{companies.map(c=><tr key={c.name} className="border-b"><td className="p-3 font-bold">{c.name}</td><td>{c.orders}</td><td>{c.passengers}</td><td>{money(c.price_per_passenger)}</td><td>{money(c.due_iqd)}</td><td className="text-emerald-700">{money(c.paid_iqd)}</td><td className="font-bold text-amber-700">{money(Number(c.due_iqd)-Number(c.paid_iqd))}</td></tr>)}</tbody></table></div></Card>
   <div className="space-y-6"><Card title="كشف حساب" sub="اختر الشركة والفترة"><form onSubmit={statementSubmit} className="space-y-3"><select className="field" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.name}>{c.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className="field" type="date" value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/><input className="field" type="date" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}/></div><button disabled={busy} className="btn">إنشاء الكشف</button></form></Card><Card title="تسجيل دفعة" sub="تضاف مباشرة لحساب الشركة"><form onSubmit={paymentSubmit} className="space-y-3"><select className="field" value={payment.companyName} onChange={e=>setPayment({...payment,companyName:e.target.value})}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.name}>{c.name}</option>)}</select><input className="field" inputMode="numeric" placeholder="المبلغ بالدينار" value={payment.amountIqd} onChange={e=>setPayment({...payment,amountIqd:e.target.value})}/><input className="field" placeholder="ملاحظة اختيارية" value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/><button disabled={busy} className="btn">تسجيل الدفعة</button></form></Card></div></div>
   {statement&&<section className="rounded-[26px] bg-white p-5 shadow-sm print:shadow-none lg:p-8"><div className="flex items-start justify-between gap-4"><button onClick={()=>window.print()} className="btn print:hidden"><Printer className="size-4"/>طباعة / PDF</button><div className="text-right"><div className="text-[10px] text-slate-400">كشف حساب شركة</div><h2 className="mt-1 text-2xl font-bold">{statement.companyName}</h2><p className="mt-2 text-xs text-slate-500">من {statement.from} إلى {statement.to}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-4"><Mini label="المسافرون" value={statement.passengers}/><Mini label="المستحق" value={money(statement.dueIqd)}/><Mini label="المدفوع" value={money(statement.paidIqd)}/><Mini label="المتبقي" value={money(statement.balanceIqd)}/></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-right text-xs"><thead><tr className="border-y bg-slate-50"><th className="p-3">رقم الطلب</th><th>الكابتن</th><th>الصالة</th><th>المسافرون</th><th>التاريخ</th></tr></thead><tbody>{statement.orders.map((o,i)=><tr key={i} className="border-b"><td className="p-3 font-mono">{o.reference}</td><td>{o.captain_name}</td><td>{o.lounge_name}</td><td>{o.passengers}</td><td>{date(o.created_at)}</td></tr>)}</tbody></table></div></section>}
  </div>
 </main>
}
function Card({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><p className="mt-1 text-[10px] text-slate-400">{sub}</p><div className="mt-4">{children}</div></section>}
function Kpi({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="rounded-[22px] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#edf4f6] text-[#286b82]">{icon}</div><div><div className="text-[10px] text-slate-400">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div></div></div>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-[9px] text-slate-400">{label}</div><div className="mt-1 font-bold">{value}</div></div>}
